## Practice

In [1]:
import numpy as np

In [3]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [4]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#### Eelement wise multiplication

In [8]:
a= np.array([1,2,3,5]).reshape(2,-1)
b = np.arange(10,50,10).reshape(-1,2)
print("Matrix a : \n",a)
print("\nMatrix b : \n",b)
print("\nMatrix a*b : \n",a*b)


Matrix a : 
 [[1 2]
 [3 5]]

Matrix b : 
 [[10 20]
 [30 40]]

Matrix a*b : 
 [[ 10  40]
 [ 90 200]]


#### Now matrix multiplication

In [11]:

print("Matrix a : \n",a)
print("\nMatrix b : \n",b)
print("\nMatrix a*b : \n",a@b)

Matrix a : 
 [[1 2]
 [3 5]]

Matrix b : 
 [[10 20]
 [30 40]]

Matrix a*b : 
 [[ 70 100]
 [180 260]]


#### Modifing array 

In [13]:
print("Before : \n",a)
a*= 10
print("\nAfter : \n",a)

Before : 
 [[1 2]
 [3 5]]

After : 
 [[10 20]
 [30 50]]


#### With integer and float



In [18]:
a1 = np.arange(5)
a2 = np.full(5,2.3)
print(a1)
print(a2)


[0 1 2 3 4]
[2.3 2.3 2.3 2.3 2.3]


In [22]:
c1 = a1+a2
print(c1)
a2+=a1
print(a2)
a1+= a2

[ 2.3  4.3  6.3  8.3 10.3]
[ 2.3  4.3  6.3  8.3 10.3]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

#### min max , sum, 

In [31]:
ab1 = np.random.randint(0,100,10)
print(ab1)
print("Minimumm value : ",ab1.min())
print("Maximum  value : ",ab1.max())
print("Sum  : ",ab1.sum())
print("cumSum  : ",ab1.cumsum())

[42 18 46 23 29 74 66 44 99 30]
Minimumm value :  18
Maximum  value :  99
Sum  :  471
cumSum  :  [ 42  60 106 129 158 232 298 342 441 471]


##  Indexing,Slicingand  Iterating

In [35]:
a=np.arange(10)**3
a[:6:2]=-1000
a[::-1]
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_22428\548865729.py:5: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [36]:
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

#### Each row in each 2nd column

In [44]:
b[...,1]
# or
b[:,1]

array([ 1, 11, 21, 31, 41])

In [39]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [40]:
b[1:3]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

#### Shape manipulation


In [6]:

a = np.array([[1, 2],
              [3, 4]])  # shape: (2, 2)
np.swapaxes(a, 0, 1)
# print(np.swapaxes(a, 0, 1))
print(np.swapaxes(a,  1,0))
# print(np.swapaxes(a, 0, 2))


[[1 3]
 [2 4]]


##### expand_dims()

In [8]:
a = np.array([1, 2, 3])        # shape: (3,)
b = np.expand_dims(a, axis=0) # shape: (1, 3)
c = np.expand_dims(a, axis=1) # shape: (1, 3)
print(b)
print(c)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [3]:
data = [1,2,3,45]
a1 = np.array(data)
print(a1)
data.append(100)
print(a1)

[ 1  2  3 45]
[ 1  2  3 45]


In [6]:
data1 = [1,2,3,45]
a2 = np.asarray(data1,copy=False)
print(a2)
data1.append(100)
print(a2)

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

In [13]:
data = [1,2,3,45]
a1 = np.array([data], ndmin=1)
print(a1)
print(a1.ndim)

[[ 1  2  3 45]]
2


In [18]:
arr2 = np.zeros([3,2])
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
arr2 = np.zeros((3,2))
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
arr2 = np.zeros((3,2,1))
print(arr2)

[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


In [21]:
arr2 = np.zeros((3,2,1,2))
print(arr2)

[[[[0. 0.]]

  [[0. 0.]]]


 [[[0. 0.]]

  [[0. 0.]]]


 [[[0. 0.]]

  [[0. 0.]]]]


In [40]:
np.random.seed(2)
arr= np.random.randint(1,200,(2,3))
print(arr)

[[169  16  73]
 [ 23  44  76]]


In [41]:
arr[1,2]

np.int32(76)

In [42]:
arr[1][2]

np.int32(76)

In [53]:
np.random.seed(11)
arr2= np.random.randint(1,100,(2,3))
print(arr2)

[[26 64 81]
 [92 82 56]]


In [54]:
np.maximum(arr,arr2)

array([[169,  64,  81],
       [ 92,  82,  76]], dtype=int32)

In [55]:
np.minimum(arr,arr2)

array([[26, 16, 73],
       [23, 44, 56]], dtype=int32)

In [65]:
arr3 =np.array([1,2,3,4,5,6,np.nan])
arr4 =np.array([np.nan,3,5,np.nan,4,2,6])
print(arr3)
print(arr4)

[ 1.  2.  3.  4.  5.  6. nan]
[nan  3.  5. nan  4.  2.  6.]


In [66]:
print(arr3.max())
print(arr3.min())
# print(arr3.fmax()) # AttributeError: 'numpy.ndarray' object has no attribute 'fmax'
# print(arr3.fmin()) # AttributeError: 'numpy.ndarray' object has no attribute 'fmax'
print(np.fmax(arr3,arr4))
print(np.fmin(arr3,arr4))
print(np.fmod(arr3,arr4))


nan
nan
[1. 3. 5. 4. 5. 6. 6.]
[1. 2. 3. 4. 4. 2. 6.]
[nan  2.  3. nan  1.  0. nan]


In [68]:
print(np.abs(arr4))

[nan  3.  5. nan  4.  2.  6.]


In [69]:
arr2

array([[26, 64, 81],
       [92, 82, 56]], dtype=int32)

In [70]:
arr2 = np.swapaxes(arr2,0,1)
print(arr2)

[[26 92]
 [64 82]
 [81 56]]


In [71]:
arr3



array([ 1.,  2.,  3.,  4.,  5.,  6., nan])

In [77]:
arr3=np.expand_dims(arr3,1)

In [78]:
arr3


array([[[[ 1.]]],


       [[[ 2.]]],


       [[[ 3.]]],


       [[[ 4.]]],


       [[[ 5.]]],


       [[[ 6.]]],


       [[[nan]]]])

In [79]:
arr3=np.expand_dims(arr3,[3,4])
arr3

array([[[[[[ 1.]]]]],




       [[[[[ 2.]]]]],




       [[[[[ 3.]]]]],




       [[[[[ 4.]]]]],




       [[[[[ 5.]]]]],




       [[[[[ 6.]]]]],




       [[[[[nan]]]]]])

In [80]:
arr3= np.squeeze(arr3)
arr3

array([ 1.,  2.,  3.,  4.,  5.,  6., nan])

In [81]:
print(arr2)

[[26 92]
 [64 82]
 [81 56]]


In [84]:
arr2 = np.squeeze(arr2)
arr2 = np.expand_dims(arr,2)
print(arr2)
arr2 = np.rollaxis(arr2,2,0)
print("-"*20)
print(arr2)

[[[169]
  [ 16]
  [ 73]]

 [[ 23]
  [ 44]
  [ 76]]]
--------------------
[[[169  16  73]
  [ 23  44  76]]]


In [85]:
arr2.shape

(1, 2, 3)

In [86]:
#MOveAxis
arr2 = np.moveaxis(arr2,[0,1],[2,0])

In [87]:
arr2.shape


(2, 3, 1)