# Day - 7 : Core Math Assignment solution

## CORE MATHEMATICAL OPERATIONS

In [1]:
import numpy as np

In [2]:
arr = np.array([12, 25, 7, 18, 30, 9, 15, 22, 5, 27])

# A. Aggregation

#### 1. Find the sum of all elements in arr.

In [3]:
arr.sum()

np.int64(170)

In [4]:
print(np.sum(arr))
print(arr.sum())

170
170


#### 2.  Find the average value of arr.

In [5]:
np.mean(arr)

np.float64(17.0)

In [6]:
arr.mean()

np.float64(17.0)

In [7]:
print(arr.mean())

17.0


#### 3. Find the largest number in arr.

In [8]:
arr.max()

np.int64(30)

In [9]:
np.max(arr)

np.int64(30)

In [10]:
print(np.max(arr))

30


#### 4. Find the smallest number in arr.

In [11]:
print(np.min(arr))

5


In [12]:
print(arr.min())

5


#### 5. Find the position (index) of the highest value in arr.

In [13]:
print(np.argmax(arr))

4


In [14]:
print(arr.argmax())

4


#### 6. Find the position (index) of the lowest value in arr.

In [15]:
print(np.min(arr))

5


In [16]:
print(arr.min())

5


#### 7. Find how much values are spread in arr.

In [17]:
print(np.max(arr)-np.min(arr))

25


In [18]:
print(np.ptp(arr))

25


#### 8. Find variance of arr.

In [19]:
print(np.var(arr))

69.6


In [20]:
print(arr.var())

69.6


#### 9. Find running total of arr (step-by-step addition).

In [21]:
np.cumsum(arr)

array([ 12,  37,  44,  62,  92, 101, 116, 138, 143, 170])

In [22]:
arr.cumsum()

array([ 12,  37,  44,  62,  92, 101, 116, 138, 143, 170])

#### 10. Find difference between highest and lowest value in arr.

In [23]:
print(np.max(arr)-np.min(arr))

25


In [24]:
np.ptp(arr )
# same but built in 

np.int64(25)

### 2D ARRAY

In [25]:
b = np.array([
    [10, 20, 30],
    [5, 15, 25],
    [8, 12, 18],
    [22, 27, 35]
])

#### 1. Find total of each row

In [26]:
np.sum(b) # total

np.int64(227)

In [27]:
np.sum(b,axis =1) # axis=1  horizontal x

array([60, 45, 38, 84])

In [28]:
b.sum(axis=1) # same

array([60, 45, 38, 84])

#### 2. Find total of each column

In [29]:
np.sum(b,axis =0) # axis=0  vertical (↓)]

array([ 45,  74, 108])

#### 3.Find average of each row.

In [30]:
np.mean(b,axis =1)

array([20.        , 15.        , 12.66666667, 28.        ])

#### 4. Find average of each column.

In [31]:
print(b.mean(axis=0))

[11.25 18.5  27.  ]


#### 5. Find total sum of all elements in array.

In [32]:
print(b.sum()) # default axis = None

227


In [33]:
print(b.sum(axis =None))

227


#### 6. Find highest value in each row.

In [34]:
print(np.max(b,axis=1))

[30 25 18 35]


#### 7. Find smallest value in each column.

In [35]:
np.min(b,axis=0)

array([ 5, 12, 18])

#### 8. Find position of highest value in flattened array.

In [36]:
print("Highest values in 2d array : ",np.max(b)) # internally array are flattern and find max 
                                                 # axis by default None

Highest values in 2d array :  35


In [37]:
b.flatten()

array([10, 20, 30,  5, 15, 25,  8, 12, 18, 22, 27, 35])

#### 9. Find range (max - min) of full dataset.

In [38]:
np.max(b)-np.min(b)

np.int64(30)

In [39]:
print(np.ptp(b))

30


#### 10. Find which row has the highest sum.

In [40]:
print(np.sum(b,axis=1).argmax())

3


In [41]:
print(np.sum(b,axis=1))

[60 45 38 84]


### REAL PROBLEM-BASED ASSIGNMENTS

In [42]:
sales = np.array([
    [120, 150, 100],   # Day 1 (Product A, B, C)
    [90,  200, 130],   # Day 2
    [80,  170, 160],   # Day 3
    [200, 220, 180],   # Day 4
    [160, 140, 190]    # Day 5
])

#### 1. Find total sales across all days and products.

In [43]:
total_sales = sales.sum()
print(total_sales)

2290


#### 2. Find total sales for each day.

In [44]:
print("Total Sales per Day :")
i =1
for t_sales in sales.sum(axis=1):
    print(f"Day {i} : {t_sales}")
    i+=1

Total Sales per Day :
Day 1 : 370
Day 2 : 420
Day 3 : 410
Day 4 : 600
Day 5 : 490


#### 3. Find total sales of each product (A, B, C).

In [45]:
print("Total Sales per Product : ")
for product ,t_sales in zip(("A","B","C"),np.sum(sales,axis=0)):
    print(f" Product {product} : {t_sales}")

Total Sales per Product : 
 Product A : 650
 Product B : 880
 Product C : 760


#### 4. Find which day had highest total sales.

In [46]:
highest_total_sale = np.sum(sales,axis=1).max() 
higest_seling_day= np.sum(sales,axis=1).argmax()+1
print(f"Day {higest_seling_day} : {highest_total_sale}")

Day 4 : 600


#### 5. Find which product sold the most overall.

In [47]:
total_sale = np.sum(sales,axis =0).max()
high_sale_p = np.sum(sales,axis =0).argmax()
product = ["A","B","C"]
print("Highest Saling Poroduct :",product[high_sale_p])
print("Total saling :",total_sale)

Highest Saling Poroduct : B
Total saling : 880


#### 6. Find which day had minimum total sales.

In [48]:
less_sale_day = np.sum(sales,axis=1).argmin()
print("Less saling Day:",less_sale_day+1)
print("Total sale on that Day : ",np.sum(sales,axis=1).min())

Less saling Day: 1
Total sale on that Day :  370


### 7. Find mean sales for each day.

In [49]:
day =1
for avg in np.mean(sales,axis=1):
    print(f"Day {day} : {avg}")
    day+=1

Day 1 : 123.33333333333333
Day 2 : 140.0
Day 3 : 136.66666666666666
Day 4 : 200.0
Day 5 : 163.33333333333334


In [50]:
day =1
for avg in np.mean(sales,axis=1):
    print(f"Day {day} : {np.round(avg,2)}")
    day+=1

Day 1 : 123.33
Day 2 : 140.0
Day 3 : 136.67
Day 4 : 200.0
Day 5 : 163.33


In [51]:
day =1
for avg in np.mean(sales,axis=1):
    print(f"Day {day} : {avg:.2f}")
    day+=1

Day 1 : 123.33
Day 2 : 140.00
Day 3 : 136.67
Day 4 : 200.00
Day 5 : 163.33


#### 8. Find highest single sale value in dataset.

In [52]:
high_single_sale = np.max(sales)
print("Highest Saling Value :",high_single_sale)

Highest Saling Value : 220


#### 9, Find difference between highest and lowest sales.

In [53]:
range_value = np.max(sales)-np.min(sales)
print(range_value)

140


In [54]:
print(np.ptp(sales))

140


#### 10. Find standard deviation of each product to see which is most stable.

In [55]:
product =["A","B","C"]
print("standard deviation of each product ")
for p, st in zip(product,np.std(sales,axis=0)):
    print(f"Product {p} : {st:.2f}")

standard deviation of each product 
Product A : 44.72
Product B : 30.07
Product C : 33.11


# B. ROUNDING + REMAINDER

### BASIC QUESTIONS

In [56]:
arr = np.array([12.4, 5.7, 8.9, 10.2, 15.6, 3.1, 9.8, 7.5, 6.3, 11.9])

In [57]:
arr

array([12.4,  5.7,  8.9, 10.2, 15.6,  3.1,  9.8,  7.5,  6.3, 11.9])

#### 1. Round all values to nearest integer.

In [58]:
np.rint(arr)

array([12.,  6.,  9., 10., 16.,  3., 10.,  8.,  6., 12.])

In [59]:
np.round(arr)

array([12.,  6.,  9., 10., 16.,  3., 10.,  8.,  6., 12.])

In [60]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



#### 2. Apply floor function to all elements.

In [61]:
np.floor(arr)

array([12.,  5.,  8., 10., 15.,  3.,  9.,  7.,  6., 11.])

#### 3. Apply ceil function to all elements.

In [62]:
np.ceil(arr)

array([13.,  6.,  9., 11., 16.,  4., 10.,  8.,  7., 12.])

#### 4. Remove decimal part using trunc function.

In [63]:
np.trunc(arr)

array([12.,  5.,  8., 10., 15.,  3.,  9.,  7.,  6., 11.])

#### 5. Find remainder when each element is divided by 2.

In [64]:
np.mod(arr,2)

array([0.4, 1.7, 0.9, 0.2, 1.6, 1.1, 1.8, 1.5, 0.3, 1.9])

In [65]:
arr%2

array([0.4, 1.7, 0.9, 0.2, 1.6, 1.1, 1.8, 1.5, 0.3, 1.9])

In [66]:
np.remainder(arr,2)

array([0.4, 1.7, 0.9, 0.2, 1.6, 1.1, 1.8, 1.5, 0.3, 1.9])

#### 6. Find remainder when each element is divided by 3.

In [67]:
np.mod(arr,3)

array([0.4, 2.7, 2.9, 1.2, 0.6, 0.1, 0.8, 1.5, 0.3, 2.9])

#### 7.Convert all values into integer format (truncate).

In [68]:
np.trunc(arr).dtype

dtype('float64')

In [69]:
arr2 = arr.copy()
arr2

array([12.4,  5.7,  8.9, 10.2, 15.6,  3.1,  9.8,  7.5,  6.3, 11.9])

In [70]:
arr2.astype(np.int32)

array([12,  5,  8, 10, 15,  3,  9,  7,  6, 11], dtype=int32)

#### 8.Round all values to 1 decimal place.

In [71]:
np.round(arr,1)

array([12.4,  5.7,  8.9, 10.2, 15.6,  3.1,  9.8,  7.5,  6.3, 11.9])

#### 9. Find difference between ceil and floor values.

In [72]:
np.ceil(arr)-np.floor(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 10. Identify which values become even after rounding.

In [73]:
new_ar = np.where(np.round(arr)%2==0,arr,0)
[np.round(a )for a in new_ar if a !=0]

[np.float64(12.0),
 np.float64(6.0),
 np.float64(10.0),
 np.float64(16.0),
 np.float64(10.0),
 np.float64(8.0),
 np.float64(6.0),
 np.float64(12.0)]

### ADVANCED ARRAY

In [74]:
arr3 = np.array([
    [12.4, 5.7, 8.9],
    [10.2, 15.6, 3.1],
    [9.8, 7.5, 6.3],
    [11.9, 4.4, 13.7]
])

In [75]:
arr3

array([[12.4,  5.7,  8.9],
       [10.2, 15.6,  3.1],
       [ 9.8,  7.5,  6.3],
       [11.9,  4.4, 13.7]])

#### 1. Apply round() row-wise and column-wise interpretation.

In [76]:
np.round(arr3)

array([[12.,  6.,  9.],
       [10., 16.,  3.],
       [10.,  8.,  6.],
       [12.,  4., 14.]])

#### 2. Apply floor to each row and find row sums.

#### 3. Apply ceil and compare with original dataset totals.

In [77]:
original_total = np.sum(arr)
ceil_total = np.ceil(arr3).sum()
print("Origional total :",original_total)
print("Ceil Total : ",ceil_total)
print("Difference : ", original_total-ceil_total)

Origional total : 91.4
Ceil Total :  115.0
Difference :  -23.599999999999994


#### 4. Find remainder of each element when divided by 2 (even/odd check).

In [78]:
arr3[arr3%2==0]

array([], dtype=float64)

In [79]:
arr3[np.round(arr3%2)==0]

array([12.4, 10.2,  6.3,  4.4])

In [80]:
arr3[arr3%2==1]

array([], dtype=float64)

In [81]:
arr3[np.round(arr3%2)==1]

array([8.9, 3.1])

#### 5. Find remainder when divided by 5 and count zeros.

In [82]:
data = arr3%5
data

array([[2.4, 0.7, 3.9],
       [0.2, 0.6, 3.1],
       [4.8, 2.5, 1.3],
       [1.9, 4.4, 3.7]])

In [83]:
total_zeros = (data.astype(int) ==0).sum() 
print("Total zeros : ",total_zeros)

Total zeros :  3


### 6. Convert dataset into integers using trunc and reshape logic.

In [84]:
truncate_data = np.trunc(arr3) 
print("Truncate data :",truncate_data,sep="\n",end="\n\n")
int_data = truncate_data.astype(int)
print("Interger data :",int_data,sep="\n",end='\n\n')

reshaped_data = int_data.reshape(2,-1)
print("Reshaped Data :",reshaped_data,sep="\n")

Truncate data :
[[12.  5.  8.]
 [10. 15.  3.]
 [ 9.  7.  6.]
 [11.  4. 13.]]

Interger data :
[[12  5  8]
 [10 15  3]
 [ 9  7  6]
 [11  4 13]]

Reshaped Data :
[[12  5  8 10 15  3]
 [ 9  7  6 11  4 13]]


#### 7. Find difference between rounded and original values.

In [85]:
arr3 - np.round(arr3)

array([[ 0.4, -0.3, -0.1],
       [ 0.2, -0.4,  0.1],
       [-0.2, -0.5,  0.3],
       [-0.1,  0.4, -0.3]])

#### 8. Apply floor and then compute column-wise sum.

In [86]:
np.sum(np.floor(arr3),axis=0)

array([42., 31., 30.])

#### 9. Apply ceil and find maximum per row.

In [87]:
np.max(np.ceil(arr3),axis=1)

array([13., 16., 10., 14.])

#### 10. Check which column has highest rounding variation.

In [88]:
print("Column : ",np.argmax(np.var(arr3),axis=0)+1)

Column :  1


In [89]:
np.var(arr3,axis=0)

array([ 1.206875, 18.975   , 15.05    ])

### REAL-WORLD PROBLEMS

In [90]:
# Columns:
# Col 0 = Product Price
# Col 1 = Discount %
# Col 2 = Delivery Days
arr = np.array([
    [120.5, 10.2, 3.7],
    [99.9,  5.8,  4.3],  
    [150.6, 12.4, 2.9],
    [80.3,  8.6,  5.1],
    [200.7, 15.9, 1.8]
])

In [91]:
arr

array([[120.5,  10.2,   3.7],
       [ 99.9,   5.8,   4.3],
       [150.6,  12.4,   2.9],
       [ 80.3,   8.6,   5.1],
       [200.7,  15.9,   1.8]])

#### 1.Round Product Price  to nearest integer and calculate total revenue.

In [92]:
total_revenue = np.round(arr[:,[0]]).sum()

In [93]:
print("Total Revenue : ",total_revenue)

Total Revenue :  652.0


#### 2. Apply floor on Discount % (Col 0) and find effective discount total.

In [94]:
discount = np.floor(arr[:,1])
discount_total = (arr[:,0]*discount/100).sum()
print("Discount Amount :",discount_total)
net_sale = total_revenue - discount_total
print("Net Revenue :",net_sale)

Discount Amount : 71.646
Net Revenue : 580.354


#### 3. Apply ceil on Delivery Days  and find total delivery time.

In [95]:
arr

array([[120.5,  10.2,   3.7],
       [ 99.9,   5.8,   4.3],
       [150.6,  12.4,   2.9],
       [ 80.3,   8.6,   5.1],
       [200.7,  15.9,   1.8]])

In [96]:
delivary_days =np.ceil(arr[:,-1])
print("Total Days :",np.sum(delivary_days))

Total Days : 20.0


#### 4. Remove decimal values from Product Price using trunc.

In [97]:
np.trunc(arr[:,0])

array([120.,  99., 150.,  80., 200.])

#### 5. Find difference between original and rounded discount values 

In [98]:
discount_values = arr[:,0]*arr[:,1]/100
round_disc_v = np.round(discount_values)
print("Original Discount :",discount_values.sum())
print("Rounded discount values :",round_disc_v.sum())

Original Discount : 75.5767
Rounded discount values : 76.0


#### 6. Use mod operation on Delivery Days to check even/odd delivery days

In [99]:
days = np.round(arr[:,-1])
print("Even Days :",days[days%2==0])
print("Odd days :",days[days%2==1])

Even Days : [4. 4. 2.]
Odd days : [3. 5.]


In [100]:
days

array([4., 4., 3., 5., 2.])

#### 7. Round prices and calculate total revenue after rounding.

In [101]:
product_price = np.round(arr[:,0])
print("Rounded Total Revenue :",product_price.sum())

Rounded Total Revenue : 652.0


In [102]:
print("Total REveneue :",total_revenue)

Total REveneue : 652.0


#### 8. Find how much discount changes after floor operation.

In [103]:
discount = arr[:,1]
prodct_p = arr[:,0]
discount_price = (prodct_p*discount/100).sum()

floor_disc_price = (prodct_p*np.floor(discount)/100).sum()

percet_diff_dis = discount_price* (discount_price - floor_disc_price ) /100

print("Discount Price : ",discount_price)
print("Floor Discount Price :",floor_disc_price)
print("Discount change after floor operation :",np.round(percet_diff_dis))

Discount Price :  75.5767
Floor Discount Price : 71.646
Discount change after floor operation : 3.0


#### 9. Use remainder (mod 3) on delivery days to group shipments.

In [104]:
days = arr[:,2]
group = days%3
g1 = group[group <1]
g2 = group[(group > 1) & (group<2)]
g3 = group[group > 2]
print("Group 1",g1)
print("Group 2 ",g2)
print("Group 3 ",g3)

Group 1 [0.7]
Group 2  [1.3 1.8]
Group 3  [2.9 2.1]


#### 10. Convert entire dataset into integer format safely for reporting.

In [105]:
int_arr = np.floor(arr).astype(int)
int_arr

array([[120,  10,   3],
       [ 99,   5,   4],
       [150,  12,   2],
       [ 80,   8,   5],
       [200,  15,   1]])

# C. SCIENTIFIC FUNCTIONS

In [106]:
# Column meaning:
# Col 0 = Raw Value (Data Feature)
# Col 1 = Growth Factor
# Col 2 = Noise / Variation

arr_data = np.array([
    [1.0, 2.0, 0.1],
    [2.0, 3.0, 0.2],
    [3.0, 4.0, 0.3],
    [4.0, 5.0, 0.4],
    [5.0, 6.0, 0.5]
])

In [107]:
arr_data

array([[1. , 2. , 0.1],
       [2. , 3. , 0.2],
       [3. , 4. , 0.3],
       [4. , 5. , 0.4],
       [5. , 6. , 0.5]])

### BASIC QUESTIONS

#### 1. Apply sqrt() on all elements.

In [108]:
np.sqrt(arr_data)

array([[1.        , 1.41421356, 0.31622777],
       [1.41421356, 1.73205081, 0.4472136 ],
       [1.73205081, 2.        , 0.54772256],
       [2.        , 2.23606798, 0.63245553],
       [2.23606798, 2.44948974, 0.70710678]])

#### 2.Apply exp() on Col 0 only.

In [109]:
np.exp(arr_data[:,0])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

#### 3. Apply log() on Col 1 (handle safely).

In [110]:
np.log(arr_data[:,0])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### 4. Raise Col 0 to power 2.

In [111]:
np.power(arr_data[:,0],2)

array([ 1.,  4.,  9., 16., 25.])

#### 5. Raise Col 2 to power 3.

In [112]:
np.power(arr_data[:,1],2)

array([ 4.,  9., 16., 25., 36.])

#### 6. Apply log10 on full dataset.

In [113]:
np.log10(arr_data)

array([[ 0.        ,  0.30103   , -1.        ],
       [ 0.30103   ,  0.47712125, -0.69897   ],
       [ 0.47712125,  0.60205999, -0.52287875],
       [ 0.60205999,  0.69897   , -0.39794001],
       [ 0.69897   ,  0.77815125, -0.30103   ]])

#### 7. Compare exp(x) vs original values.

In [114]:
arr_data - np.exp(arr_data)

array([[  -1.71828183,   -5.3890561 ,   -1.00517092],
       [  -5.3890561 ,  -17.08553692,   -1.02140276],
       [ -17.08553692,  -50.59815003,   -1.04985881],
       [ -50.59815003, -143.4131591 ,   -1.0918247 ],
       [-143.4131591 , -397.42879349,   -1.14872127]])

#### 8. Compute square root and store result.

In [115]:
result = np.sqrt(arr_data)
result

array([[1.        , 1.41421356, 0.31622777],
       [1.41421356, 1.73205081, 0.4472136 ],
       [1.73205081, 2.        , 0.54772256],
       [2.        , 2.23606798, 0.63245553],
       [2.23606798, 2.44948974, 0.70710678]])

#### 9. Apply power transformation (x³) on dataset.

In [116]:
np.power(arr_data,3)

array([[1.00e+00, 8.00e+00, 1.00e-03],
       [8.00e+00, 2.70e+01, 8.00e-03],
       [2.70e+01, 6.40e+01, 2.70e-02],
       [6.40e+01, 1.25e+02, 6.40e-02],
       [1.25e+02, 2.16e+02, 1.25e-01]])

#### 10.Find exponential growth of Col 1.

In [117]:
np.exp(arr_data[:,0])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

### ADVANCED ARRAY

In [118]:
# Column meaning:
# Col 0 = Population Growth
# Col 1 = Time Factor
# Col 2 = Decay Rate

pp_array = np.array([
    [1.5, 2.0, 0.1],
    [2.5, 3.0, 0.2],
    [3.5, 4.0, 0.3],
    [4.5, 5.0, 0.4],
    [5.5, 6.0, 0.5]
])

In [119]:
pp_array

array([[1.5, 2. , 0.1],
       [2.5, 3. , 0.2],
       [3.5, 4. , 0.3],
       [4.5, 5. , 0.4],
       [5.5, 6. , 0.5]])

#### 1. Apply exponential growth on Col 0.

In [120]:
np.exp(pp_array[:,0])

array([  4.48168907,  12.18249396,  33.11545196,  90.0171313 ,
       244.69193226])

#### 2. Apply log transformation on Col 1.

In [121]:
np.log(pp_array[:,1])

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

#### 3. Compute decay using exp(-x) on Col 2.

In [122]:
np.exp(-pp_array[:,1])

array([0.13533528, 0.04978707, 0.01831564, 0.00673795, 0.00247875])

#### 4. Compare log(x) vs sqrt(x) on same column.

In [123]:
np.log(pp_array) == np.sqrt(pp_array)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

#### 5. Apply power (x²) on all columns.

In [124]:
np.power(pp_array[:,:],2)

array([[2.250e+00, 4.000e+00, 1.000e-02],
       [6.250e+00, 9.000e+00, 4.000e-02],
       [1.225e+01, 1.600e+01, 9.000e-02],
       [2.025e+01, 2.500e+01, 1.600e-01],
       [3.025e+01, 3.600e+01, 2.500e-01]])

#### 6. Normalize dataset using log transformation.

In [125]:
np.log(pp_array)

array([[ 0.40546511,  0.69314718, -2.30258509],
       [ 0.91629073,  1.09861229, -1.60943791],
       [ 1.25276297,  1.38629436, -1.2039728 ],
       [ 1.5040774 ,  1.60943791, -0.91629073],
       [ 1.70474809,  1.79175947, -0.69314718]])

#### 7. Compute growth model using exp(time factor)

In [126]:
np.exp(pp_array[:,1])

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])

#### 8. Apply combined function: log + sqrt.

In [127]:
np.log(pp_array)+np.sqrt(pp_array)

array([[ 1.63020998,  2.10736074, -1.98635733],
       [ 2.49742956,  2.8306631 , -1.16222432],
       [ 3.12359166,  3.38629436, -0.65625025],
       [ 3.62539774,  3.84550589, -0.2838352 ],
       [ 4.04995597,  4.24124921,  0.0139596 ]])

### REAL-WORLD PROBLEMS

In [128]:
# Column meaning:
# Col 0 = User Activity Score
# Col 1 = Engagement Growth Rate
# Col 2 = Drop-off Rate

DATA = np.array([
    [10.0, 1.2, 0.1],
    [20.0, 1.5, 0.2],
    [30.0, 1.8, 0.3],
    [40.0, 2.0, 0.4],
    [50.0, 2.5, 0.5]
])

In [129]:
DATA

array([[10. ,  1.2,  0.1],
       [20. ,  1.5,  0.2],
       [30. ,  1.8,  0.3],
       [40. ,  2. ,  0.4],
       [50. ,  2.5,  0.5]])

#### 1.User Growth Model: Apply exponential growth on activity score.

In [130]:
grow_model = np.exp(DATA[:,0])
grow_model

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

#### 2. Engagement Analysis: Apply log transformation on growth rate.

In [131]:
log_transformation = np.log(DATA[:,1])
np.round(log_transformation,3)

array([0.182, 0.405, 0.588, 0.693, 0.916])

#### 3. Drop-off Prediction: Use exponential decay on drop-off rate.

In [132]:
activity = DATA[:,0]
drop_rate = DATA[:,2]
remainning_users = activity * np.exp(-drop_rate)
print(remainning_users)

[ 9.04837418 16.37461506 22.22454662 26.81280184 30.32653299]


#### 4 .Feature Scaling: Convert all columns using log normalization.

In [133]:
np.log(DATA)

array([[ 2.30258509,  0.18232156, -2.30258509],
       [ 2.99573227,  0.40546511, -1.60943791],
       [ 3.40119738,  0.58778666, -1.2039728 ],
       [ 3.68887945,  0.69314718, -0.91629073],
       [ 3.91202301,  0.91629073, -0.69314718]])

#### 5. Viral Growth Simulation: Apply exp on engagement rate.

In [134]:
grow = np.exp(DATA[:,1])
grow

array([ 3.32011692,  4.48168907,  6.04964746,  7.3890561 , 12.18249396])

#### 6.Data Compression: Use log to compress activity scores.

In [135]:
compresed_active_score = np.log(DATA[:,0])
compresed_active_score

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

#### 7. Performance Boost Analysis: Compare sqrt vs log effects.

In [136]:
sqrt = np.sqrt(DATA)
logdata = np.log(DATA)
sqrt == logdata

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

#### 8. AI Feature Engineering: Apply power transformation (x²).

In [137]:
DATA**2

array([[1.00e+02, 1.44e+00, 1.00e-02],
       [4.00e+02, 2.25e+00, 4.00e-02],
       [9.00e+02, 3.24e+00, 9.00e-02],
       [1.60e+03, 4.00e+00, 1.60e-01],
       [2.50e+03, 6.25e+00, 2.50e-01]])

#### 9. Trend Detection: Find which column grows fastest using exp.

In [138]:
grow_data = np.exp(DATA)
grow_col = np.argmax(np.mean(DATA,axis=0))
print("Column :",grow_col+1, ":",grow_data[grow_col])

Column : 1 : [2.20264658e+04 3.32011692e+00 1.10517092e+00]
