# NumPy Iteration Functions – Simple Assignments 

## 

In [1]:
import numpy as np

### FUNCTION 1: np.nditer()
Efficient multi-dimensional iterator.




In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Q1. Iterate through all elements of matrix using np.nditer() and print each element.

In [3]:
for a in np.nditer(matrix):
    print(a)

1
2
3
4
5
6
7
8
9


#### Q2. Iterate through matrix row by row .

In [4]:
for a in np.nditer(matrix,order='c'):
    print(a)

1
2
3
4
5
6
7
8
9


#### Q3. Iterate through matrix column by column.

In [5]:
for a in np.nditer(matrix,order='f'):
    print(a)

1
4
7
2
5
8
3
6
9


#### Q4. Iterate and multiply each element by 2, store in new array.


In [6]:
new_array = np.empty_like(matrix)
for a in np.nditer(matrix):
    new_array[np.argwhere(matrix==a)] = a*2

In [7]:
new_array

array([[14, 14, 14],
       [16, 16, 16],
       [18, 18, 18]])

#### Q5. Iterate through matrix and count how many elements are greater than 5.

In [8]:
count = 0
for a in np.nditer(matrix):
    if a > 5 :
        count+=1
print("Total Elements : ",count)

Total Elements :  4


In [10]:
for row in np.nditer(matrix,flags = ['external_loop']):
    print(row)

[1 2 3 4 5 6 7 8 9]


### FUNCTION 2: np.ndenumerate()
Iterator yielding index and value.

In [20]:
arr_2d = np.array([[10, 25, 30], [45, 50, 60]])
print("Array:\n", arr_2d)

Array:
 [[10 25 30]
 [45 50 60]]


#### Q6. Iterate using np.ndenumerate() and print index and value for each element.


In [21]:
for index , value  in np.ndenumerate(arr_2d):
    print(f"Index :{index} -- Value :{value}")

Index :(0, 0) -- Value :10
Index :(0, 1) -- Value :25
Index :(0, 2) -- Value :30
Index :(1, 0) -- Value :45
Index :(1, 1) -- Value :50
Index :(1, 2) -- Value :60


#### Q7. Find the index of element with value 50 using np.ndenumerate().

In [22]:
for index, value in np.ndenumerate(arr_2d):
    if value == 50:
        print("Index of value  50:", index)

Index of value  50: (1, 1)


#### Q8. Replace all even numbers with 0 using np.ndenumerate().

In [23]:
arr_2d_cp = arr_2d.copy()
for index, value in np.ndenumerate(arr_2d_cp):
    if value%2 ==0:
        arr_2d_cp[index] = 0
arr_2d_cp

array([[ 0, 25,  0],
       [45,  0,  0]])

#### Q9. Create a dictionary mapping index to value using np.ndenumerate().

In [31]:
result = {}
for index, value in np.ndenumerate(arr_2d):
    result[index] = value
print(result)

{(0, 0): np.int64(10), (0, 1): np.int64(25), (0, 2): np.int64(30), (1, 0): np.int64(45), (1, 1): np.int64(50), (1, 2): np.int64(60)}


In [35]:
result = {}
for index, value in np.ndenumerate(arr_2d):
    result[index] = int(value)

print(result)

{(0, 0): 10, (0, 1): 25, (0, 2): 30, (1, 0): 45, (1, 1): 50, (1, 2): 60}


#### Q10. Find sum of values at odd indices using np.ndenumerate().

In [39]:
sum_v = 0
for index , val in np.ndenumerate(arr_2d):
    if (index[0]%2!=0 & index[1] % 2 != 0):  
        sum_v+= val
print("Sum of values at odd indices:", sum_v) #wrong

Sum of values at odd indices: 0


In [45]:
sum_v = 0
for index , val in np.ndenumerate(arr_2d):
    if (index[0]+ index[1]) % 2 != 0:  
        sum_v+= val
print("Sum of values at odd indices:", sum_v) #wrong

Sum of values at odd indices: 130


In [46]:
arr_2d

array([[10, 25, 30],
       [45, 50, 60]])

In [47]:
sum_v = 0
for index , val in np.ndenumerate(arr_2d):
    if (index[0] % 2 != 0) or ((index[0] + index[1]) % 2 != 0):
        sum_v+= val
print("Sum of values at odd indices:", sum_v)

Sum of values at odd indices: 180


### FUNCTION 3: np.ndindex()
Iterator over multi-dimensional indices.

In [48]:
shape_3d = (3, 4, 2)  # 3 rows, 4 cols, 2 depth
arr_3d = np.random.randint(1, 100, size=shape_3d)
print("3D Array shape:", arr_3d.shape)
print("First slice (depth 0):\n", arr_3d[:, :, 0])

3D Array shape: (3, 4, 2)
First slice (depth 0):
 [[ 5 92 53 47]
 [ 2  6 60 66]
 [38 54 43 64]]


#### Q11. Iterate over all indices of a 3x4 array using np.ndindex().

In [49]:
for index in np.ndindex((3,4)):
    print(index)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(2, 0)
(2, 1)
(2, 2)
(2, 3)


#### Q12. Iterate over all indices of a 1x4 array using np.ndindex().

In [50]:
for index in np.ndindex((1,4)):
    print(index)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


#### Q13. Find all indices where value > 80 using np.ndindex().

In [51]:
for index in np.ndindex(arr_3d.shape):
    if arr_3d[index] > 80:
        print(index)

(0, 1, 0)
(1, 0, 1)
(1, 2, 1)


#### Q14. Set all elements on diagonal (i==j) to 0 using np.ndindex().

In [53]:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
for index in np.ndindex(arr_2d.shape):
    if index[0] == index[1]:   
        arr_2d[index] = 0

print(arr_2d)

[[ 0 20 30]
 [40  0 60]
 [70 80  0]]


# 

### FUNCTION 4: np.flatiter()
Flat iterator over array (1D view).

In [55]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Q15. Create a flat iterator using .flat and print all elements.

In [56]:
for a in np.flatiter(arr):
    print(a)

TypeError: cannot create 'numpy.flatiter' instances

In [57]:
for a in arr.flat:
    print(a)

1
2
3
4
5
6
7
8
9
10
11
12


#### Q16. Iterate through flat iterator and sum all elements.

In [58]:
sum_val =0
for a in arr.flat:
    sum_val += a
print(sum_val)

78


#### Q17. Find maximum value using flat iterator.

In [59]:
max_v =-1
for a in arr.flat:
    if max_v < a:
        max_v =a
print(max_v)

12


#### Q18. Modify all elements using flat iterator (add 10 to each).

In [63]:
for i in range(arr.size):
    arr.flat[i] += 10 
print(arr)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


#### Q19. Use flat iterator to find index of value 7 in flattened view.

In [64]:
for i, val in enumerate(arr.flat):
    if val == 7:
        print("Flat index of 7:", i)

In [65]:
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [66]:
for i, val in enumerate(arr.flat):
    if val == 17:
        print("Flat index of 17:", i)

Flat index of 17: 6
