# Basic Linear Algebra

## Set 1

In [2]:
import numpy as np

#### 1. Create a vector [1,2,3] and print it.

In [3]:
vect = np.array([1,2,3])
vect

array([1, 2, 3])

#### 2. Create a 2×2 matrix and display its shape.

In [4]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [5]:
matrix.shape

(2, 2)

#### 3. Transpose of a 2x2 matrix

In [6]:
matrix.T

array([[1, 3],
       [2, 4]])

#### 4. Dot product of [2,3] and [4,5]

In [7]:
v1 = np.array([2,3])
v2 = np.array([4,5])

In [8]:
print(np.dot(v1,v2))

23


#### 5. Perform matrix multiplication of two 2×2 matrices.

In [11]:
np.random.seed(21)
m1 = np.random.randint(1,10,(2,2))
m2 = np.random.randint(2,10,(2,2))
print(m1)

[[9 5]
 [1 1]]


In [12]:
print(m2)

[[2 5]
 [6 4]]


In [13]:
matrix_multi = m1 @m2

In [14]:
matrix_multi

array([[48, 65],
       [ 8,  9]], dtype=int32)

In [15]:
np.matmul(m1,m2)

array([[48, 65],
       [ 8,  9]], dtype=int32)

#### 6. Determinant of a 2x2 matrix


In [16]:
m1

array([[9, 5],
       [1, 1]], dtype=int32)

In [19]:
print(np.round(np.linalg.det(m1)))

4.0


#### 7. Find inverse of a 2×2 matrix.

In [20]:
np.linalg.inv(m1)

array([[ 0.25, -1.25],
       [-0.25,  2.25]])

#### 8. Compute rank of a 2×2 matrix.

In [21]:
np.linalg.matrix_rank(m1)

np.int64(2)

# 

#### Set 2

#### 1. Create a 3×3 matrix and find its transpose.

In [23]:
np.random.seed(42)
ma1 = np.random.randint(1,20,(3,3))

In [24]:
ma1.shape

(3, 3)

#### 2. Compute dot product of [1,2,3] and [3,2,1].

In [25]:
va1 = np.array([1,2,3])
va2 = np.array([3,2,1])

In [27]:
np.dot(va1,va2)

np.int64(10)

#### 3. Multiply a matrix with its transpose.

In [29]:
ma1

array([[ 7, 15, 11],
       [ 8,  7, 19],
       [11, 11,  4]], dtype=int32)

In [30]:
print(np.multiply(ma1,ma1.T))

[[ 49 120 121]
 [120  49 209]
 [121 209  16]]


#### 4. Find determinant of a 3×3 matrix.

In [32]:
print(np.round(np.linalg.det(ma1)))

1509.0


#### 5. Check if matrix is invertible using determinant.

In [35]:
if np.linalg.det(ma1) > 0:
    print(np.linalg.inv(ma1))
else:
    print("INVERSE NOT POSSIBLE")

[[-0.11994698  0.04042412  0.13783963]
 [ 0.11729622 -0.06163022 -0.02982107]
 [ 0.0072896   0.05831677 -0.04705103]]


#### 6. Find inverse of a valid 2×2 matrix.

In [36]:
m1

array([[9, 5],
       [1, 1]], dtype=int32)

In [37]:
np.linalg.inv(m1)

array([[ 0.25, -1.25],
       [-0.25,  2.25]])

#### 7. Compute rank of a 3×3 matrix.

In [38]:
np.linalg.matrix_rank(ma1)

np.int64(3)

#### 8. Compute eigenvalues of a 2×2 matrix

In [39]:
values, vectors = np.linalg.eig(m1)
print("Values :",values)
print("Vector :",vectors)

Values : [9.58257569 0.41742431]
Vector : [[ 0.99328045 -0.5033825 ]
 [ 0.11573221  0.86406369]]


# 

# Set 3

#### 1. Create two matrices and perform matrix matmultiplication

In [40]:
np.random.seed(42)
mtx1 = np.random.randint(1,25,(3,3))
mtx2 = np.random.randint(1,30,(3,3))
print("-----------Matrix 1 -------------")
print(mtx1)
print("-----------Matrix 2 -------------")
print(mtx2)

-----------Matrix 1 -------------
[[ 7 20 15]
 [11  8 21]
 [ 7 19 23]]
-----------Matrix 2 -------------
[[11 11 24]
 [21  4  8]
 [24  3 22]]


In [41]:
np.matmul(mtx1,mtx2)

array([[ 857,  202,  658],
       [ 793,  216,  790],
       [1028,  222,  826]], dtype=int32)

In [42]:
mtx1@mtx2

array([[ 857,  202,  658],
       [ 793,  216,  790],
       [1028,  222,  826]], dtype=int32)

#### 2. Compute dot product of first row of first matrix  with first column of secound matrix

In [43]:
np.dot(mtx1[0],mtx2[:,0])

np.int32(857)

#### 3. Find transpose and then compute A⋅A.T

In [44]:
A = mtx1

In [45]:
A.T

array([[ 7, 11,  7],
       [20,  8, 19],
       [15, 21, 23]], dtype=int32)

In [46]:
np.dot(A,A.T)

array([[674, 552, 774],
       [552, 626, 712],
       [774, 712, 939]], dtype=int32)

#### 4. Perform matrix multiplication and handle incompatible shapes using try-except.

In [47]:
m1

array([[9, 5],
       [1, 1]], dtype=int32)

In [48]:
mtx1

array([[ 7, 20, 15],
       [11,  8, 21],
       [ 7, 19, 23]], dtype=int32)

In [50]:
try:
    result = m1 @ mtx1
    print("Result:", result)
except ValueError as e:
    print("Error: Matrix multiplication not possible due to shape mismatch")
    print(e)

Error: Matrix multiplication not possible due to shape mismatch
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


#### 5. Create a 2×2 matrix and check whether it is invertible

In [51]:
m1

array([[9, 5],
       [1, 1]], dtype=int32)

In [53]:
if np.linalg.det(m1) != 0:
    print("Inverse:\n", np.linalg.inv(m1))
else:
    print("Matrix is not invertible")

Inverse:
 [[ 0.25 -1.25]
 [-0.25  2.25]]
