# Numpy Arrray Operation

## 1. Arithemetic operation

In [1]:
import numpy as np

In [2]:
a1 = np.array(range(10))
a2 = np.array(range(10,20))
print("A1 : ")
print(a1)
print("\n B : ")
print(a2)
print("A+B : ")
print(a1+a2)
print("\nA-B : ")
print(a1-a2)
print("\nA*B : ")
print(a1*a2)
print("\nA/B : ")
print(a1/a2)
print("A%B : ")
print(a1%a2)

A1 : 
[0 1 2 3 4 5 6 7 8 9]

 B : 
[10 11 12 13 14 15 16 17 18 19]
A+B : 
[10 12 14 16 18 20 22 24 26 28]

A-B : 
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]

A*B : 
[  0  11  24  39  56  75  96 119 144 171]

A/B : 
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
A%B : 
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a1//a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
print(a1**a2)

[                  0                   1                4096
             1594323           268435456         30517578125
       2821109907456     232630513987207   18014398509481984
 1350851717672992089]


In [5]:
aa1 = np.full(5,"Hi")
aa2 = np.full(5,"Hello")
print(aa1)
print(aa2)

['Hi' 'Hi' 'Hi' 'Hi' 'Hi']
['Hello' 'Hello' 'Hello' 'Hello' 'Hello']


In [6]:
aa1+aa2

array(['HiHello', 'HiHello', 'HiHello', 'HiHello', 'HiHello'], dtype='<U7')

In [7]:
a= aa1+aa2

In [8]:
print(aa1)
aa1 += aa2
print(aa1)

['Hi' 'Hi' 'Hi' 'Hi' 'Hi']
['Hi' 'Hi' 'Hi' 'Hi' 'Hi']


In [9]:
aa1

array(['Hi', 'Hi', 'Hi', 'Hi', 'Hi'], dtype='<U2')

In [10]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
a1+=a2

In [13]:
a1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
aa2+=aa1

In [15]:
aa2

array(['Hello', 'Hello', 'Hello', 'Hello', 'Hello'], dtype='<U5')

In [16]:
aa1+aa2

array(['HiHello', 'HiHello', 'HiHello', 'HiHello', 'HiHello'], dtype='<U7')

In [17]:
aa1+++aa2

UFuncTypeError: ufunc 'positive' did not contain a loop with signature matching types <class 'numpy.dtypes.StrDType'> -> None

###### That means you're applying the positive unary operator (+) twice on aa2 before adding it to aa1.

###### But if aa2 is a NumPy array of strings, then doing +aa2 tries to apply the np.positive() ufunc, which only works on numeric types, not strings.

In [141]:
aa1-aa2

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U2'), dtype('<U5')) -> None

###### Aap - (minus operator) use kar rahe hain string arrays ke beech, aur NumPy ko ye samajh nahi aata string me minus ka kya matlab hota hai.

In [19]:
aa1*aa2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U2'), dtype('<U5')) -> None

## 2.Scalar operation

In [20]:
a1


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
a1+10

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [22]:
print(a1)
print(a1-10)

[10 12 14 16 18 20 22 24 26 28]
[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
print(a1)
print(a1/2)

[10 12 14 16 18 20 22 24 26 28]
[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [23]:
print(a1)
print(a1//2)

[10 12 14 16 18 20 22 24 26 28]
[ 5  6  7  8  9 10 11 12 13 14]


In [25]:
print(a1)
print(a1**2)

[10 12 14 16 18 20 22 24 26 28]
[100 144 196 256 324 400 484 576 676 784]


In [26]:
print(a1)
print(a1*2)
print(a1*2-1)
print(a1*(2-1))

[10 12 14 16 18 20 22 24 26 28]
[20 24 28 32 36 40 44 48 52 56]
[19 23 27 31 35 39 43 47 51 55]
[10 12 14 16 18 20 22 24 26 28]


In [27]:
print(a1)
print(a1+2)
print(a1++2)
print(a1+++++2)

[10 12 14 16 18 20 22 24 26 28]
[12 14 16 18 20 22 24 26 28 30]
[12 14 16 18 20 22 24 26 28 30]
[12 14 16 18 20 22 24 26 28 30]


In [28]:
print(a1)
print(a1++++-2)
print(a1++++--2)
print(a1++++---2)
print(a1++++----2)

[10 12 14 16 18 20 22 24 26 28]
[ 8 10 12 14 16 18 20 22 24 26]
[12 14 16 18 20 22 24 26 28 30]
[ 8 10 12 14 16 18 20 22 24 26]
[12 14 16 18 20 22 24 26 28 30]


In [29]:
print(a1***2)

SyntaxError: invalid syntax (751200266.py, line 1)

###### Yeh 3 baar * lag gaya hai, jo invalid syntax hai. Python me do hi * allowed hote hain saath me: Operator

In [30]:
print(a1///2)

SyntaxError: invalid syntax (2914035601.py, line 1)

In [31]:
print(a1)
print(a1%2)

[10 12 14 16 18 20 22 24 26 28]
[0 0 0 0 0 0 0 0 0 0]


In [32]:
print(a1)
print(2+a1)

[10 12 14 16 18 20 22 24 26 28]
[12 14 16 18 20 22 24 26 28 30]


## 3. Comparision opertaion
##### Element-wise comparisions return boolean array

In [33]:
print(a1)
print(a2)

[10 12 14 16 18 20 22 24 26 28]
[10 11 12 13 14 15 16 17 18 19]


In [34]:
print(a1==a2)

[ True False False False False False False False False False]


In [35]:
print(a1>a2)

[False  True  True  True  True  True  True  True  True  True]


In [36]:
print(a1<a2)

[False False False False False False False False False False]


In [38]:
print(a1>13)

[False False  True  True  True  True  True  True  True  True]


In [39]:
ab = np.random.randint(10,100,10)

In [40]:
ba = np.random.randint(10,100,10)

In [41]:
print(ab)
print(ba)

[94 11 42 47 71 16 43 17 92 25]
[91 13 85 88 17 16 64 51 22 90]


In [42]:
print(ab==ba)
print(ab>=ba)
print(ab<=ba)
print(ab!=ba)

[False False False False False  True False False False False]
[ True False False False  True  True False False  True False]
[False  True  True  True False  True  True  True False  True]
[ True  True  True  True  True False  True  True  True  True]


In [43]:
print(ab>38)

[ True False  True  True  True False  True False  True False]


In [44]:
print(ab[ab>38])
print(ab[ab<38])

[94 42 47 71 43 92]
[11 16 17 25]


In [45]:
print(ab[ab==21])
print(ab[ba==41])
print(ba[ba==41])

[]
[]
[]


In [46]:
print(ab[True])

[[94 11 42 47 71 16 43 17 92 25]]


In [47]:
a==ab

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

###### Aap do NumPy arrays a aur ab ke beech comparison (==) kar rahe ho, lekin unki shapes match nahi kar rahi, aur NumPy unhe broadcast bhi nahi kar sakta

In [48]:
x1=np.random.randint(10,100,(2,3))
x2=np.random.randint(10,100,(2,1))

In [49]:
print(x1)
print("\nSecond x2 : ")
print(x2)

[[98 40 10]
 [25 14 83]]

Second x2 : 
[[96]
 [71]]


In [50]:
x1+x2

array([[194, 136, 106],
       [ 96,  85, 154]], dtype=int32)

In [51]:
x1==x2

array([[False, False, False],
       [False, False, False]])

In [52]:
x2==x1

array([[False, False, False],
       [False, False, False]])

In [53]:
x1<x2

array([[False,  True,  True],
       [ True,  True, False]])

In [54]:
x1>x2

array([[ True, False, False],
       [False, False,  True]])

In [55]:
x1

array([[98, 40, 10],
       [25, 14, 83]], dtype=int32)

In [56]:
x2

array([[96],
       [71]], dtype=int32)

In [57]:
ab==x1

ValueError: operands could not be broadcast together with shapes (10,) (2,3) 

###### Aap do NumPy arrays a aur ab ke beech comparison (==) kar rahe ho, lekin unki shapes match nahi kar rahi, aur NumPy unhe broadcast bhi nahi kar sakta

In [58]:
aa1

array(['Hi', 'Hi', 'Hi', 'Hi', 'Hi'], dtype='<U2')

In [59]:
aa1.size

5

In [60]:
xa1=np.arange(5)
print(xa1)

[0 1 2 3 4]


###### We can compare str with  int , float 

In [61]:
aa1==xa1


array([False, False, False, False, False])

In [62]:
xa2 = np.arange(5).astype(str)


In [63]:
print(xa1)
print(xa2)
xa1==xa2

[0 1 2 3 4]
['0' '1' '2' '3' '4']


array([False, False, False, False, False])

In [64]:
xa1!=xa2

array([ True,  True,  True,  True,  True])

In [65]:
!xa1

'xa1' is not recognized as an internal or external command,
operable program or batch file.


#### ! ka matlab kya hota hai?
###### ! ka matlab kya hota hai? !kuch_bhi
###### "Yeh command computer ke andar system (jaise CMD ya Terminal) ko bhejo, Python ko nahi."
###### Example below ----- !dir


In [142]:
!dir

 Volume in drive C is Windows-SSD
 Volume Serial Number is 6A78-F2C4

 Directory of C:\Users\Omkar Yallurkar\Nnumpy

31-07-2025  11:09    <DIR>          .
29-07-2025  18:39    <DIR>          ..
30-07-2025  17:18    <DIR>          .ipynb_checkpoints
29-07-2025  18:38            61,796 Array creation .ipynb
30-07-2025  13:35            24,981 Array _Indexing_Slicing.ipynb
30-07-2025  12:13            19,794 Array_Atributers.ipynb
31-07-2025  11:09            50,479 Array_operation.ipynb
26-07-2025  12:12            42,121 Numpy_P.ipynb
29-07-2025  19:29            10,071 Untitled.ipynb
               6 File(s)        209,242 bytes
               3 Dir(s)  202,755,559,424 bytes free


In [66]:
xa3 = np.full(5,True)
print(xa3)

[ True  True  True  True  True]


In [67]:
!xa3

'xa3' is not recognized as an internal or external command,
operable program or batch file.


In [68]:
[xa3]

[array([ True,  True,  True,  True,  True])]

In [69]:
print([xa3])

[array([ True,  True,  True,  True,  True])]


In [70]:
print([print(xa3)])

[ True  True  True  True  True]
[None]


### compare with scalar

In [71]:
xa1

array([0, 1, 2, 3, 4])

In [72]:
xa1>2

array([False, False, False,  True,  True])

In [73]:
xa1<=2

array([ True,  True,  True, False, False])

In [74]:
xa1<2

array([ True,  True, False, False, False])

In [75]:
xa1!=2

array([ True,  True, False,  True,  True])

#### Use boolean result for filtering

In [76]:
bvalue = xa1>2
print(bvalue)
print(xa1[bvalue])

[False False False  True  True]
[3 4]


In [77]:
bvalue = xa1==3
print(xa1[bvalue])

[3]


### chained condition (&,|)

##### In below we wnat only greater than 10 and less than 50 

In [78]:
x1 = np.random.randint(1,100,50)
print(x1)

[74 93 68 56 75  3 36 42 17 47 96 64 39 52 10 92 33 79 23 34 71 55 91 14
 12 82 63 57 29  3 56 11 87 30 84 10 38 57  7 37 52 74 29 66 97 74 48 27
 61 75]


In [79]:
bv = (x1>10 )&( x1<50)
print(bv)
print(x1[bv])

[False False False False False False  True  True  True  True False False
  True False False False  True False  True  True False False False  True
  True False False False  True False False  True False  True False False
  True False False  True False False  True False False False  True  True
 False False]
[36 42 17 47 39 33 23 34 14 12 29 11 30 38 37 29 48 27]


In [80]:
x1.any(x1>10&x1<55)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Operator precedence (गलत तरीके से & use kiya gaya hai)
#####  Galat likha:  
######  1. x1.any(x1 > 10 & x1 < 55)   2. Yeh Python is tarah samajhta hai: x1 > (10 & x1) < 55   Jo completely galat hai — isiliye error deta hai.
##### Sahi Tarika: Use brackets properly, and call .any() on the result, not with arguments.
###### 1. (x1 > 10) & (x1 < 55)
###### 2. ((x1 > 10) & (x1 < 55)).any()
###### Galat : x1.any(condition)	   |||||||||               sahi : condition.any()  and also shahi : np.any(array) 



#### Aap NumPy array ko if statement ya comparison me directly use kar rahe ho, lekin usme 1 se zyada values hain, to Python ko samajh nahi aata ki True maana jaye ya False.
##### Example 1. wrong code 
###### import numpy as np
###### a = np.array([1, 2, 3])
###### if a: 
######  print("yes")
###### "Array me 3 values hain: [1, 2, 3] Kya sabhi True hain? Ya koi ek bhi True hona kaafi hai? Main kaise decide karoon?"
#
##### Example to Right code 
###### a = np.array([1, 2, 3])
###### if a.any(): 
######  print("yes")

In [145]:
bv = [(x1>10 )&( x1<50)]

##### In above bv is list not ndarray so no any array atributes will work on these 
##### Quenki yaha code inside [] k=hai so

In [146]:
print(bv.ndim)

AttributeError: 'list' object has no attribute 'ndim'

In [82]:
print(bv)

[array([False, False, False, False, False, False,  True,  True,  True,
        True, False, False,  True, False, False, False,  True, False,
        True,  True, False, False, False,  True,  True, False, False,
       False,  True, False, False,  True, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
       False,  True,  True, False, False])]


In [148]:
bv[0]

array([False, False, False, False, False, False,  True,  True,  True,
        True, False, False,  True, False, False, False,  True, False,
        True,  True, False, False, False,  True,  True, False, False,
       False,  True, False, False,  True, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
       False,  True,  True, False, False])

In [149]:

print(x1[bv[0]])


[36 42 17 47 39 33 23 34 14 12 29 11 30 38 37 29 48 27]


In [153]:
print(x1[bv])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

##### Provide value ie less than 10 or greateer than 50

In [85]:
print(x1[(x1<10)| (x1>50)])

[74 93 68 56 75  3 96 64 52 92 79 71 55 91 82 63 57  3 56 87 84 57  7 52
 74 66 97 74 61 75]


## 4. Universal Function

### A. Unary ufuncs
##### operate on one array 

In [2]:
u1 = np.random.randint(-50,50,10)


In [3]:
print(u1)

[ 19 -21   6 -30  -6 -17 -10   9 -49   7]


In [4]:
print(np.abs(u1))

[19 21  6 30  6 17 10  9 49  7]


In [6]:
print(np.sqrt(u1))

[4.35889894        nan 2.44948974        nan        nan        nan
        nan 3.                nan 2.64575131]


C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9648\9600159.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(u1))


######  Jab hum NumPy ke np.sqrt() function ka use karte hain kisi array ke upar, to ye function array ke har element ka square root nikalta hai. Lekin mathematical rule ke mutabiq, kisi bhi negative number ka square root real number system mein exist nahi karta. NumPy is situation ko handle karne ke liye nan (Not a Number) return karta hai. Iska matlab hota hai ki result mathematically invalid hai.
###### Agar aapke array (jaise u1) mein kuch negative values hain aur aap unka square root nikalne ki koshish karte hain, to NumPy aapko ek RuntimeWarning deta hai:

In [5]:
print(np.sqrt(u1).astype(int))

[                   4 -9223372036854775808                    2
 -9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808                    3 -9223372036854775808
                    2]


C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9648\2256663056.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(u1).astype(int))
C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9648\2256663056.py:1: RuntimeWarning: invalid value encountered in cast
  print(np.sqrt(u1).astype(int))


###### Jab aap NumPy mein np.sqrt(u1).astype(int) likhte ho, to aap har element ka square root nikalne ki koshish kar rahe ho aur usse integer mein convert kar rahe ho.

###### Lekin agar u1 array mein kuch negative numbers hote hain (jaise -1, -5), to unka square root real numbers mein possible nahi hota. NumPy in values ka square root NaN (Not a Number) return karta hai.

###### Jab aap astype(int) lagate ho, to NumPy NaN ko integer mein convert nahi kar paata. Is wajah se aapko warning milti hai:

##### Final Note :
###### Negative numbers ka sqrt real number mein valid nahi hota.
###### NaN ko int mein convert karna galti hai, warning deta hai.
###### Aapko pehle input ko clean karna chahiye, phir calculation karni chahiye.

In [105]:
print(np.sqrt(16))

4.0


In [7]:
print(np.sqrt(-16))

nan


C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9648\4225472685.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-16))


In [106]:
print(np.exp(2))

7.38905609893065


In [10]:
print(np.exp(-200000000000))

0.0


In [11]:
np.log(-10)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9648\2104861374.py:1: RuntimeWarning: invalid value encountered in log
  np.log(-10)


np.float64(nan)

In [17]:
np.power(1,2)
np.power(1,-2)

ValueError: Integers to negative integer powers are not allowed.

In [18]:
np.power(-2,3)

np.int64(-8)

In [107]:
print(np.exp(u1))

[3.93133430e+12 1.48413159e+02 9.49611942e+19 1.73927494e+18
 1.83156389e-02 1.52299797e-08 2.90488497e+13 1.06864746e+13
 6.73794700e-03 1.15482242e-17]


In [111]:
print(np.sin(400))
print(np.tan(400))
print(np.cos(400))
print(np.tan(u1))

-0.8509193596391765
1.6198844291169272
-0.525296338642536
[ 0.88714284 -3.38051501 -2.08661353  2.29138799 -1.15782128  1.13731371
 -0.44169557 -6.4053312   3.38051501 -3.61455441]


In [113]:
print(u1[[3,-2]])

[42 -5]


In [115]:
print(np.log(10))
print(np.log10(100))

2.302585092994046
2.0


In [121]:
print(np.ceil(2.01))
print(np.floor(2.99))
print(np.round(2.34))
print(np.round(2.54))
print(np.round(2.50))
print(np.round(2.5000001))

3.0
2.0
2.0
3.0
2.0
3.0


##### Unary fun on 2D and 3D array

In [124]:
u2 = np.random.randint(1,50,(2,3))
u3 = np.random.randint(1,50,(2,2,3))
print(u2)
print("array 3D : ")
print(u3)

[[37 25  6]
 [20 44 30]]
array 3D : 
[[[23 30 19]
  [46 13 14]]

 [[25 34 18]
  [48 48 28]]]


In [125]:
print(np.sqrt(u1,u2))

UFuncTypeError: Cannot cast ufunc 'sqrt' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [20]:
a = np.arange(5).astype(float)
b = np.arange(5).astype(float)
print(b)
print(np.sqrt(a,b))
print(b)

[0. 1. 2. 3. 4.]
[0.         1.         1.41421356 1.73205081 2.        ]
[0.         1.         1.41421356 1.73205081 2.        ]


In [128]:
print(np.sqrt(4.16))

2.039607805437114


In [130]:
print(np.sqrt(u1,4))

TypeError: return arrays must be of ArrayType