##  Shape Manipulation in NumPy

In [1]:
import numpy as np


##### 1. Create a 1D array of numbers from 1 to 12 and reshape it to (3, 4).

In [2]:
a1 = np.arange(1,12+1)
b1 = a1.reshape(3,4)
print(a1)
print("_"*20)
print(b1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
____________________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### 2. Reshape a 1D array of 16 elements into shape (4, 4).

In [3]:
a2 = np.arange(16)
print(a2)
b2 = np.reshape(a2,(4,4))
print("_"*20)
print(b2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
____________________
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


##### 3 . Convert a 2D array [[1, 2], [3, 4]] into a 1D array using ravel().

In [4]:
a3 = np.array( [[1, 2], [3, 4]] )
print(a3)
b3= a3.ravel()
print(b3)

[[1 2]
 [3 4]]
[1 2 3 4]


##### 4. Flatten a 3D array into 1D using flatten().

In [5]:
a4 = np.zeros((2,2,2))
print(a4)
print("_"*20)
print(a4.flatten())
print("_"*20)
print(a4)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
____________________
[0. 0. 0. 0. 0. 0. 0. 0.]
____________________
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


##### 5. Use reshape() to change a 3×2 array into a 2×3 array.

In [6]:
a5 = np.ones((3,2))
print(a5)
print("_"*20)
b5=a5.reshape(2,3)
print(b5)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
____________________
[[1. 1. 1.]
 [1. 1. 1.]]


##### 6. Use np.transpose() on a (2, 3) array and print the result.

In [7]:
a6 = np.ones((2,3))
print(a6)
print("_"*20)
np.transpose(a6)
print(a5)

[[1. 1. 1.]
 [1. 1. 1.]]
____________________
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##### 7 .Given array shape (2, 1, 3), remove the dimension with size 1 using squeeze().



In [8]:
a7 = np.full((2, 1, 3),2)
print(a7)
print("_"*20)
# b7 = np.squeeze(a7)
b7 = a7.squeeze()
print(b7)

[[[2 2 2]]

 [[2 2 2]]]
____________________
[[2 2 2]
 [2 2 2]]



##### 8 . Create a 2D array and add a new axis using expand_dims() at axis=0.

In [9]:
a8 = np.linspace(1,12,12).reshape(3,4)
print(a8)
print("_"*20)
b8 = np.expand_dims(a8,0)
print(b8)
print(b8.shape)

print("_"*20)
c8 = np.expand_dims(a8,1)
print(c8)
print(c8.shape)
print("_"*20)
d8 = np.expand_dims(a8,2)
# d8 = a8.expand_dims()  # AttributeError: 'numpy.ndarray' object has no attribute 'expand_dims'
print(d8)
print(d8.shape)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
____________________
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]
(1, 3, 4)
____________________
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]
(3, 1, 4)
____________________
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [10.]
  [11.]
  [12.]]]
(3, 4, 1)


##### 9.	Add an extra dimension to a (4,) array to make it (4,1).

In [10]:
a9 = np.arange(4)
print(a9.shape)
# np.expand_dims(a9)   # TypeError: expand_dims() missing 1 required positional argument: 'axis'
# np.expand_dims(a9,2)  # AxisError: axis 2 is out of bounds for array of dimension 2
print(np.expand_dims(a9,1).shape)

(4,)
(4, 1)


##### 10.	Given a = np.array([1, 2, 3]), reshape it to (3, 1).

In [11]:
a10 = np.array([1, 2, 3])
print(a10.shape)
print(a10.reshape(3,1).shape)

(3,)
(3, 1)


##### 11.	Change the shape of a (3, 2) array to (2, 3) and check .shape.

In [12]:
# a11 = np.random(3, 2) # TypeError: 'module' object is not callable
# a11 = np.random((3, 2))# TypeError: 'module' object is not callable
a11 = np.random.rand(3, 2)
print(a11.shape)
print(a11.reshape(2,3).shape)

(3, 2)
(2, 3)


##### 12.	Use .T to transpose a (3, 2) array and print the shape.

In [13]:
a12 = np.random.rand(3, 2)
print(a12.shape)
print(a12.T.shape)

(3, 2)
(2, 3)


##### 13.	Create a (2, 2) array, reshape it to (4, 1), then flatten it back to 1D.

In [14]:
a13 = np.random.rand(2, 2)
print(a13.shape)
b13 = np.reshape(a13,(4,1))
print(b13.shape)
c13 = b13.flatten()
print(c13)
# np.flatten(a13)  #AttributeError: module 'numpy' has no attribute 'flatten'


(2, 2)
(4, 1)
[0.4001084  0.73781556 0.13602989 0.88262423]


##### 14.	Use np.swapaxes() on a 3D array with shape (2, 3, 4) to swap axes 0 and 2.

In [15]:
a14 = np.random.rand(2, 3, 4)
print(np.swapaxes(a14,0,2).shape)
print(a14.swapaxes(0,2).shape)

(4, 3, 2)
(4, 3, 2)


##### 15.	Use resize() to change a 2×3 array to shape 3×3. What happens?

In [16]:
a15 = np.random.randint(1,6,(2, 3))
print(a15)
print("_"*20)
c15=a15.resize()
print(c15)
print("_"*20)
d15=a15.resize((3,3))
print(d15)
print("_"*20)
b15=np.resize(a15,(3,3))
print(b15)
# print()

[[5 3 5]
 [4 2 2]]
____________________
None
____________________
None
____________________
[[5 3 5]
 [4 2 2]
 [0 0 0]]


In [17]:
a= np.array([])
print(a)
b = np.resize(a,(2,3))
# c = np.resize(a) # TypeError: resize() missing 1 required positional argument: 'new_shape'
print(b)

[]
[[0. 0. 0.]
 [0. 0. 0.]]


##### 16.	Flatten a 4x4 matrix into a 1D array.

In [18]:
a16 = np.random.randint(1,16,(4,4))
c16 = a16.flatten()
# c16 = np.flatten(a16) # AttributeError: module 'numpy' has no attribute 'flatten'
d16 = np.ravel(a16)
print("Covertind 2D array to 1D using Faltten() and ravel()")
print("-"*30)
print("flatten : ",c16)
print("_"*20)
print("ravel : ", d16)
print("_"*20)
print("Now updating array A now see chances in faltten and ravel ")
print("-"*30)
a16[...,0]=999
print("flatten : ",c16)
print("_"*20)
print("ravel : ",d16)

Covertind 2D array to 1D using Faltten() and ravel()
------------------------------
flatten :  [13  6 13  5  9  6 10 13 14  7  7  4 13 13  8 10]
____________________
ravel :  [13  6 13  5  9  6 10 13 14  7  7  4 13 13  8 10]
____________________
Now updating array A now see chances in faltten and ravel 
------------------------------
flatten :  [13  6 13  5  9  6 10 13 14  7  7  4 13 13  8 10]
____________________
ravel :  [999   6  13   5 999   6  10  13 999   7   7   4 999  13   8  10]


##### 17.	Reshape a (3, 4) array to shape (6, 2) using reshape().

In [19]:
a17 = np.random.randint(1,12,(3,4))
print(a17.shape)
print(a17.reshape(6,2).shape)

(3, 4)
(6, 2)


##### 18.	Remove all singleton dimensions from array a = np.array([[[5]]]).

In [20]:
a18 = np.array([[[5]]])
print(a18.shape)
print(a18.squeeze().shape)
print(a18.squeeze(0).shape)
print(np.squeeze(a18).shape)

(1, 1, 1)
()
(1, 1)
()


##### 19.	Use expand_dims() twice to change a (5,) array to shape (1, 5, 1).

In [21]:
a19 = np.array([1,2,3,4,5])
print(a19.shape)
b19=np.expand_dims(a19,0)
print(np.expand_dims(b19,2).shape)
print(a19.shape)
print(np.expand_dims(a19,(0,2)).shape)

(5,)
(1, 5, 1)
(5,)
(1, 5, 1)


##### 20.	Create a 3D array with shape (2, 2, 2) and flatten it.

In [22]:
a20 = np.ones((2,2,2))
print(a20.flatten())

[1. 1. 1. 1. 1. 1. 1. 1.]


##### 21.	Use transpose() to reverse the axes of a (2, 3, 4) array → shape should become (4, 3, 2).

In [23]:
a21 = np.random.randint(1,22,(2, 3, 4))
print(a21.shape)
print(a21.T.shape)

(2, 3, 4)
(4, 3, 2)


##### 22.	Use reshape() to convert a (9,) array to (3, 3), then use T.

In [24]:
a22 =np.arange(9).reshape(3,3)
print(a22)
print("_"*20)
print(a22.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
____________________
[[0 3 6]
 [1 4 7]
 [2 5 8]]


##### 23.	Convert a (3, 2, 1) array to shape (3, 2) using squeeze().

In [25]:
a23 = np.ones((3, 2, 1))
print(a23.squeeze().shape)

(3, 2)


##### 24.	Start with a (4,) array, convert it to (1, 4, 1), then flatten it.

In [26]:
a24 = np.arange(4)
b24 = np.expand_dims(a24,(0,2))
print(b24.shape)
print(b24.flatten())

(1, 4, 1)
[0 1 2 3]


##### 25.	Create a (1, 1, 4) array and remove all dimensions with size 1 using squeeze().

In [27]:
a25 = np.ones((1, 1, 4) )
print(a25.squeeze())

[1. 1. 1. 1.]
