# NumPy Basic Statistics – Simple Assignments


In [1]:
import numpy as np

### FUNCTION 1: np.mean()
Average of array elements.

In [2]:
marks = np.array([85, 72, 90, 68, 77, 88, 95, 63, 79, 82])
print("Marks:", marks)

Marks: [85 72 90 68 77 88 95 63 79 82]


#### Q1. Calculate mean of all marks.

In [4]:
print(np.mean(marks))

79.9


#### Q2. Calculate mean of marks greater than 75.

In [7]:
print(np.mean(marks[marks>75]))

85.14285714285714


#### Q3. Calculate row-wise mean for a 2D array (create 3×4 random array).

In [8]:
np.random.seed(42)
array2d = np.random.randint(30,100,size=(3,4))
array2d

array([[81, 44, 90, 50],
       [53, 32, 51, 82],
       [31, 59, 67, 31]], dtype=int32)

In [10]:
print(np.mean(array2d,axis=1))

[66.25 54.5  47.  ]


#### Q4. Calculate column-wise mean for the same 2D array.

In [11]:
print(np.mean(array2d,axis=0))

[55.         45.         69.33333333 54.33333333]


#### Q5. Calculate mean along both axes simultaneously.

In [12]:
print(np.mean(array2d,axis=(0,1)))

55.916666666666664


In [13]:
print(np.mean(array2d,axis=(1,0)))

55.916666666666664


In [14]:
print(np.mean(array2d))

55.916666666666664


### FUNCTION 2: np.median()
Middle value of array.

In [16]:
salaries = np.array([32000, 45000, 28000, 52000, 38000, 61000, 41000, 35000, 49000, 55000])
print("Salaries:", salaries)

Salaries: [32000 45000 28000 52000 38000 61000 41000 35000 49000 55000]


#### Q6. Calculate median salary.

In [17]:
print(np.median(salaries))

43000.0


#### Q7. Compare mean vs median - which is higher?

In [20]:
mean_v = np.mean(salaries)
median_v = np.median(salaries)
higher = "mean is higher " if mean_v > median_v else "median is higher"
print("Mean : ",mean_v)
print("Median : ",median_v)
print(higher)

Mean :  43600.0
Median :  43000.0
mean is higher 


#### Q8. Calculate median of first 5 salaries.

In [21]:
print(np.median(salaries[:5]))

38000.0


#### Q9. Calculate median for each row of 4×5 random array.

In [22]:
np.random.seed(42)
array3 = np.random.randint(1,10,(4,5))
array3
    

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4],
       [8, 8, 3, 6, 5],
       [2, 8, 6, 2, 5]], dtype=int32)

In [23]:
print(np.median(array3,axis=1))

[7. 5. 6. 5.]


#### Q10. Find median of even numbers in array.

In [25]:
even_number = array3[array3%2==0]
even_number

array([4, 8, 8, 4, 8, 8, 6, 2, 8, 6, 2], dtype=int32)

In [26]:
print(np.median(even_number))

6.0


### FUNCTION 3: np.std() and np.var()
Standard deviation and variance.

In [27]:
temperatures = np.array([22, 24, 23, 28, 26, 24, 22, 25, 27, 23, 29, 24])
print("Temperatures:", temperatures)

Temperatures: [22 24 23 28 26 24 22 25 27 23 29 24]


#### Q11. Calculate standard deviation of temperatures.

In [28]:
print(np.std(temperatures))

2.203217344400381


#### 4Q12. Calculate variance of temperatures.

In [29]:
print(np.var(temperatures))

4.854166666666667


#### Q13. Which day has temperature farthest from mean?

In [31]:
mean_data = np.mean(temperatures)
diff_data = np.abs(mean_data-temperatures)
print("Day : ",np.argmax(diff_data)+1)

Day :  11


#### Q14. Calculate std for each column of 5×5 random array.

In [32]:
np.random.seed(42)
array4 = np.random.randint(1,50,(5,5))
array4

array([[39, 29, 15, 43,  8],
       [21, 39, 19, 23, 11],
       [11, 24, 36, 40, 24],
       [ 3, 22,  2, 24, 44],
       [30, 38,  2, 21, 33]], dtype=int32)

In [33]:
print(np.std(array4,axis=0))

[12.87478155  7.00285656 12.60793401  9.32523458 13.46105494]


#### Q15. Calculate std for even-indexed positions only.

In [34]:
print(np.std(temperatures[::2]))

2.6718699236468995


## FUNCTION 4: np.min() and np.max()
Minimum and maximum values.

In [35]:
scores = np.array([45, 67, 89, 34, 92, 78, 56, 88, 73, 95, 61, 84])
print("Scores:", scores)

Scores: [45 67 89 34 92 78 56 88 73 95 61 84]


#### Q16. Find minimum score.

In [37]:
print(np.min(scores))

34


#### Q17. Find maximum score.

In [38]:
print(np.max(scores))

95


#### Q18. Find range (max - min).

In [39]:
print(np.max(scores)-np.min(scores))

61


#### Q19. Find row-wise max for 3×4 array.

In [40]:
np.random.seed(42)
arr5 = np.random.randint(1,100,(3,4))
arr5

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]], dtype=int32)

In [41]:
print(np.max(arr5,axis=1))

[93 87 88]


#### Q20. Find column-wise min for same array.

In [42]:
print(np.min(arr5,axis=0))

[52 21 15 24]


### FUNCTION 5: np.ptp()
Peak-to-peak (max - min) range.

In [43]:
prices = np.array([120, 85, 200, 95, 175, 110, 65, 190, 150, 130])
print("Prices:", prices)

Prices: [120  85 200  95 175 110  65 190 150 130]


#### Q21. Calculate price range using np.ptp().

In [44]:
print(np.ptp(prices))

135


#### Q22. Compare np.ptp() with (max - min).

In [45]:
print(np.max(prices)-np.min(prices))

135


#### Q23. Calculate row-wise ptp for 4×4 array.

In [46]:
np.random.seed(42)
price_array = np.random.randint(10,100,(4,4))
price_array

array([[61, 24, 81, 70],
       [30, 92, 96, 84],
       [84, 97, 33, 12],
       [31, 62, 11, 97]], dtype=int32)

In [47]:
print(np.ptp(price_array,axis=1))

[57 66 85 86]


#### Q24. Calculate ptp for first half of array.

In [49]:
print(np.ptp(prices[:prices.size//2]))

115


#### Q25. Calculate ptp for values between 100 and 180.

In [55]:
data_values = prices[(prices>100) & (prices<180)]
data_values

array([120, 175, 110, 150, 130])

In [56]:
print(np.ptp(data_values))

65


### FUNCTION 6: np.percentile()
Value below which given percentage falls.

In [2]:
heights = np.array([165, 172, 168, 180, 158, 175, 182, 170, 166, 178, 173, 169])
print("Heights:", heights)

Heights: [165 172 168 180 158 175 182 170 166 178 173 169]


#### Q26. Find 25th percentile (Q1).

In [3]:
print(np.percentile(heights,25))

167.5


#### Q27. Find 50th percentile (median).

In [4]:
print(np.percentile(heights,50))

171.0


In [5]:
print(np.median(heights))

171.0


#### Q28. Find 75th percentile (Q3).

In [6]:
print(np.percentile(heights,75))

175.75


#### Q29. Find IQR (Q3 - Q1).

In [9]:
q1 = np.percentile(heights,25)
q3 = np.percentile(heights,75)
iqr = q3 - q1
print(iqr)

8.25


#### Q30. Find 90th percentile (top 10% height).

In [10]:
print(np.percentile(heights,90))

179.8


### FUNCTION 7: np.quantile()
Quantile (similar to percentile but 0-1 range)

In [11]:
ages = np.array([23, 25, 29, 31, 22, 28, 35, 27, 24, 30, 26, 33, 32, 28, 34])
print("Ages:", ages)

Ages: [23 25 29 31 22 28 35 27 24 30 26 33 32 28 34]


#### Q31. Find 0.25 quantile (same as 25th percentile).

In [12]:
print(np.quantile(ages,0.25))

25.5


In [13]:
print(np.percentile(ages,25))

25.5


#### Q32. Find 0.5 quantile (median).

In [15]:
print(np.quantile(ages,0.5))

28.0


In [16]:
print(np.median(ages))

28.0


#### Q33. Find 0.75 quantile.

In [19]:
print(np.quantile(ages,.75))

31.5


#### Q34. Find multiple quantiles at once [0.25, 0.5, 0.75].

In [20]:
print(np.quantile(ages,[0.25,0.5,0.75]))

[25.5 28.  31.5]


#### Q35. Find 0.1 and 0.9 quantiles for outliers detection.

In [21]:
print(np.quantile(ages,0.1))
print(np.quantile(ages,0.9))

23.4
33.6


### FUNCTION 8: np.corrcoef()
Correlation coefficient between variables.

In [22]:
# Hours studied vs exam scores
hours = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
scores = np.array([45, 52, 58, 65, 70, 78, 82, 88, 92, 95])
print("Hours:", hours)
print("Scores:", scores)

Hours: [ 1  2  3  4  5  6  7  8  9 10]
Scores: [45 52 58 65 70 78 82 88 92 95]


#### Q36. Calculate correlation between hours and scores.

In [23]:
np.corrcoef(hours,scores)

array([[1.        , 0.99542469],
       [0.99542469, 1.        ]])

#### Q37. Create 3 variables (4×3 array) and find correlation matrix.

In [24]:
np.random.seed(42)
a1 = np.random.randint(1,100,(4,3))
a2 = np.random.randint(20,100,(4,3))
a3 = np.random.randint(30,100,(4,3))

In [25]:
a1

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]], dtype=int32)

In [26]:
a2

array([[22, 41, 72],
       [21, 49, 57],
       [21, 83, 79],
       [40, 52, 95]], dtype=int32)

In [27]:
a3

array([[87, 51, 78],
       [88, 71, 89],
       [44, 91, 91],
       [76, 91, 80]], dtype=int32)

In [30]:
print(np.corrcoef(a1,a2))

[[ 1.          0.72512158  0.9759575   0.93595077 -0.5905071  -0.18258642
   0.08715933 -0.72332633]
 [ 0.72512158  1.          0.85778028  0.92116277 -0.98392882 -0.80944237
  -0.62279913 -0.99999661]
 [ 0.9759575   0.85778028  1.          0.99019894 -0.75221136 -0.39249353
  -0.13206764 -0.85643915]
 [ 0.93595077  0.92116277  0.99019894  1.         -0.83686661 -0.51710338
  -0.26921395 -0.92014644]
 [-0.5905071  -0.98392882 -0.75221136 -0.83686661  1.          0.90128465
   0.75249298  0.98439036]
 [-0.18258642 -0.80944237 -0.39249353 -0.51710338  0.90128465  1.
   0.96353406  0.81096837]
 [ 0.08715933 -0.62279913 -0.13206764 -0.26921395  0.75249298  0.96353406
   1.          0.62483391]
 [-0.72332633 -0.99999661 -0.85643915 -0.92014644  0.98439036  0.81096837
   0.62483391  1.        ]]


#### Q38. Calculate correlation for random data (should be near 0).

In [31]:
np.random.seed(10)
x = np.random.rand(10)
y = np.random.rand(10)
print(np.corrcoef(x,y))

[[ 1.         -0.63534904]
 [-0.63534904  1.        ]]


#### Q39. Calculate correlation for negative relationship (create inverse data).

In [32]:
a = np.arange(10)
b = a[::-1].copy()

In [33]:
np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

#### Q40. Correlation coefficient measures the relationship between two variables.

In [35]:
print(np.corrcoef(scores,hours))

[[1.         0.99542469]
 [0.99542469 1.        ]]


## REAL-WORLD SCENARIO 1: Student Performance

In [36]:
np.random.seed(42)
# 30 students, 5 subjects
students = np.random.randint(50, 100, size=(30, 5))
subjects = ["Math", "Science", "English", "History", "Art"]
print("Students shape:", students.shape)
print("First 3 students:\n", students[:3])


Students shape: (30, 5)
First 3 students:
 [[88 78 64 92 57]
 [70 88 68 72 60]
 [60 73 85 89 73]]


#### Q41. Calculate mean score for each student.

In [37]:
print(np.mean(students,axis=1))

[75.8 71.6 76.  68.  73.8 79.4 74.6 76.6 67.2 73.8 69.8 78.6 78.4 65.6
 75.4 77.8 70.2 79.  82.2 67.6 66.2 68.  79.8 67.6 79.  85.  73.  69.4
 71.2 70.4]


#### Q42. Calculate mean score for each subject.

In [39]:
sub_mean = np.mean(students,axis=0)
for s, m in zip(subjects,sub_mean):
    print(f"{s} : {m:.2f}")

Math : 70.27
Science : 75.80
English : 73.77
History : 78.37
Art : 70.30


#### Q43. Find student with highest average.

In [41]:
student_mean = np.mean(students,axis=1)
print("Student Index No : ",np.argmax(student_mean))
print("mean : ",np.max(student_mean))

Student Index No :  25
mean :  85.0


#### Q44. Find subject with lowest average.

In [42]:
sub_mean

array([70.26666667, 75.8       , 73.76666667, 78.36666667, 70.3       ])

In [44]:
low_sub_ind = np.argmin(sub_mean)
print("Subject : ",subjects[low_sub_ind])
print("Mean :  ",np.min(np.round(sub_mean,2)))

Subject :  Math
Mean :   70.27


#### Q45. Calculate standard deviation for each subject (which subject has most variation?).

In [47]:
std_dev = np.std(students,axis=0)
max_var_sub = subjects[np.argmax(std_dev)]
print("Standard Deviation : ",std_dev)
print("Max variation sub  : ",max_var_sub)

Standard Deviation :  [12.7643601  11.90630085 16.11558942 14.9387267  13.66052708]
Max variation sub  :  English


### 🔹 REAL-WORLD SCENARIO 2: Sales Data


In [58]:
# 12 months, 4 products
sales = np.array([
    [120, 145, 130, 155],  
    [85, 92, 88, 105],     
    [200, 210, 105, 130],  
    [45, 52, 48, 60],      
    [160, 175, 168, 190],  
    [95, 88, 102, 110],    
    [180, 195, 188, 210],  
    [70, 78, 72, 85],      
    [150, 160, 155, 175],  
    [110, 118, 115, 125],  
    [230, 145, 138, 160],  
    [65, 70, 68, 75]       
])
months = np.array([ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])
print("Sales shape (12 months × 4 products):", sales.shape)
print("First 3 months of sales:\n", sales[:3])

Sales shape (12 months × 4 products): (12, 4)
First 3 months of sales:
 [[120 145 130 155]
 [ 85  92  88 105]
 [200 210 105 130]]


In [60]:
months

array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec'], dtype='<U3')

#### Q46. Calculate total sales per month (sum across products).

In [61]:
total_sales = np.sum(sales , axis=1)
for m , s in zip(months,total_sales):
    print(f"{m} : {s}")

Jan : 550
Feb : 370
Mar : 645
Apr : 205
May : 693
Jun : 395
Jul : 773
Aug : 305
Sep : 640
Oct : 468
Nov : 673
Dec : 278


#### Q47. Calculate average sales per product (across 12 months).

In [62]:
print(np.mean(sales,axis=0))

[125.83333333 127.33333333 114.75       131.66666667]


#### Q48. Find best month for each product.

In [63]:
bst_m = np.argmax(sales,axis=0)
print("Best month for peoduct : ")
product = ["Product A","Product B","Product C","Product D"]
for p, m in zip(product,bst_m):
    print(f"{p} : {months[m]}")

Best month for peoduct : 
Product A : Nov
Product B : Mar
Product C : Jul
Product D : Jul
