# NUMPY COPY AND VIEW

In [1]:
import numpy as np

In [23]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 1. Create a copy of an array using .copy() and verify that changes do not affect the original array

In [3]:
ar1 = array.copy()
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar1[0] =999

In [5]:
print(array)
print(ar1)

[0 1 2 3 4 5 6 7 8 9]
[999   1   2   3   4   5   6   7   8   9]


#### 2. Create a copy of an array using np.copy() and demonstrate independence from the original array.

In [7]:
ar2 = np.copy(array)
ar2[4] = 999
print("Original array:", array)
print("Copied array  :", ar2)

Original array: [0 1 2 3 4 5 6 7 8 9]
Copied array  : [  0   1   2   3 999   5   6   7   8   9]


#### 3.Create a new array using slicing ([:]) and check whether it behaves as a copy or view.

In [8]:
ar3 = array[:]
ar3[0] =999
array

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])


#### 4. Create a copy of an array using np.array() and modify it to confirm original data remains unchanged.

In [12]:
ar4 = np.array(array).copy()
ar4[0] = 999
print("Original array:", array)
print("Copied array  :", ar4)

Original array: [0 1 2 3 4 5 6 7 8 9]
Copied array  : [999   1   2   3   4   5   6   7   8   9]


#### 5. Copy data from one array to another using np.copyto() and verify independence.

In [24]:
ar5 =np.empty_like(array)
np.copyto(ar5,array)
ar5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
ar5[0]=999

In [28]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ar5

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

#### 6. Create a new array using np.asarray() and determine whether it creates a copy or shares memory

In [30]:
ar6 = np.asarray(array)
ar6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ar6[0]=111

In [32]:
array

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

#### 7. Create a copy of an array using flatten() and verify that changes do not reflect in the original array.

In [33]:
ar7 = array.flatten()
ar7

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
ar7[0] = 888

In [35]:
array

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

#### 8. Create an array using ravel() and check whether it behaves as a copy or a view.

In [37]:
ar8 = array.ravel()
ar8

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [38]:
ar8[0]=1234

In [39]:
array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 9. Convert an array to a list and back to an array to create a copy and verify independence.

In [40]:
b = np.array(array.tolist())

# Modify new array
b[0] = 777

print("Original array:", array)
print("New array     :", b)

Original array: [1234    1    2    3    4    5    6    7    8    9]
New array     : [777   1   2   3   4   5   6   7   8   9]


#### 10. Create a copy of a 2D array and modify one element to ensure the original remains unchanged

In [41]:
array2d = array.reshape(2,-1)

In [42]:
array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [43]:
array2d

array([[1234,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [44]:
ar8 = array2d.copy()

In [45]:
ar8

array([[1234,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [46]:
ar8[0,0]=1111

In [47]:
array2d

array([[1234,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [48]:
ar8

array([[1111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

#### 11. Create a view and modify it to observe changes in original

In [49]:
new_array = np.array(range(1,11))
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
b1 = new_array.view()
b1[1] = 999
print(new_array)

[  1 999   3   4   5   6   7   8   9  10]


#### 12. Modify original and observe effect on view

In [51]:
new_array[0] = 0

In [52]:
b1

array([  0, 999,   3,   4,   5,   6,   7,   8,   9,  10])

#### 13. Check memory sharing using .base

In [57]:
b1.base

array([  0, 999,   3,   4,   5,   6,   7,   8,   9,  10])

#### 14. Use slicing and verify it behaves like view

In [58]:
b2 = new_array[:5]
b2

array([  0, 999,   3,   4,   5])

In [59]:
b2[-1]=111

In [60]:
new_array

array([  0, 999,   3,   4, 111,   6,   7,   8,   9,  10])

#### 15. Create view and check memory sharing

In [61]:
b3 = new_array.view()
print(np.shares_memory(new_array, b3))

True
