# NumPy Basic File Handling Functions – Simple Assignments

In [1]:
import numpy as np

### FUNCTION 1: np.save()
Save a single array to a binary file (.npy extension).

In [3]:
# Student scores data
scores = np.array([[85, 92, 78], [88, 91, 84], [79, 95, 87], [92, 88, 90]])
print("Scores array:\n", scores)
print("Shape:", scores.shape)

Scores array:
 [[85 92 78]
 [88 91 84]
 [79 95 87]
 [92 88 90]]
Shape: (4, 3)


#### Q1. Save the scores array to a file named "student_scores.npy" using np.save().

In [4]:
np.save("student_scores.npy",scores)

In [6]:
data = np.load("student_scores.npy")
data

array([[85, 92, 78],
       [88, 91, 84],
       [79, 95, 87],
       [92, 88, 90]])

#### Q2. Save the same array with a different filename "backup_scores.npy".

In [7]:
np.save( "backup_scores.npy",scores)

In [9]:
data1 = np.load( "backup_scores.npy")
data1

array([[85, 92, 78],
       [88, 91, 84],
       [79, 95, 87],
       [92, 88, 90]])

#### Q3. Try to save an array with integer data type and verify the file is created.

In [12]:
import os
np.save("int_arraay.npy",scores)
if os.path.exists("int_array.npy"):
    print("File created successfully")
else:
    print("File not found")

File not found


In [14]:
if os.path.exists("int_arraay.npy"):
    print("File created successfully")
else:
    print("File not found")

File created successfully


#### Q4. Save a 3D array (create one of shape 5×4×3) to a file named "3d_data.npy".

In [15]:
arr_3d = np.arange(60).reshape(5, 4, 3)
print("Shape:", arr_3d.shape)

np.save("3d_data.npy", arr_3d)

Shape: (5, 4, 3)


#### Q5. Save a float64 array to "float_data.npy" and check file size.

In [16]:
arr = np.array([1.5, 2.5, 3.5, 4.5], dtype=np.float64)
np.save("float_data.npy", arr)
size = os.path.getsize("float_data.npy")

print("File size:", size, "bytes")

File size: 160 bytes


# 

# 

### FUNCTION 2: np.load()
Load a saved .npy file back into an array.

#### Array (First save then load)


In [17]:
arr_to_save = np.array([10, 20, 30, 40, 50])
np.save("my_array.npy", arr_to_save)
print("Saved array:", arr_to_save)

Saved array: [10 20 30 40 50]


#### Q6. Load the "my_array.npy" file using np.load() and store in variable loaded_arr.

In [18]:
loaded_arr = np.load("my_array.npy")
loaded_arr

array([10, 20, 30, 40, 50])

#### Q7. Verify that loaded array has same values, shape, and dtype as original.

In [19]:
loaded_arr.shape

(5,)

In [20]:
arr_to_save.shape

(5,)

#### Q8. Load "student_scores.npy" from Q1 and calculate its mean.

In [22]:
scores = np.load("student_scores.npy")

mean_value = np.mean(scores)

print("Mean of scores:", np.round(mean_value,2))

Mean of scores: 87.42


#### Q9. Load "3d_data.npy"  and print its shape.

In [23]:
data3 = np.load("3d_data.npy")
data3.shape

(5, 4, 3)

#### Q10. Try to load a non-existent file and handle the error.

In [25]:
try:
    data = np.load("My_file.npy")  
    print(data)
except FileNotFoundError:
    print("Error: File not found!")

Error: File not found!


# 

# 

### FUNCTION 3: np.savez()
Save multiple arrays into a single compressed .npz file.

In [26]:
# Multiple arrays to save together
names = np.array(["Alice", "Bob", "Charlie", "Diana"])
ages = np.array([25, 30, 28, 35])
scores = np.array([85, 92, 78, 88])
print("Names:", names)
print("Ages:", ages)
print("Scores:", scores)

Names: ['Alice' 'Bob' 'Charlie' 'Diana']
Ages: [25 30 28 35]
Scores: [85 92 78 88]


#### Q11. Save all three arrays (names, ages, scores) into one file "student_data.npz" using np.savez().

In [27]:
np.savez("students_data.npz",names,ages,scores)

In [29]:
all_data = np.load("students_data.npz")
all_data

NpzFile 'students_data.npz' with keys: arr_0, arr_1, arr_2

#### Q12. Use keyword arguments to name the arrays (e.g., student_names=names).


In [30]:
names = np.array(["Omkar", "Rahul", "Amit"])
scores = np.array([85, 90, 88])

np.savez("students_data1.npz", student_names=names, student_scores=scores)

In [31]:
all_data2 = np.load("students_data.npz")
all_data

NpzFile 'students_data.npz' with keys: arr_0, arr_1, arr_2

#### Q13. Load the .npz file and access each array by its keyword name.

In [33]:
data5 = np.load("students_data1.npz")

names = data5["student_names"]
scores = data5["student_scores"]

print("Names:", names)
print("Scores:", scores)

Names: ['Omkar' 'Rahul' 'Amit']
Scores: [85 90 88]


#### Q14. Save arrays without keywords and access by index (arr_0, arr_1, arr_2).

In [3]:
data5 = np.load("students_data.npz")
print(data5['arr_0'])

['Alice' 'Bob' 'Charlie' 'Diana']


In [5]:
print(data5['arr_1'])

[25 30 28 35]


In [6]:
print(data5['arr_2'])

[85 92 78 88]


#### Q15. Add a fourth array "grades" with values ["A", "B", "C", "B"] to same npz file.

In [7]:
dataa = np.load("students_data.npz")
a = dataa['arr_0']
b = dataa['arr_1']
c = dataa['arr_2']
grades = np.array(["A", "B", "C", "B"])

np.savez('data.npz', a, b, c, grades)

new_data = np.load('data.npz')
print(new_data.files)

['arr_0', 'arr_1', 'arr_2', 'arr_3']


# 

# 

### FUNCTION 4: np.load() with .npz files
Load multiple arrays from compressed .npz file.

In [11]:
# Create and save .npz file
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
z = np.array([9, 10, 11, 12])
np.savez("xyz_data.npz", first=x, second=y, third3=z)
print("Saved x, y, z to xyz_data.npz")

Saved x, y, z to xyz_data.npz


#### Q16. Load "xyz_data.npz" and list all array names using .files attribute.

In [12]:
data_file = np.load( "xyz_data.npz")
print(data_file.files)

['first', 'second', 'third3']


#### Q17. Access the array named "second" from loaded .npz file.

In [13]:
data6 =np.load( "xyz_data.npz")
data6['second']

array([5, 6, 7, 8])

#### Q18. Load the file and compute sum of all three arrays.

In [15]:
data7 =np.load( "xyz_data.npz")
total_sum = np.sum(data7['first']) + np.sum(data7['second']) + np.sum(data7['third3'])

print("Total Sum:", total_sum)

Total Sum: 78


#### Q19. Check if key "first" exists in loaded .npz file.

In [16]:
data8 =np.load( "xyz_data.npz")
# Check if 'first' exists
if 'first' in data8.files:
    print("Key 'first' exists")
else:
    print("Key 'first' does not exist")

Key 'first' exists


#### Q20. Load "student_data.npz" and display the data type (dtype) of each array stored in it.

In [20]:
data = np.load('students_data.npz')

for key in data.files:
    print(key, ":", data[key].dtype)

arr_0 : <U7
arr_1 : int64
arr_2 : int64


In [21]:
for key in data.files:
    print(key, ":", data[key].dtype.name)

arr_0 : str224
arr_1 : int64
arr_2 : int64


# 

# 

### FUNCTION 5: np.savetxt()
Save array to text file (.txt, .csv) with custom delimiter.

In [22]:
sales = np.array([
    [1200, 1350, 1400, 1600],
    [800, 950, 1100, 1250],
    [2000, 2100, 2300, 2500],
    [500, 600, 700, 800],
    [1500, 1650, 1750, 1900]
])
print("Sales data (products × quarters):\n", sales)

Sales data (products × quarters):
 [[1200 1350 1400 1600]
 [ 800  950 1100 1250]
 [2000 2100 2300 2500]
 [ 500  600  700  800]
 [1500 1650 1750 1900]]


#### Q21. Save sales array to "sales.csv" with comma delimiter using np.savetxt().

In [25]:
np.savetxt("sales.csv",sales,delimiter=',')

#### Q22. Save same array to "sales.txt" with space delimiter.

In [26]:
np.savetxt("sales.txt",sales,delimiter=' ')

In [ ]:
np.savetxt("sales.csv",sales,delimiter=',')

#### Q23. Save as integers with format "%d" (no decimal points).

In [27]:
np.savetxt("sales.csv",sales,delimiter=',',fmt="%d")

#### Q24. Save only first 3 rows and first 2 columns to "subset_sales.csv".

In [28]:
np.savetxt("subset_sales.csv",sales[:3,:2])

# 

# 

### FUNCTION 6: np.loadtxt()
Load data from text file into array.

#### Array (Create text file first)

In [ ]:
sample_data = np.array([
    [1.5, 2.3, 3.7],
    [4.1, 5.6, 6.2],
    [7.8, 8.9, 9.4]
])
np.savetxt("sample.txt", sample_data, delimiter=",")
print("Created sample.txt")
print("Data saved:\n", sample_data)

#### Q25. Load "sales.txt" using np.loadtxt() with comma delimiter.

In [35]:
a_data = np.loadtxt("sales.txt",delimiter=' ')
a_data

array([[1200., 1350., 1400., 1600.],
       [ 800.,  950., 1100., 1250.],
       [2000., 2100., 2300., 2500.],
       [ 500.,  600.,  700.,  800.],
       [1500., 1650., 1750., 1900.]])

#### Q26. Load "sales.csv" from Q21 and calculate total sales per product.

In [36]:
a1_data = np.loadtxt("Sales.csv",delimiter=",")
print("Total Sales : ",np.sum(a1_data))

Total Sales :  27950.0


#### Q27. Load text file skipping first row (header) using skiprows=1.

In [38]:
a2_data = np.loadtxt("Sales.csv",delimiter=",",skiprows=1)

a2_data

array([[ 800.,  950., 1100., 1250.],
       [2000., 2100., 2300., 2500.],
       [ 500.,  600.,  700.,  800.],
       [1500., 1650., 1750., 1900.]])

#### Q28. Load only specific columns (e.g., columns 0 and 2) using usecols.

In [41]:
a3_data = np.loadtxt("Sales.csv",usecols=(0,2))

ValueError: could not convert string '1200,1350,1400,1600' to float64 at row 0, column 1.

In [43]:
a3_data = np.loadtxt("Sales.csv",delimiter=',',usecols=(0,2))
a3_data

array([[1200., 1400.],
       [ 800., 1100.],
       [2000., 2300.],
       [ 500.,  700.],
       [1500., 1750.]])

#### Q29. Load data as integers using dtype=int.

In [44]:
a4_data = np.loadtxt("Sales.csv",delimiter=',',dtype='int')
a4_data

array([[1200, 1350, 1400, 1600],
       [ 800,  950, 1100, 1250],
       [2000, 2100, 2300, 2500],
       [ 500,  600,  700,  800],
       [1500, 1650, 1750, 1900]])

#### Q30. Load "data.txt" using NumPy and print only the first row.

In [46]:
a5_data = np.loadtxt("Sales.csv",delimiter=',')
print(a5_data[0])

[1200. 1350. 1400. 1600.]


# 

# 

# FUNCTION 7: np.genfromtxt()
Advanced text loading with handling missing values.

#### Array (Create file with missing values)

In [47]:
# Create data with missing values as string
data_with_missing = """ID,Age,Score
1,25,85
2,,92
3,30,
4,28,78
5,,88
"""
with open("missing_data.csv", "w") as f:
    f.write(data_with_missing)
print("Created missing_data.csv")

Created missing_data.csv


#### Q31. Load "missing_data.csv" using np.genfromtxt() with delimiter=','.

In [50]:
miss_data = np.genfromtxt("missing_data.csv",delimiter=',')
print(miss_data)

[[nan nan nan]
 [ 1. 25. 85.]
 [ 2. nan 92.]
 [ 3. 30. nan]
 [ 4. 28. 78.]
 [ 5. nan 88.]]


#### Q32. Handle missing values by filling with 0 using filling_values=0.

In [51]:
new_data = np.genfromtxt("missing_data.csv" ,delimiter=',',filling_values=0)
new_data

array([[ 0.,  0.,  0.],
       [ 1., 25., 85.],
       [ 2.,  0., 92.],
       [ 3., 30.,  0.],
       [ 4., 28., 78.],
       [ 5.,  0., 88.]])

#### Q33. Skip header row using skip_header=1.

In [52]:
new_data2 = np.genfromtxt("missing_data.csv" ,delimiter=',',skip_header=1)
new_data2

array([[ 1., 25., 85.],
       [ 2., nan, 92.],
       [ 3., 30., nan],
       [ 4., 28., 78.],
       [ 5., nan, 88.]])

#### Q34. Use missing_values="" and filling_values=-1 to mark missing as -1.

In [53]:
new_data3 = np.genfromtxt("missing_data.csv" ,delimiter=',',filling_values=-1,missing_values='')
new_data3

array([[-1., -1., -1.],
       [ 1., 25., 85.],
       [ 2., -1., 92.],
       [ 3., 30., -1.],
       [ 4., 28., 78.],
       [ 5., -1., 88.]])

#### Q35. Load only numeric columns (skip ID column) using usecols=(1,2).

In [57]:
new_data4 = np.genfromtxt(
    "missing_data.csv",
    delimiter=',',
    usecols=(1, 2),
    skip_header=1,
    filling_values=-1
)
print(new_data4)

[[25. 85.]
 [-1. 92.]
 [30. -1.]
 [28. 78.]
 [-1. 88.]]
