## NumPy's Arithmetic Binary Functions.

In [2]:
import numpy as np

##### 1.	Add two arrays a = [1, 2, 3] and b = [4, 5, 6].

In [3]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])
print(a1+b1)
print(np.add(a1,b1))

[5 7 9]
[5 7 9]


##### 2.	Subtract array b = [4, 5, 6] from a = [10, 15, 20].

In [5]:
a2 = np.array( [4, 5, 6])
b2 = np.array( [10, 15, 20])
print(b2-a2)
print(np.subtract(b2,a2))

[ 6 10 14]
[ 6 10 14]


##### 3.	Multiply a = [2, 3, 4] with b = [5, 6, 7].

In [7]:
a3 = np.array( [2, 3, 4])
b3 = np.array(  [5, 6, 7])
print(a3*b3)
print(np.multiply(a3,b3))

[10 18 28]
[10 18 28]


##### 4.	Divide a = [10, 20, 30] by b = [2, 4, 5] using np.divide().

In [8]:
a4 = np.array([10, 20, 30])
b4 = np.array([2, 4, 5])
print(a4/b4)
print(np.divide(a4,b4))

[5. 5. 6.]
[5. 5. 6.]


##### 5.	Use np.floor_divide() on a = [10, 20, 30], b = [3, 6, 7].

In [9]:
a5 = np.array( [10, 20, 30])
b5 = np.array( [3, 6, 7])
print(a5//b5)
print(np.floor_divide(a5,b5))

[3 3 4]
[3 3 4]


##### 6.	Find the remainder using np.mod() for a = [10, 20, 30], b = [3, 4, 5].

In [10]:
a6 = np.array([10, 20, 30])
b6 = np.array( [3, 4, 5])
print(a6%b6)
print(np.mod(a6,b6))

[1 0 0]
[1 0 0]


##### 7.	Use np.power() to raise a = [2, 3, 4] to powers b = [2, 3, 1].

In [11]:
a7 = np.array([2, 3, 4] )
b7 = np.array([2, 3, 1])
print(a7**b7)
print(np.power(a7,b7))

[ 4 27  4]
[ 4 27  4]


##### 8.	Add a scalar 10 to array a = [1, 2, 3].

In [3]:
a8= np.array([1,2,3])
print(a8+10)
print(np.add(a8,10))

[11 12 13]
[11 12 13]


##### 9.	Subtract scalar 5 from array a = [10, 20, 30].

In [5]:
a9 = np.array([10, 20, 30])
print(a9-5)
print(np.subtract(a9,5))

[ 5 15 25]
[ 5 15 25]


##### 10.	Multiply each element in a = [2, 4, 6] by scalar 3.

In [7]:
a10 = np.array([2,4,6])
print(a10*3)
print(np.multiply(a10,3))

[ 6 12 18]
[ 6 12 18]


##### 11.	Divide a = [15, 30, 45] by scalar 5 using np.divide().

In [9]:
a11 = np.array([15,30,45])
print(a11/5)
print(np.divide(a11,5))

[3. 6. 9.]
[3. 6. 9.]


##### 12.	Floor divide a = [17, 35, 50] by scalar 6.

In [11]:
a12 = np.array([17,35,50])
print(a12//6)
print(np.floor_divide(a12,6))

[2 5 8]
[2 5 8]


##### 13.	Modulus of a = [11, 21, 31] with scalar 4.

In [12]:
a13 = np.array([11,21,31])
print(a13%4)
print(np.mod(a13,4))

[3 1 3]
[3 1 3]


##### 14.	Raise a = [2, 3, 5] to power 3 using np.power().

In [13]:
a14 = np.array([2,3,5])
print(a14**3)
print(np.power(a14,3))

[  8  27 125]
[  8  27 125]


##### 15.	Add two 2D arrays:    a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].


In [14]:
a15 = np.array( [[1, 2], [3, 4]] )
b15 = np.array([[5, 6], [7, 8]])
print(a15+b15)
print(np.add(a15,b15))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


#### 16.	Multiply arrays with different shapes using broadcasting:
##### a = [[1], [2], [3]], b = [10, 20].


In [18]:
a16 = np.array([[1], [2], [3]])
b16 = np.array( [10, 20])
print(a16*b16)
print()
print(np.multiply(a16,b16))
print()
print(np.multiply(b16,a16))


[[10 20]
 [20 40]
 [30 60]]

[[10 20]
 [20 40]
 [30 60]]

[[10 20]
 [20 40]
 [30 60]]


##### 17.	Use np.subtract() for arrays with negative numbers:
##### a = [-5, -10, 15], b = [5, -5, 5].


In [19]:
a17 = np.array([-5, -10, 15])
b17 = np.array( [5, -5, 5])
print(a17-b17)
print(np.subtract(a17,b17))

[-10  -5  10]
[-10  -5  10]


##### 18.	Use np.mod() for negative dividends:    a = [-10, -20, -30], b = [3, 4, 5].


In [21]:
a18 = np.array([-10,-20,-30])
b18 = np.array( [3, 4, 5])
print(a18%b18)
print(np.mod(a18,b18))

[2 0 0]
[2 0 0]


##### 19.	Use np.power() where power is 0: a = [10, 20, 30], b = [0, 0, 0].


In [22]:
a19 = np.array([10,20,30])
b19 = np.array([0,0,0])
print(a19**b19)
print(np.power(a19,b19))

[1 1 1]
[1 1 1]


In [29]:
print("1**0   = ",1**0)
print("0**0   = ",0**0)
print("-1**0  = ",-1**0)
print("-1**-1 = ",-1**-1)
print("1**-1  = ",1**-1)
print("-10**2 = ",-10**2)
print("10**-2 =",10**-2)

1**0   =  1
0**0   =  1
-1**0  =  -1
-1**-1 =  -1.0
1**-1  =  1.0
-10**2 =  -100
10**-2 = 0.01


##### 20.	Divide two float arrays: a = [10.5, 20.2, 30.3], b = [2.1, 2.0, 3.3].


In [30]:
a20 = np.array([10.5, 20.2, 30.3])
b20 = np.array([2.1, 2.0, 3.3])
print(a20/b20)
print(np.divide(a20,b20))

[ 5.         10.1         9.18181818]
[ 5.         10.1         9.18181818]


##### 21.	Multiply a 1D array a = [1, 2, 3] with a 2D array b = [[1, 2, 3], [4, 5, 6]].

In [33]:
a21 = np.array([1, 2, 3] )
b21 = np.array( [[1, 2, 3], [4, 5, 6]])
print(a21*b21)
print(a21+b21)

[[ 1  4  9]
 [ 4 10 18]]
[[2 4 6]
 [5 7 9]]


##### 22.	Add arrays with mixed integers and floats:
a = [1.5, 2.5, 3.5], b = [1, 2, 3].


In [45]:
a22 = np.array([1.5,2.5,3.5])
b22 = np.array([1,2,3])
print(a22+b22)
print(np.add(a22,b22,dtype=int,casting = 'unsafe'))

[2.5 4.5 6.5]
[2 4 6]


##### 23.	Use np.floor_divide() with float values:
a = [5.5, 10.2, 15.9], b = [2.1, 3.2, 4.5].


In [47]:
a23 = np.array([5.5,10.2,15.9])
b23 = np.array([2.1,3.2,4.5])
print(a23//b23)
print(np.floor_divide(a23,b23))

[2. 3. 3.]
[2. 3. 3.]


##### 24.	Apply np.power() element-wise on large exponents:
a = [2, 3, 4], b = [10, 5, 3].


In [49]:
a24 = np.array([2,3,4])
b24 = np.array([10,5,3])
print(a24**b24)
print(np.power(a24,b24))

[1024  243   64]
[1024  243   64]


##### 25.	Add a column vector a = [[1], [2], [3]] to a row vector b = [10, 20, 30] using broadcasting.

In [50]:
a25 = np.array([[1],[2],[3]])
b25 = np.array([10,20,30])
print(a25+b25)
print(np.add(a25,b25))

[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
