## Bitwise Binary Function Practice 

In [2]:
import numpy as np

##### 1.	Perform np.bitwise_and() on a = [1, 2, 3], b = [3, 2, 1].

In [3]:
a1 = np.array([1,2,3])
b1 = np.array([3,2,1])
print(a1&b1)
print(np.bitwise_and(a1,b1))

[1 2 1]
[1 2 1]


##### 2.	Perform np.bitwise_or() on a = [5, 10, 15], b = [1, 2, 3].

In [5]:
a2 = np.array([5,10,15])
b2 = np.array([1,2,3])
print(a2|b2)
print(np.bitwise_or(a2,b2))  

[ 5 10 15]
[ 5 10 15]


##### 3.	Use np.bitwise_xor() on a = [12, 25, 37], b = [15, 30, 42].

In [10]:
a3 = np.array([12,25,37])
b3 = np.array([15,30,42])
print(a3^b3)
print(np.bitwise_xor(a3,b3))

[ 3  7 15]
[ 3  7 15]


#### 4.	Compare the result of np.bitwise_and(6, 3) manually and verify with code.

In [8]:
print(np.bitwise_and(6, 3) )
print(6&3)

2
2


##### 5.	Perform bitwise AND between two boolean arrays:
a = [True, False, True], b = [False, False, True].


In [11]:
a4 = np.array([True, False, True])
b4 = np.array([False, False, True])
print(a4&b4)
print(np.bitwise_and(a4,b4))

[False False  True]
[False False  True]


##### 6.	Use np.bitwise_or() with binary equivalents:
a = [0b1100, 0b1010], b = [0b1010, 0b1100].


In [14]:
a6 = np.array( [0b1100, 0b1010])
b6 = np.array([0b1010, 0b1100])
print(a6.dtype)
print(b6.dtype)
print(a6)
print("_"*20)
print(np.bitwise_or(a6,b6    )  )

int64
int64
[12 10]
____________________
