# Logical Binary Function 

In [1]:
import numpy as np

##### 1.	Use np.logical_and() on a = [True, False, True], b = [False, False, True].

In [5]:
a1 = np.array([True,False,True])
b1 = np.array([False,False,True])
print(a1& b1)
print(np.logical_and(a1,b1))

[False False  True]
[False False  True]


##### 2.	Use np.logical_or() on a = [0, 1, 2], b = [1, 0, 3].
###### & , |,^ - use only boolean type data not numberic 
###### (& , |,^) = In Boolean -> Logaical operation
###### (& , |,^) = In Numeric -> Bitwise operation
###### (& , |,^) = In Str -> Error

In [28]:
a2 = np.array([0, 1, 2])
b2 = np.array([1, 0, 3])
print(a2.astype(bool)|b2.astype(bool))
print(a2|b2)
print(np.logical_or(a2,b2))

[ True  True  True]
[1 1 3]
[ True  True  True]


##### 3.	Use np.logical_xor() on a = [True, True, False], b = [False, True, False].

In [7]:
a3 = np.array([True,True,False])
b3 = np.array([False,True,False])
print(np.logical_xor(a3,b3))

[ True False False]


##### 4.	Check where both arrays are positive using logical_and():
a = [1, -1, 1], b = [2, 2, 0].


In [15]:
a4 = np.array([1,-1,1])
b4 = np.array([2,2,0])
print((a4&b4))
print(np.logical_and(a4,b4))

[0 2 0]
[ True  True False]


##### 5.	Create a condition using logical_or():
a > 3 OR b < 2 where a = [2, 4, 1], b = [1, 2, 3].


In [30]:
a5 = np.array([2, 4, 1])
b5 = np.array([1,2,3])
print(np.logical_or(a5,b5,where=(a5>3)|(b5<2)))

print(np.logical_or(a5>3,b5<2))

[ True  True False]
[ True  True False]


##### 6.	Compare two arrays element-wise using logical_xor() to find where values differ.

In [20]:
a6 = np.random.randint(-10,10,10)
b6 = np.random.randint(-10,10,10)
print(np.logical_or(a6,b6,where=a6!=b6))


[ True  True  True  True  True  True  True False  True  True]


In [21]:
print(a6)
print(b6)

[ -8  -2  -9  -9 -10  -2  -5   6  -6  -8]
[  1   7 -10  -1  -2  -4   1   6  -8   9]


In [22]:
a=-1
b=1
np.logical_or(a,b,where=a!=b)

np.True_

##### 7.	Test logical_and() with boolean conditions: a > 5 and b < 10.

In [32]:
a7 = np.random.randint(1,15,10)
b7 = np.random.randint(1,15,10)
print(np.logical_and(a7,b7,where=(a7>5)&(b7<10)))

print(np.logical_and(a7>5,b7<10))

[ True  True False False False  True  True  True False  True]
[False  True False False False  True  True  True False  True]


##### 8.	Use np.logical_or() to filter all non-zero or negative values.

In [36]:
a8=np.array([0,1,-1],dtype=bool)
print(a8)
a8 = np.array([0, -1, 2])
b8 = np.array([1, 0, -3])

print(np.logical_or(a8 < 0, b8 != 0))

[False  True  True]
[ True  True  True]


##### 9.	Try logical_and() on arrays:
a = [0, 1, 2], b = [3, 0, 4].


In [37]:
a9 = np.array([0,1,2])
b9 = np.array([3,0,4])
print(np.logical_and(a9,b9))

[False False  True]


##### 10.	Combine logical_and() and logical_not() to find where both are False.

In [38]:
a10 = np.array([0, 1, 0])
b10 = np.array([0, 0, 2])

mask = np.logical_not(np.logical_or(a10, b10))
print(mask)

[ True False False]


##### 11.	Use broadcasting in logical_xor():
a = [[True], [False]], b = [True, False]


In [40]:
a11 = np.array([[True],[False]])
b11 = np.array([True,False])
print(a11^b11)

print(np.logical_xor(a11,b11))

[[False  True]
 [ True False]]
[[False  True]
 [ True False]]


##### 12.	Apply logical_or() between scalar and array: True OR a = [False, False, True].

In [41]:
a12 = np.array([False,False, True])
b12 = True
print(a12|b12)
print(np.logical_or(a12,b12))

[ True  True  True]
[ True  True  True]


##### 13.	Use logical_and() with mixed booleans and integers:
a = [0, 1, 2], b = [True, False, True].


In [43]:
a13 = np.array([0,1,2])
b13 = np.array([True,False,True])
print(np.logical_and(a13,b13))
print(a13&b13)
print(b13&a13)

[False False  True]
[0 0 0]
[0 0 0]


##### 14.	Detect where two arrays are both non-zero using logical_and().

In [44]:
a14 = np.array([1,0,-1])
b14 = np.array([0,1,1])
print(np.logical_and(a14,b14))

[False False  True]


##### 15.	Count how many True values are in result of logical_or() for given a, b.

In [47]:
a15 = np.array([1,0,-1,0])
b15 = np.array([00,0,-1,1])
print("Count : ",np.logical_or(a15,b15).sum())


Count :  3


##### 16.	Check if any condition is satisfied across arrays using logical_or().

In [54]:
a16 = np.random.randint(1,50,10)
b16 = np.random.randint(1,50,10)
print("Array 1 : ",a16)
print("Array 2 : ",b16)
print(np.logical_or(a16>25,b16<25).any())

Array 1 :  [48 41 43 32 31 49  2 44  7 28]
Array 2 :  [22 39 22 38 43 12 16 36 46 10]
True


##### 17.	Test for exclusive condition using logical_xor(): a > 3, b < 5.

In [56]:
a17 = np.random.randint(1,5,10)
b17 = np.random.randint(1,5,10)
print("Array 1 : ",a17)
print("Array 2 : ",b17)
print(np.logical_xor(a17>3,b17<5))

Array 1 :  [3 4 2 3 3 4 2 1 4 3]
Array 2 :  [4 1 2 2 3 1 1 4 4 2]
[ True False  True  True  True False  True  True False  True]


##### 18.	Use logical_and() with:
a = np.arange(5), b = np.array([1, 0, 3, 0, 5]).


In [57]:
a18 = np.arange(5)
b18 = np.array([1, 0, 3, 0, 5])
print(np.logical_and(a18,b18))


[False False  True False  True]


##### 19.	Combine multiple logical operations:
(a > 2) & (b < 6) using logical_and().


In [59]:
a19 = np.arange(10)
b19 = np.linspace(0,11,10,dtype=int)
print(np.logical_and(a19>2,b19<6))

[False False False  True  True False False False False False]


In [61]:


aaa = np.array([1, 3, 5])
baa = np.array([7, 5, 4])

cond1 = aaa > 2        # [False, True, True]
cond2 = baa < 6        # [False, True, True]

res = np.logical_and( aaa > 2 , cond2)
print(np.logical_and(cond1,  baa < 6 ))
print(res)


[False  True  True]
[False  True  True]


##### 20.	Chain logical_and() and logical_or() to create a complex filter.

In [63]:
a20 = np.random.randint(1,100,10)
b20 = np.random.randint(1,100,10)
cond1 = np.logical_and(a20 > 3, b20 < 6)
cond2 = a20 < 2
final = np.logical_or(cond1, cond2)
print(final)

[False False  True False False False  True False False False]


##### 21.	Test logical_xor() with identical arrays and explain output.

In [65]:
a21 = np.array([1, 2, 3])
b21 = np.array([1, 2, 3])
print(np.logical_xor(a21,b21))

[False False False]


##### 22.	Use np.logical_or() on empty arrays and explain result.

In [68]:
a22 = np.array([])
b22 = np.array([])
print(np.logical_or(a22,b22))
# When arrays are empty, the output is also an empty array
# No error occurs, shape is preserved.

[]


##### 23.	Create a mask where only one condition is true using logical_xor().

In [70]:
a23 = np.array([1,0,3])
b23 = np.array([3,2,1])
mask = np.logical_xor(a23,b23)
print(mask)

[False  True False]


##### 24.	Use logical_and() to filter rows in a 2D array that satisfy multiple conditions.

In [76]:
a24 = np.arange(12).reshape(6,-1)
mask = np.logical_and(a24[:, 0] > 2, a24[:, 1] < 7)
filtered = a24[mask]
print(a24)
print("_"*20)
print(filtered)
print("_"*20)

print(a24[(a24[:,0]>2 ) & (a24[:,-1]<7)])

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
____________________
[[4 5]]
____________________
[[4 5]]
