## Core NumPy operations:
### 1. ARITHMETIC OPERATIONS
### 2. COMPARISON OPERATIONS
### 3. LOGICAL OPERATIONS

In [1]:
import numpy as np

### 1. ARITHMETIC OPERATIONS

In [2]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 4, 3, 2, 1])

In [3]:
a

array([10, 20, 30, 40, 50])

In [4]:
b

array([5, 4, 3, 2, 1])

#### 1. Add 10 to all elements in a

In [5]:
np.add(a,10)

array([20, 30, 40, 50, 60])

In [6]:
a+10

array([20, 30, 40, 50, 60])

#### 2. Subtract 5 from all elements in a

In [7]:
np.subtract(a,5)

array([ 5, 15, 25, 35, 45])

In [8]:
a-5

array([ 5, 15, 25, 35, 45])

#### 3. Multiply all elements of a by 2

In [9]:
np.multiply(a,2)

array([ 20,  40,  60,  80, 100])

In [10]:
a*2

array([ 20,  40,  60,  80, 100])

#### 4. Divide all elements of a by 2

In [11]:
np.divide(a,2)

array([ 5., 10., 15., 20., 25.])

In [12]:
a/2

array([ 5., 10., 15., 20., 25.])

#### 5. Add arrays a + b

In [13]:
np.add(a,b)

array([15, 24, 33, 42, 51])

In [14]:
a+b

array([15, 24, 33, 42, 51])

#### 6. Subtract arrays a - b

In [15]:
np.subtract(a,b)

array([ 5, 16, 27, 38, 49])

In [16]:
a-b

array([ 5, 16, 27, 38, 49])

#### 7. Multiply arrays a * b

In [17]:
np.multiply(a,b)

array([50, 80, 90, 80, 50])

In [18]:
a*b

array([50, 80, 90, 80, 50])

#### 8. Divide arrays a / b

In [19]:
np.divide(a,b)

array([ 2.,  5., 10., 20., 50.])

In [20]:
a/b

array([ 2.,  5., 10., 20., 50.])

#### 9. Find square of all elements in a

In [21]:
np.power(a,2)

array([ 100,  400,  900, 1600, 2500])

In [22]:
np.multiply(a,a)

array([ 100,  400,  900, 1600, 2500])

In [23]:
a**2

array([ 100,  400,  900, 1600, 2500])

#### 10 . Find cube of all elements in a

In [24]:
np.power(a,3)

array([  1000,   8000,  27000,  64000, 125000])

In [25]:
a

array([10, 20, 30, 40, 50])

In [26]:
a**3

array([  1000,   8000,  27000,  64000, 125000])

In [27]:
np.multiply(a*a,a)

array([  1000,   8000,  27000,  64000, 125000])

#### 11. Add scalar 100 to all elements

In [28]:
b

array([5, 4, 3, 2, 1])

In [29]:
np.add(b,100)

array([105, 104, 103, 102, 101])

In [30]:
b+100

array([105, 104, 103, 102, 101])

#### 12. Multiply all elements by 0.5 (discount simulation)

In [31]:
np.multiply(b,0.5)

array([2.5, 2. , 1.5, 1. , 0.5])

#### 13. Compute total sum of a + b

In [32]:
np.sum(a+b)

np.int64(165)

In [33]:
print(np.sum(a+b))

165


#### 14. Compute difference sum (a - b)

In [34]:
print(np.sum(a-b))

135


#### 15. Find percentage increase of a from b

In [35]:
print("Array A :",a)
print("Array B :",b)

Array A : [10 20 30 40 50]
Array B : [5 4 3 2 1]


In [36]:
np.divide(a,b)*100

array([ 200.,  500., 1000., 2000., 5000.])

### 2. COMPARISON OPERATIONS

In [37]:
a = np.array([10, 25, 30, 45, 60])
b = np.array([15, 20, 30, 40, 50])

In [38]:
print("Array A : ",a)
print("Array B : ",b)

Array A :  [10 25 30 45 60]
Array B :  [15 20 30 40 50]


#### 1. Find elements in a greater than 30

In [39]:
a>30

array([False, False, False,  True,  True])

In [40]:
a[a>30]

array([45, 60])

In [41]:
np.greater(a,30)

array([False, False, False,  True,  True])

In [42]:
a.greater(30)

AttributeError: 'numpy.ndarray' object has no attribute 'greater'

In [43]:
a[np.greater(a,30)]

array([45, 60])

In [44]:
greater_data = np.greater(a,30)
a[greater_data]

array([45, 60])

#### 2. Find elements in b less than 40

In [45]:
b[np.less(b,40)]

array([15, 20, 30])

In [46]:
b[b<40]

array([15, 20, 30])

#### 3. Find equal elements in both arrays

In [47]:
a1 = np.equal(a,b)
# c = np.concatenate(a,b)
a[a1]

array([30])

In [48]:
print("Array A :",a)
print("Array B :",b)

Array A : [10 25 30 45 60]
Array B : [15 20 30 40 50]


In [49]:
a[a==b]

array([30])

#### 4. Count how many values in a > 20

In [50]:
np.greater(a,20).size

5

#### 5. Count how many values in b < 30

In [51]:
np.less(b,30).size

5

#### 6. Find max comparison result (a > b)

In [52]:
a[a>b].max()

np.int64(60)

#### 7. Find min comparison result (a < b)

In [53]:
a[a<b].min()

np.int64(10)

#### 8. Get indices where a > b

In [54]:
a[a>b].index()

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [55]:
mask_index = np.argwhere(a>b)

In [56]:
mask_index

array([[1],
       [3],
       [4]])

#### 9. Get indices where a == b

In [57]:
mask_index2 = np.argwhere(a==b)
mask_index2

array([[2]])

In [58]:
print("A :",a)
print("B :",b)

A : [10 25 30 45 60]
B : [15 20 30 40 50]


#### 10. Compare if arrays are equal completely

In [61]:
np.where(a==b,1,0).all()

np.False_

#### 11. Check if any element in a > 50

In [62]:
np.where(a>50,1,0).any()

np.True_

#### 12. Check if all elements in b > 10

In [64]:
(b>10).all()

np.True_

#### 13. Replace values in a > 40 with -1

In [66]:
c = np.where(a>40,-1,c)
c

array([10, 25, 30, -1, -1])

#### 14. Create mask of values where a > b

In [68]:
mask = a>b
mask

array([False,  True, False,  True,  True])

#### 15 . Check a > b
###### Check a < b
###### Check a == b
######  a != b
###### Check a >= b
###### Check a <= b

In [72]:
print(a<b,end="\n\n")
print(a==b,end='\n\n')
print(a !=b,end='\n\n')
print(a>=b,end='\n\n')
print(a<=b,end='\n\n')

[ True False False False False]

[False False  True False False]

[ True  True False  True  True]

[False  True  True  True  True]

[ True False  True False False]



### 3. LOGICAL OPERATIONS

#### 1. Check (a > 10) & (b > 10)

In [73]:
(a>10)&(b>10)

array([False,  True,  True,  True,  True])

In [74]:
np.logical_and(a>b,b>10)

array([False,  True, False,  True,  True])

#### 2. Check (a > 20) | (b > 20)

In [75]:
np.logical_or(a>20,b>20)

array([False,  True,  True,  True,  True])

In [77]:
(a>20)|(b>20)

array([False,  True,  True,  True,  True])

#### 3. Check ~(a > 20)

In [78]:
np.logical_not(a>20)

array([ True, False, False, False, False])

In [79]:
~(a>30)

array([ True,  True,  True, False, False])

#### 4. Find values where a > 15 AND b < 20

In [82]:
np.select([a>15,b<20],[a,b])

array([15, 25, 30, 45, 60])

In [85]:
result = a[(a > 15) & (b < 20)]
print(result)

[]


In [84]:
a

array([10, 25, 30, 45, 60])

In [83]:
b

array([15, 20, 30, 40, 50])

#### 5. Find values where a > 20 OR b > 20

In [87]:
result = a[(a > 20) | (b > 20)]
print(result)

[25 30 45 60]


#### 6. Find values where NOT (a < 20)

In [88]:
a[~(a<20)]

array([25, 30, 45, 60])

In [89]:
a[np.logical_not(a<20)]

array([25, 30, 45, 60])

#### 7. Combine condition: (a > 15) & (b == 15)

In [90]:
np.logical_and(a>15,b==5)

array([False, False, False, False, False])

#### 8. Filter values where both arrays are equal

In [91]:
a[a==b]

array([30])

In [92]:
b[a==b]

array([30])

#### 9. Filter values where either is > 25

In [94]:
a[(a>25)|(b>25)]

array([30, 45, 60])

#### 10. Find elements where neither condition is true

In [98]:
a[~((a>25)|(b>25))]

array([10, 25])

In [100]:
result = a[~((a > 25) | (b > 25))]
print(result)

[10 25]


#### 11. Count how many satisfy a > 20 & b < 20

In [101]:
np.logical_and(a>20,b<20).sum()

np.int64(0)

In [104]:
np.sum((a > 20) & (b < 20))

np.int64(0)

#### 12. Replace values where (a < 20) with 0

In [106]:
np.where(a<20,0,a)

array([ 0, 25, 30, 45, 60])

#### 13.Replace values where (b > 20) with -1

In [107]:
np.where(b>20,-1,a)

array([10, 25, -1, -1, -1])

#### 14. Create boolean mask for a in range 10–25

In [109]:
mask = ((a>=10)&(a<=25))
mask

array([ True,  True, False, False, False])

#### 15. Create mask for b not equal to 15

In [111]:
mask = b!=15
mask

array([False,  True,  True,  True,  True])

#### 16. Find valid entries where both > 10

In [112]:
result = a[(a > 10) & (b > 10)]
print(result)

[25 30 45 60]


#### 17. Check if any element satisfies (a > 25 & b > 25)

In [113]:
np.logical_and(a>25,b>25).any()

np.True_

In [118]:
a[np.logical_and(a>25,b>25)]

array([30, 45, 60])

In [119]:
b[np.logical_and(a>25,b>25)]

array([30, 40, 50])

#### 18. Check if all elements satisfy (a > 5)

In [120]:
a[a>5].all()

np.True_

#### 19. Extract values where (a + b > 40)

In [123]:
result = a[(a + b) > 40]
result

array([25, 30, 45, 60])

#### 20. Final filter: (a > b) & (b < 20)

In [124]:
a[(a>b)&(b<20)]

array([], dtype=int64)