### Numpy Creation 

In [1]:
import numpy as np 


In [2]:
a = np.array([1, 2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([1,2,3,4,3.3],dtype=int)

In [10]:
a1


array([1, 2, 3, 4, 3])

In [6]:
a1.dtype

dtype('float64')

In [14]:
a2 = np.array([[1,2,3],[2,1,3]])
print(a2)

[[1 2 3]
 [2 1 3]]


In [17]:
a3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[3,2,1]]])
print(a3)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [3 2 1]]]


### Dimension and Shapes 

In [20]:
print(a3.shape)
a3.ndim

(2, 2, 3)


3

#  1. Creating array using arange()

In [22]:
ar1 = np.arange(5)
print(ar1)

[0 1 2 3 4]


In [23]:
ar2 = np.arange(1,10,3)
print(ar2)

[1 4 7]


In [24]:
ar3 = np.arange(10,0,-1)
print(ar3)

[10  9  8  7  6  5  4  3  2  1]


In [26]:
ar4 = np.arange(5,15)
ar4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Emmpty arrranay
ar5 = np.arange(5, 5)
print(ar5)  # []


In [30]:
ar6 = np.arange(2.5, 5.5, 0.5,dtype= int )
ar6

array([2, 3, 4, 5, 6, 7])

In [32]:
ar7 = np.arange(0,100,7)
print(ar7)

[ 0  7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [34]:
ar8 = np.arange(12).reshape(3,4)
ar8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
ar9 = np.arange(0,1,0.1)
print(ar9)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### एक array बनाओ जिसमें 100 से शुरू होकर 10 तक values हों, हर step -7.5 हो।

In [49]:
ar10 = np.arange(100,10,-7.5)
print(ar10)

[100.   92.5  85.   77.5  70.   62.5  55.   47.5  40.   32.5  25.   17.5]


In [39]:
ar11 = np.arange(25).reshape(5,5)
ar11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### arange() से एक array बनाओ जिसमें सिर्फ 3 के multiples हों और 50 से कम हों, और फिर इसे reverse करो

In [42]:
ar12 = np.arange(3,50,3)
ar12
ar12[::-1]

array([48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

#### arange() से 1D array बनाओ फिर उसे reshape() करके 3D array में convert करो (shape = (2, 3, 2))।



In [43]:
ar13 = np.arange(12).reshape(2,3,2)
ar13

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

##### 0 से 1 के बीच (exclusive) 0.05 step size वाली array बनाओ और फिर उसे np.round() से 2 decimal तक round करो

In [56]:
ar14 = np.arange(0,1,0.05)
ar14
ar14= np.round(ar14,23)
print(ar14)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


# 2. Creating array using linspace()

In [62]:
aa1 = np.linspace(1,10)
aa1.size

[ 1.1         1.28163265  1.46326531  1.64489796  1.82653061  2.00816327
  2.18979592  2.37142857  2.55306122  2.73469388  2.91632653  3.09795918
  3.27959184  3.46122449  3.64285714  3.8244898   4.00612245  4.1877551
  4.36938776  4.55102041  4.73265306  4.91428571  5.09591837  5.27755102
  5.45918367  5.64081633  5.82244898  6.00408163  6.18571429  6.36734694
  6.54897959  6.73061224  6.9122449   7.09387755  7.2755102   7.45714286
  7.63877551  7.82040816  8.00204082  8.18367347  8.36530612  8.54693878
  8.72857143  8.91020408  9.09183673  9.27346939  9.45510204  9.63673469
  9.81836735 10.        ]


In [71]:
aa2 = np.linspace(1,10,10)
print(aa2.size)
aa = np.linspace(1,10,num = 10)
print(aa.size)

10
10


In [78]:
aa3 = np.linspace(1,100,num = 10, dtype=int)
aa4 = np.linspace(1,100,  num= 10, endpoint = False,  dtype = int , retstep = True)
print(aa3)
print(aa4)

[  1  12  23  34  45  56  67  78  89 100]
(array([ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]), np.float64(9.9))


#### 0 से 10 तक 5 values बनाओ और साथ में step size भी print करो (retstep=True)।


In [80]:
ab1, step  = np.linspace(0,10,5, retstep= True)
print(ab1)
print("Step : ",step)

[ 0.   2.5  5.   7.5 10. ]
Step :  2.5


#### 10 से 1 तक reverse order में linspace से array बनाओ।

In [82]:
ab2 = np.linspace(10,1,10).astype(int)
ab2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### एक array बनाओ जिसमें 0 से 1 तक के बीच 1000 points हों।

In [86]:
ab3= np.linspace(0,1,1000)
print(ab3.size)

1000


#### linspace() से बने array को np.sin() में input दो।

In [87]:
x = np.linspace(0, np.pi, 5)
y = np.sin(x)
print(y)


[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


#### Two array eleemnt - wise sum 

In [90]:
a1 = np.linspace(0, 100, 10).astype(int)
a2 = np.linspace(10, 0, 10).astype(int)
sum_array = a1 + a2
print(sum_array)



[ 10  19  29  39  49  59  69  79  89 100]


####  Gradient-style 2D array (shape 10×1):

In [91]:
a = np.linspace(0, 1, 10).reshape(10, 1)
print(a)


[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


# 3. Creating array using np.zeroes() and np.ones()

#### 1. एक 1D array जिसमें 5 zeros हों:

In [93]:
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

#### 2. एक 1D array जिसमें 6 ones हों:

In [94]:
on1 = np.ones(6)
on1

array([1., 1., 1., 1., 1., 1.])

#### 3. 2×3 zero matrix:

In [95]:
z2 = np.zeros((2,3))
z2

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 4. 4×4 matrix filled with ones (integer type):

In [97]:
on2 = np.ones((4,4), dtype=int)
on2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Zero array with boolean type:

In [98]:
z3 = np.zeros((2,3),dtype=bool)
z3

array([[False, False, False],
       [False, False, False]])

####  2×2 array filled with 1.5:

In [105]:
on3 = np.ones((2,2))+0.5
print(on3)
on4 = np.ones((2,2))*1.5
print("\n second : \n",on4)

[[1.5 1.5]
 [1.5 1.5]]

 second : 
 [[1.5 1.5]
 [1.5 1.5]]


####  Identity-like matrix filled with 5s:

In [106]:
on5 = np.ones((3,3))*5
on5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

### एक ऐसे 2x3 array बनाओ जिसमें alternate row zeros और ones हो।

In [107]:
a = np.array([
    np.zeros(3),
    np.ones(3)
])
print(a)


[[0. 0. 0.]
 [1. 1. 1.]]


#### Transpose of ones array:

In [108]:
on6 = np.ones((2,3)).T
on6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

####  (3×3) array filled with 1s, middle = 0:

In [109]:
on7 = np.ones((3,3))
on7[1,1]=0
print(on7)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


# 4. Crearing array using np.full()

#### 1.एक 1D array बनाओ जिसमें 5 elements हों और सभी का मान 7 हो।

In [110]:
f1 = np.full(5,7)
f1

array([7, 7, 7, 7, 7])

#### 2.एक 2x3 matrix बनाओ जिसमें सभी values 0.5 हों।

In [112]:
f2 = np.full((2,3),0.5)
f2

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

#### 3. np.full() का उपयोग करके एक 3x3 matrix बनाओ जिसमें सभी values 100 हों

In [113]:
print(np.full((3,3),100))

[[100 100 100]
 [100 100 100]
 [100 100 100]]


#### 4. एक 4x1 shape वाली array बनाओ filled with -1.

In [114]:
print(np.full((4,1),-1))

[[-1]
 [-1]
 [-1]
 [-1]]


#### 5. एक integer-type array बनाओ जिसमें सभी values 9 हों और shape (2, 2) हो।

In [115]:
print(np.full((2,2),9))

[[9 9]
 [9 9]]


#### 6. एक 3x3 matrix बनाओ filled with string 'A'।


In [137]:
print(np.full((3,3),"A"))
print(np.full((3,3),"A").dtype)
print(np.full((3,3),"A",dtype=str))
print(np.full((3,3),"A").dtype)

[['A' 'A' 'A']
 ['A' 'A' 'A']
 ['A' 'A' 'A']]
<U1
[['A' 'A' 'A']
 ['A' 'A' 'A']
 ['A' 'A' 'A']]
<U1


#### 7. एक 5x5 matrix बनाओ जिसमें सभी elements 3.14 हों और dtype='float32' हो।

In [123]:
print(np.full((5,5),3.14, dtype= 'float32'))
print("second :")
print(np.full((5,5),3.14, dtype= float))

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
second :
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


#### 8 . एक 2D array बनाओ filled with 0s using np.full() (not np.zeros())

In [124]:
print(np.full((2,3),0))

[[0 0 0]
 [0 0 0]]


#### 9. एक array बनाओ जिसकी shape (3, 1, 2) हो और values 1.1 से filled हों।

In [126]:
print(np.full((3,1,2),1.1))

[[[1.1 1.1]]

 [[1.1 1.1]]

 [[1.1 1.1]]]


#### 10. एक 6x1 array बनाओ जिसमें सभी values 'Python' हों (dtype=object)।

In [132]:
print(np.full((6,1),'Python',dtype= object))
print(np.full((6,1),'Python',dtype= object).dtype)

[['Python']
 ['Python']
 ['Python']
 ['Python']
 ['Python']
 ['Python']]
object


#### 11. एक ऐसे array का sum निकालो जो np.full((3, 3), 10) से बना हो।

In [134]:
print(np.full((3,3),10).sum())

90


#### 12 . एक Boolean array बनाओ जिसमें shape (3, 3) हो और सभी values True हों।

In [136]:
print(np.full((3,3),1,dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 5 . Creating array using np.empty()

#### 1. एक 1D empty array बनाओ जिसमें 5 elements हों।

In [139]:
print(np.empty(5))

[0.00000000e+000 1.18607568e-311 1.18607568e-311 1.18607568e-311
 0.00000000e+000]


#### 2. एक 2×3 shape की empty array बनाओ।

In [140]:
print(np.empty((2,3)))

[[0. 0. 0.]
 [1. 1. 1.]]


#### 3. एक empty array बनाओ जिसमें सभी values integer dtype में हों।

In [141]:
print(np.empty(5,dtype=int))

[            0 2400643907456 2400643908736 2400643908336             0]


#### 4. एक empty array बनाओ जिसमें dtype = 'bool' हो।

In [142]:
print(np.empty((2,3),dtype=bool))

[[False False False]
 [ True  True  True]]


#### 5. एक empty array बनाओ और फिर उसमें manually values assign करो।

In [147]:
e1 = np.empty(5)
print(e1)
e1[0]=10
e1[1]=20
e1[2]=30
e1[3]=40
e1[4]=50
print("After mannually asssining values : ")
print(e1)

[10. 20. 30. 40. 50.]
After mannually asssining values : 
[10. 20. 30. 40. 50.]


#### 6. एक 5×2 empty matrix बनाओ और उसका reshape(2,5) करो।

In [148]:
print(np.empty((5,2)).reshape(2,5))

[[0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.55555556 0.66666667 0.77777778 0.88888889 1.        ]]


#### 7. एक empty array बनाओ और उसमें सभी elements को 1 से multiply करो।

In [150]:
print(np.empty((2,3))*1)

[[0. 0. 0.]
 [1. 1. 1.]]


### 8 . एक empty array बनाओ और फिर उसमें सभी values को 0 से fill करो (fill() method)

In [151]:
a = np.empty((2, 3))
a.fill(0)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


#### 9. एक empty array बनाओ जिसमें shape (10,) हो और उसे np.sort() करो।

In [152]:
print(np.sort(np.empty(10)))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 10. एक empty array बनाओ और उसमें values manually input लेकर भरो (e.g., loop से)।

In [156]:
em1 =np.empty((2,3))
for i in range(2):
    for j in range(3):
        em1[i][j] = input("Enter value : ")
print(em1)

Enter value :  12
Enter value :  32
Enter value :  23
Enter value :  56
Enter value :  77
Enter value :  21


[[12. 32. 23.]
 [56. 77. 21.]]


#### 11. एक empty array बनाओ और उसमें np.arange() से values भर दो।

In [160]:
print(np.empty(np.arange(10)))


a = np.empty(6)
a[:] = np.arange(6)
print(a)

[]
[0. 1. 2. 3. 4. 5.]


#### 12. एक empty boolean array बनाओ और उसे all True से fill करो।

In [161]:

a = np.empty((3, 3), dtype=bool)
a.fill(True)
print(a)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 6. creating array using np.eye() and np.identity()

#### 1. Create a 3×3 identity matrix using np.identity().

In [2]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 2. Create a 3×4 matrix using np.eye() with default diagonal (k=0).

In [3]:
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


#### 3. Create a 4×4 identity matrix using np.eye().

In [4]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 4. Create a 5×5 matrix using np.identity() with integer data type.

In [5]:
print(np.identity(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


#### 5. Create a 6×6 identity matrix of float values using np.eye()

In [7]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#### 6. Create a 4×4 matrix with diagonal shifted one above the main diagonal using np.eye(k=2).

In [9]:
print(np.eye(4,k=2))

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 7. Create a 5×5 matrix with diagonal shifted two below the main diagonal using np.eye(k=-2).

In [10]:
print(np.eye(5, k=-2))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


####  8. Create a 3×6 matrix using np.eye() and shift diagonal to k=2.

In [11]:
print(np.eye(3,6,2))

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


####  9. Create a 4×4 matrix with dtype=int using np.eye().

In [13]:
print(np.eye(4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### 10 . Create a 5×5 matrix using np.eye() and fill the main diagonal with 7 instead of 1. 

In [17]:
print(np.eye(5) * 7)

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]


####  11. Add two identity matrices of size 3×3 (created using np.identity()).

In [15]:
i1 = np.identity(3)
i2 = np.identity(3)
i3 = i1+i2
print( "First : \n ",i1)
print("second : \n ",i2)
print("Sum = \n",i3)

First : 
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
second : 
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sum = 
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


####  12. Multiply a np.identity(4) matrix by 10.

In [16]:
print(np.identity(4)*4)

[[4. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]


#### 13. Create a 4×4 matrix using np.eye() and convert all 1s to True, 0s to False.

In [18]:
print(np.eye(4,dtype=bool))

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


### 14. Create a matrix of shape (4, 4) where the diagonal elements form an arithmetic sequence [2, 4, 6, 8] using broadcasting

In [19]:
e11 = np.zeros((4, 4), dtype=int)
e11[np.arange(4), np.arange(4)] = [2, 4, 6, 8]
print(e11)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


#### 15. Create a matrix where the main diagonal is 1, upper diagonal is 2, and lower diagonal is 3.



In [20]:
ee1 = np.zeros((5, 5), dtype=int)
ee1[np.arange(5), np.arange(5)] = 1             # main
ee1[np.arange(4), np.arange(1, 5)] = 2           # upper
ee1[np.arange(1, 5), np.arange(4)] = 3           # lower
print(ee1)

[[1 2 0 0 0]
 [3 1 2 0 0]
 [0 3 1 2 0]
 [0 0 3 1 2]
 [0 0 0 3 1]]


# Creating array using np.random module 

#### Generate 1 random float using np.random.rand().

In [52]:
print(np.random.rand())

0.18024085901224407


#### Generate a 1D array of 5 random floats between 0 and 1.

In [53]:
print(np.random.rand(5))

[0.69061153 0.81402133 0.84848339 0.42139648 0.49191813]


#### Generate a 3×3 array of random floats using rand().

In [50]:
print(np.random.rand(3,3))

[[0.00260284 0.42718859 0.46741213]
 [0.80471559 0.63794714 0.87002599]
 [0.26443986 0.92032001 0.67403901]]


#### Generate 5 random integers from 1 to 10 using randint().

In [28]:
print(np.random.randint(1,10+1,5))

[2 3 7 8 1]


#### Generate a 2×4 array of random integers between 50 and 100.

In [32]:
print(np.random.randint(50,100,(2,4)))

[[65 94 85 70]
 [88 68 99 70]]


####  Pick 1 random value from the list [10, 20, 30, 40] using choice().

In [34]:
print(np.random.choice([10,20,30,40],size=1))

[30]


#### Generate a 5×2 array using randn() and observe positive and negative values

In [36]:
print(np.random.randn(5,2))

[[ 1.87026886 -0.70613021]
 [-0.62540609  0.64875485]
 [ 0.54855141 -0.80066543]
 [-0.87448629 -0.42696886]
 [-0.26358977 -0.42621324]]


#### Generate a random 4×4 matrix of integers (1–9) and count how many values >5.

In [39]:
r1 = np.random.randint(1,9,(4,4))
r2 = r1[r1>5]
print(r1)
print("Total values : ",r2.size)

 

[[4 7 8 4]
 [1 1 2 2]
 [1 8 5 6]
 [4 7 5 1]]
Total values :  5


#### Generate 3 random samples with replacement = false from list [1, 2, 3, 4].

In [46]:
print(np.random.choice([1,2,3,4],3,replace=False))
print("\nSecond :")
print(np.random.choice([1,2,3,4],3))

[3 2 1]

Second :
[4 1 3]


#### Generate 6 random floats and sort them in ascending order.

In [48]:
print(np.sort(np.random.rand(6)))

[0.00547079 0.30300282 0.31058992 0.42104359 0.7750157  0.91006362]


 #  8. Creating array using np.reshape()

#### Convert a 1D array of 6 elements into a 2D array of shape (2, 3).

In [55]:
x1 = np.array(range(6))
print("1D array : ")
print(x1)
x2 = np.reshape(x1,(2,3))
print("\n After shapeing array ")
print(x2)

1D array : 
[0 1 2 3 4 5]

 After shapeing array 
[[0 1 2]
 [3 4 5]]


#### Convert a list [1,2,3,4,5,6,7,8] into a 2D NumPy array of shape (4, 2).

In [57]:
x3 = np.array( [1,2,3,4,5,6,7,8] ).reshape(4,2)
print(x3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Create a 3×3 array using arange() and reshape.


In [59]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Generate a 1D array of 12 numbers and reshape into (3, 4).

In [60]:
print(np.ones(12).reshape(3,4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Create a 1D array with 9 elements and reshape into 3x3.

In [62]:
print(np.full(9,4).reshape(3,3))

[[4 4 4]
 [4 4 4]
 [4 4 4]]


#### Create a 3x2x2 array using reshape() from np.arange(12).


In [63]:
print(np.arange(12).reshape(3,2,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


#### Convert a 2D array of shape (4, 3) into shape (2, 6).

In [65]:
print(np.full((4,3),5).reshape(2,6))

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]]


#### Reshape a 1D array of 24 numbers into 3D shape (2, 3, 4)

In [66]:
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


####  Flatten a 2D array of shape (3, 3) back into 1D using .reshape(-1).

In [67]:
print(np.full((3,3),2))
print(np.full((3,3),2).reshape(-1))

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[2 2 2 2 2 2 2 2 2]
