## NumPy Array Creation Practice Assignments

In [2]:
import numpy as np

#### 1 . Create an array of first 50 natural numbers without directly writing numbers.

In [3]:
a1 = np.arange(1,51)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### 2. Generate all even numbers between 1 and 200 using only NumPy methods.

In [4]:
a2 = np.arange(2,201,2)
a2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

#### 3. Create an array of odd numbers from 1 to 199 without using manual list

In [5]:
a3 = np.arange(1,200,2)
a3

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

#### 4. Generate reverse sequence from 100 to 1 using NumPy only

In [6]:
a4 =np.arange(100,0,-1)
a4

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

#### 5. Create an array where each value is multiplication of 3 (0 to 30 multiples)

In [7]:
a5 = np.arange(3,31,3)
a5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

#### 6. Create a sequence: 1, 4, 7, 10, 13 ... up to 30 elements.

In [8]:
a6 = np.arange(1,30,3)
a6

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

#### 7. Create sequence: 2, 6, 12, 20, 30 ... (pattern-based logic).

In [9]:
a7 = np.arange(1,11)
a7 = a7*(a7+1)
a7

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

#### 8. Generate square numbers from 1 to 100 using NumPy only.

In [10]:
a8 = np.arange(1,101)
a8 = a8**2
a8

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

#### 9. Generate cube numbers from 1 to 50

In [11]:
a9 = np.arange(1,51)**3
a9

array([     1,      8,     27,     64,    125,    216,    343,    512,
          729,   1000,   1331,   1728,   2197,   2744,   3375,   4096,
         4913,   5832,   6859,   8000,   9261,  10648,  12167,  13824,
        15625,  17576,  19683,  21952,  24389,  27000,  29791,  32768,
        35937,  39304,  42875,  46656,  50653,  54872,  59319,  64000,
        68921,  74088,  79507,  85184,  91125,  97336, 103823, 110592,
       117649, 125000])

#### 10. Create Fibonacci-like first 20 values (array form).

In [12]:
fib = np.empty(20, dtype=int)
fib[0] = 0
fib[1] = 1
for i in range(2, 20):
    fib[i] = fib[i-1] + fib[i-2]

print(fib)

[   0    1    1    2    3    5    8   13   21   34   55   89  144  233
  377  610  987 1597 2584 4181]


#### 11. Create sequence 1–100 and replace even numbers with 0.

In [14]:
a10 = np.arange(1,101)
for i in range(1,len(a10),2):
    a10[i]=0
a10
    

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0, 51,
        0, 53,  0, 55,  0, 57,  0, 59,  0, 61,  0, 63,  0, 65,  0, 67,  0,
       69,  0, 71,  0, 73,  0, 75,  0, 77,  0, 79,  0, 81,  0, 83,  0, 85,
        0, 87,  0, 89,  0, 91,  0, 93,  0, 95,  0, 97,  0, 99,  0])

#### 12 . Create sequence 1–50 and replace odd numbers with -1.

In [15]:
a12 = np.arange(1,50)
for i in range(0,len(a12),2):
    a12[i]=-1
a12

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1,
       18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34,
       -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1])

#### 13. Create an array where each element is equal to its index value (0 to n).

In [16]:
n = int(input("Enter a number : "))
a13 = np.arange(n)
a13

Enter a number :  10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 14. Create an array where each element is the square of its index

In [17]:
a14 = np.arange(10)**2
a14

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### 15. Create an array where each element is cube of its index.

In [19]:
a15 = np.arange(10)**3
a15

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### 16. Create an array where each element = (index × 2) + 1.

In [20]:
a16 = np.arange(10)*2+1
a16

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 17. Create an array where each element = index % 3.

In [21]:
a17 = np.arange(10)%3
a17

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

#### 18. Create an array of size 50 where even index positions contain 0 and odd index positions contain 1.

In [31]:
a18 = np.arange(1,51)
a18[a18%2==0]=0
a18[a18%2!=0]=1
a18

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0])

#### 19. Create an array where values are 1 if index is divisible by 3, else 0.

In [55]:
a19 = np.arange(30)
for i in  a19:
    if i%3==0:
        a19[i]=1
    else :
        a19[i]=0
a19[0]=0
a19

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0])

#### 20 . Create an array where elements are -1 for even indices and +1 for odd indices.

In [57]:
a20 = np.full(10,1)
for i in range(len(a20)):
    if i%2==0:
        a20[i]=-1
a20

array([-1,  1, -1,  1, -1,  1, -1,  1, -1,  1])

#### 21 . Create an array where numbers divisible by 5 are kept, others replaced with 0.

In [58]:
a21 = np.arange(16)
for i in range(len(a21)):
    if i % 5 !=0:
        a21[i]=0
a21

array([ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0, 10,  0,  0,  0,  0, 15])

#### 22 . Create an array where values greater than 50 are 1, else 0.

In [61]:
np.random.seed(42)
a22 = np.random.randint(10,100,15)
print(a22)
ind_data = a22>50
a22[ind_data]=1
a22[~ind_data]=0
print(a22)
        

[61 24 81 70 30 92 96 84 84 97 33 12 31 62 11]
[1 0 1 1 0 1 1 1 1 1 0 0 0 1 0]


## REVERSAL & ORDER LOGIC

#### 23. Create an array from 1 to 100 and reverse it.

In [62]:
a23 = np.arange(1,101)[::-1]
a23

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

#### 24. Create reverse array of even numbers only.

In [82]:
a24 = np.arange(1,50)[1::2][::-1]
a24

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10,  8,  6,  4,  2])

In [85]:
inc_array = np.arange(1,6)
dec_array = np.arange(4,0,-1)
a25 = np.concatenate((inc_array,dec_array))
a25

array([1, 2, 3, 4, 5, 4, 3, 2, 1])

#### 25. Create descending multiples of 10 from 100 to 0.

In [86]:
a25 = np.arange(100,0,-10)
a25

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

#### 26. Create array sorted in descending order without using sort().

In [90]:
np.random.seed(42)
a26 = np.random.randint(1,100,15)
n = a26.size
print(a26)
for i in range(n-1):
    k=i
    for j in range(i+1,n):
        if a26[k] >a26[j]:
            k = j
    temp = a26[k]
    a26[k]=a26[i]
    a26[i]= temp

print(a26)
    

[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53]
[ 3 15 21 22 24 52 53 61 72 75 75 83 87 88 93]


#### LOGIC 

### 27.Create array of prime numbers up to 200.

In [91]:
prime_numbers = []
for num in range(2,201):
    Is_prime = True 
    for i in range(2,int(num//2)+1):
        if num %i ==0:
            Is_prime = False
            break
    if Is_prime :
        prime_numbers.append(num)
a27 = np.array(prime_numbers)
a27

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199])

#### 28. Create array of numbers divisible by both 3 and 7.

In [92]:
a28 = np.arange(50)
a28=a28[a28%3==0 | a28%7 ==0]
a28

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [97]:
a28=a28[(a28%3==0 )| (a28%7 ==0)]
a28

array([ 0,  3,  6,  7,  9, 12, 14, 15, 18, 21, 24, 27, 28, 30, 33, 35, 36,
       39, 42, 45, 48, 49])

#### 29. Create array of numbers divisible by 4 but not by 6.

In [101]:
a29 = np.random.randint(10,100,30)
a29 = a29[(a29%4==0)&(a29%6!=0)]
a29


array([20, 44, 44, 16, 32, 44, 56], dtype=int32)

#### 30. Create array of numbers ending with digit 5.

In [102]:
a30 = np.arange(50)
a30 = a30[a30%10==5]
a30

array([ 5, 15, 25, 35, 45])