# NumPy Missing Values Operations

### FUNCTION 1: np.isnan()
Returns boolean array where NaN values are True.

In [1]:
import numpy as np

# Employee salaries with missing values
salaries = np.array([45000, np.nan, 52000, 38000, np.nan, 61000, 49000, np.nan, 55000, 47000])
print("Salaries:", salaries)

Salaries: [45000.    nan 52000. 38000.    nan 61000. 49000.    nan 55000. 47000.]


#### Q1. Find all indices where salary is missing (NaN) using np.isnan().



In [2]:
np.isnan(salaries)

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [4]:
np.where(np.isnan(salaries))[0]

array([1, 4, 7])

#### Q2. Count how many missing values are in the array.



In [6]:
np.where(np.isnan(salaries))[0].size

3

#### Q3. Extract all non-missing salaries into a new array.



In [9]:
array2 = np.extract(~np.isnan(salaries),salaries)
array2

array([45000., 52000., 38000., 61000., 49000., 55000., 47000.])

In [11]:
arr3 = salaries[~np.isnan(salaries)]
arr3

array([45000., 52000., 38000., 61000., 49000., 55000., 47000.])

#### Q4. Replace all missing salaries with the median of non-missing values.



In [14]:
arr4 = salaries.copy()
arr4

array([45000.,    nan, 52000., 38000.,    nan, 61000., 49000.,    nan,
       55000., 47000.])

In [16]:
median_data = np.nanmedian(arr4)
median_data

np.float64(49000.0)

In [17]:
arr4[np.isnan(arr4)] = median_data
arr4

array([45000., 49000., 52000., 38000., 49000., 61000., 49000., 49000.,
       55000., 47000.])

#### Q5. Check if any missing values exist in the array using np.isnan()



In [18]:
np.isnan(salaries).any()

np.True_

In [19]:
np.isnan(arr4).any()

np.False_

## FUNCTION 2: np.nan_to_num()
Replaces NaN with 0 and inf with large numbers

In [20]:
readings = np.array([25.5, np.nan, 30.2, np.inf, 28.7, np.nan, -np.inf, 26.3, 29.1, np.nan])
print("Readings:", readings)

Readings: [25.5  nan 30.2  inf 28.7  nan -inf 26.3 29.1  nan]


#### Q6. Replace all NaN values with 0 using np.nan_to_num().

In [22]:
readings2 = readings.copy()
readings2

array([25.5,  nan, 30.2,  inf, 28.7,  nan, -inf, 26.3, 29.1,  nan])

In [26]:
readings2 = np.nan_to_num(readings2,nan=0)
readings2.astype(int)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14160\2645280142.py:2: RuntimeWarning: invalid value encountered in cast
  readings2.astype(int)


array([                  25,                    0,                   30,
       -9223372036854775808,                   28,                    0,
       -9223372036854775808,                   26,                   29,
                          0])

#### Q7. Replace NaN with 100 and inf with 999 using custom parameters.

In [27]:
readings3 = readings.copy()
readings3

array([25.5,  nan, 30.2,  inf, 28.7,  nan, -inf, 26.3, 29.1,  nan])

In [28]:
readings3 = np.nan_to_num(readings3,nan= 100, posinf= 999, neginf= -999)
readings3

array([  25.5,  100. ,   30.2,  999. ,   28.7,  100. , -999. ,   26.3,
         29.1,  100. ])

#### Q8. Replace only NaN (keep inf as is) by setting posinf=None, neginf=None.

In [30]:
readings4 = readings.copy()
readings4

array([25.5,  nan, 30.2,  inf, 28.7,  nan, -inf, 26.3, 29.1,  nan])

In [33]:
readings4 = np.nan_to_num(readings4,nan= 100, posinf= None, neginf= None)
readings4

array([ 2.55000000e+001,  1.00000000e+002,  3.02000000e+001,
        1.79769313e+308,  2.87000000e+001,  1.00000000e+002,
       -1.79769313e+308,  2.63000000e+001,  2.91000000e+001,
        1.00000000e+002])

In [34]:
np.set_printoptions(suppress=True, precision=2)

In [35]:
readings4

array([ 2.55e+001,  1.00e+002,  3.02e+001,  1.80e+308,  2.87e+001,
        1.00e+002, -1.80e+308,  2.63e+001,  2.91e+001,  1.00e+002])

#### Q9. Compare original array vs nan_to_num result.

In [36]:
print("\nComparison (Original vs Converted):")
for o, c in zip(readings, readings3):
    print(f"{o}  -->  {c}")


Comparison (Original vs Converted):
25.5  -->  25.5
nan  -->  100.0
30.2  -->  30.2
inf  -->  999.0
28.7  -->  28.7
nan  -->  100.0
-inf  -->  -999.0
26.3  -->  26.3
29.1  -->  29.1
nan  -->  100.0


In [37]:
print("\nComparison (Original vs Converted):")
for o, c in zip(readings, readings4):
    print(f"{o}  -->  {c}")


Comparison (Original vs Converted):
25.5  -->  25.5
nan  -->  100.0
30.2  -->  30.2
inf  -->  1.7976931348623157e+308
28.7  -->  28.7
nan  -->  100.0
-inf  -->  -1.7976931348623157e+308
26.3  -->  26.3
29.1  -->  29.1
nan  -->  100.0


#### Q10. Use np.nan_to_num() on 2D array 

In [39]:
read2d = readings.reshape(-1,2)
read2d

array([[25.5,  nan],
       [30.2,  inf],
       [28.7,  nan],
       [-inf, 26.3],
       [29.1,  nan]])

In [40]:
np.nan_to_num(read2d,nan=1)

array([[ 2.55e+001,  1.00e+000],
       [ 3.02e+001,  1.80e+308],
       [ 2.87e+001,  1.00e+000],
       [-1.80e+308,  2.63e+001],
       [ 2.91e+001,  1.00e+000]])

## FUNCTION 3: np.nanmean(), np.nanmedian(), np.nanstd()
Statistical operations ignoring NaN.

In [41]:
test_scores = np.array([
    [85, np.nan, 92, 78, 88],
    [np.nan, 91, 87, np.nan, 95],
    [76, 84, np.nan, 89, 82],
    [93, 88, 91, 86, np.nan],
    [np.nan, 79, 85, 92, 88]
])
print("Test scores matrix:\n", test_scores)

Test scores matrix:
 [[85. nan 92. 78. 88.]
 [nan 91. 87. nan 95.]
 [76. 84. nan 89. 82.]
 [93. 88. 91. 86. nan]
 [nan 79. 85. 92. 88.]]


#### Q11. Calculate mean of each column ignoring NaN .



In [47]:
print(np.nanmean(test_scores ,axis =0))


[84.67 85.5  88.75 86.25 88.25]


#### Q12. Calculate median of each row ignoring NaN 



In [49]:
median_result = np.nanmedian(test_scores,axis =1)
print(median_result)

[86.5 91.  83.  89.5 86.5]


#### Q13. Calculate standard deviation of entire array ignoring NaN.



In [50]:
print(np.nanstd(test_scores))

5.115291290449605


#### Q14. Find which column has highest mean (ignoring NaN).



In [53]:
mean_res = np.nanmean(test_scores,axis=0)
print("Column No :",np.argmax(mean_res)+1)
print("mean value : ",np.max(mean_res))

Column No : 3
mean value :  88.75


#### Q15. Calculate variance using np.nanvar() ignoring missing values.



In [55]:
np.nanvar(test_scores,axis=0)


array([48.22, 20.25,  8.19, 27.19, 21.19])

In [57]:
np.nanvar(test_scores,axis=1)


array([26.19, 10.67, 21.69,  7.25, 22.5 ])

In [58]:
 np.nanvar(test_scores)


np.float64(26.16620498614958)

## FUNCTION 4: np.isinf()
Returns boolean array where infinite values are True

In [59]:
sensor_data = np.array([10, 20, np.inf, 30, -np.inf, 25, np.inf, 35, 40, -np.inf])
print("Sensor data:", sensor_data)

Sensor data: [ 10.  20.  inf  30. -inf  25.  inf  35.  40. -inf]


#### Q16. Find all indices where value is infinite using np.isinf().



In [61]:
np.isinf(sensor_data)

array([False, False,  True, False,  True, False,  True, False, False,
        True])

In [63]:
np.where(np.isinf(sensor_data))[0]

array([2, 4, 6, 9])

#### Q17. Replace all positive infinity with 999 and negative infinity with -999.



In [70]:
np.nan_to_num(sensor_data,posinf=999, neginf=-999)

array([  10.,   20.,  999.,   30., -999.,   25.,  999.,   35.,   40.,
       -999.])

#### Q18. Count how many infinite values exist in array.



In [71]:
sensor_data[np.isinf(sensor_data)].size

4

#### Q19. Remove all infinite values (create array with only finite values).



In [72]:
new_array = sensor_data[~np.isinf(sensor_data)].copy()
new_array

array([10., 20., 30., 25., 35., 40.])

#### Q20. Check if any infinite values exist using np.isinf().any().



In [73]:
np.isinf(sensor_data).any()

np.True_

In [74]:
np.isinf(new_array).any()

np.False_

### FUNCTION 5: np.isfinite()
Returns boolean array where values are finite (not NaN, not inf).



In [93]:
mixed = np.array([5, np.nan, 10, np.inf, 15, -np.inf, 20, np.nan, 25, 30])
print("Mixed array:", mixed)

Mixed array: [  5.  nan  10.  inf  15. -inf  20.  nan  25.  30.]


#### Q21. Find all finite values using np.isfinite().



In [94]:
np.isfinite(mixed)

array([ True, False,  True, False,  True, False,  True, False,  True,
        True])

In [95]:
mixed[np.isfinite(mixed)]

array([ 5., 10., 15., 20., 25., 30.])

#### Q22. Count how many finite values are in array.



In [96]:
mixed[np.isfinite(mixed)].size

6

#### Q23. Extract all finite values into new array.



In [97]:
new_mixed_data = mixed[np.isfinite(mixed)]

In [98]:
new_mixed_data

array([ 5., 10., 15., 20., 25., 30.])

In [99]:
mixed

array([  5.,  nan,  10.,  inf,  15., -inf,  20.,  nan,  25.,  30.])

#### Q24. Replace all non-finite values (NaN and inf) with 0.

In [103]:
mixed2= mixed.copy()
mixed2

array([  5.,  nan,  10.,  inf,  15., -inf,  20.,  nan,  25.,  30.])

In [104]:
mixed2[~np.isfinite(mixed2)] =0

In [105]:
mixed2

array([ 5.,  0., 10.,  0., 15.,  0., 20.,  0., 25., 30.])

#### Q25. Calculate sum of only finite values.

In [106]:
np.nansum(mixed)

C:\Users\Omkar Yallurkar\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


np.float64(nan)

In [108]:
print(mixed[np.isfinite(mixed)].sum())

105.0


### FUNCTION 6: np.nansum(), np.nanprod(), np.nancumsum()
Sum, product, cumulative sum ignoring NaN.

In [109]:
quarterly_sales = np.array([
    [1000, np.nan, 1200, 1100],
    [np.nan, 1300, 1400, np.nan],
    [1500, 1600, np.nan, 1700],
    [np.nan, np.nan, 1800, 1900]
])
print("Quarterly sales (4 quarters, 4 regions):\n", quarterly_sales)

Quarterly sales (4 quarters, 4 regions):
 [[1000.   nan 1200. 1100.]
 [  nan 1300. 1400.   nan]
 [1500. 1600.   nan 1700.]
 [  nan   nan 1800. 1900.]]


#### Q26. Calculate total sales per region ignoring NaN 

In [111]:
np.nansum(quarterly_sales)

np.float64(14500.0)

In [112]:
np.nansum(quarterly_sales,axis =1)

array([3300., 2700., 4800., 3700.])

#### Q27. Calculate total sales per quarter ignoring NaN 


In [113]:
np.nansum(quarterly_sales,axis =0)

array([2500., 2900., 4400., 4700.])

#### Q28. Calculate cumulative sum along rows ignoring NaN

In [115]:
np.nancumsum(quarterly_sales,axis=0)

array([[1000.,    0., 1200., 1100.],
       [1000., 1300., 2600., 1100.],
       [2500., 2900., 2600., 2800.],
       [2500., 2900., 4400., 4700.]])

In [116]:
np.nancumsum(quarterly_sales,axis=1)

array([[1000., 1000., 2200., 3300.],
       [   0., 1300., 2700., 2700.],
       [1500., 3100., 3100., 4800.],
       [   0.,    0., 1800., 3700.]])

In [117]:
np.nancumsum(quarterly_sales)

array([ 1000.,  1000.,  2200.,  3300.,  3300.,  4600.,  6000.,  6000.,
        7500.,  9100.,  9100., 10800., 10800., 10800., 12600., 14500.])

#### Q29. Calculate product of values ignoring NaN

In [118]:
np.nanprod(quarterly_sales)

np.float64(3.352212864e+31)

In [119]:
np.nanprod(quarterly_sales,axis=0)

array([1.50e+06, 2.08e+06, 3.02e+09, 3.55e+09])

In [120]:
np.nanprod(quarterly_sales,axis=1)

array([1.32e+09, 1.82e+06, 4.08e+09, 3.42e+06])

#### Q30. Find which region has highest total sales (ignoring missing quarters).

In [122]:
print(np.argmax(np.nansum(quarterly_sales,axis=0))+1)

4


### FUNCTION 7: np.nanmin(), np.nanmax()
Minimum and maximum ignoring NaN.

In [2]:
temperatures = np.array([
    [23.5, 24.1, np.nan, 22.8, 25.0],
    [np.nan, 26.3, 27.1, np.nan, 24.5],
    [21.2, 22.5, 23.8, np.nan, 24.2],
    [25.5, np.nan, 26.0, 27.2, 26.8]
])
print("Temperatures (4 cities, 5 days):\n", temperatures)

Temperatures (4 cities, 5 days):
 [[23.5 24.1  nan 22.8 25. ]
 [ nan 26.3 27.1  nan 24.5]
 [21.2 22.5 23.8  nan 24.2]
 [25.5  nan 26.  27.2 26.8]]


#### Q31. Find minimum temperature in each city ignoring NaN 

In [3]:
np.nanmin(temperatures,axis=1)

array([22.8, 24.5, 21.2, 25.5])

#### Q32. Find maximum temperature in each day ignoring NaN 


In [4]:
np.nanmax(temperatures,axis=0)

array([25.5, 26.3, 27.1, 27.2, 26.8])

#### Q33. Find overall minimum and maximum temperature ignoring NaN.

In [5]:
print("Minimum Temp per City : ",np.nanmin(temperatures,axis=1))
print("Maximum  Temp per City : ",np.nanmax(temperatures,axis=1))

Minimum Temp per City :  [22.8 24.5 21.2 25.5]
Maximum  Temp per City :  [25.  27.1 24.2 27.2]


#### Q34. Find which city has highest maximum temperature.

In [6]:
print("City No : ",np.argmax(np.nanmax(temperatures,axis=1))+1)

City No :  4


#### Q35. Find which day had lowest minimum temperature.

In [7]:
print("Day : ",np.argmin(np.nanmin(temperatures,axis=0))+1)

Day :  1


## FUNCTION 8: np.argmin() / np.argmax() with NaN handling

In [8]:
response_times = np.array([120, np.nan, 95, 150, np.nan, 80, 200, 110, np.nan, 130])
print("Response times (ms):", response_times)

Response times (ms): [120.  nan  95. 150.  nan  80. 200. 110.  nan 130.]


#### Q36. Find index of minimum value ignoring NaN

In [9]:
print(np.nanargmin(response_times))

5


#### Q37. Find index of maximum value ignoring NaN 

In [10]:
print(np.nanargmax(response_times))

6


#### Q38. What happens if you use normal np.argmin() on array with NaN?

In [11]:
print(np.argmin(response_times))

1


In [12]:
print(np.nanargmin(response_times))

5


#### Q39. Find position of 2nd smallest value ignoring NaN.

In [22]:
duplicate_data = response_times.copy()
duplicate_data

array([120.,  nan,  95., 150.,  nan,  80., 200., 110.,  nan, 130.])

In [26]:
duplicate_data[np.nanargmin(duplicate_data)] = None
print("2ND smallest Value position : ",np.nanargmin(duplicate_data))


2ND smallest Value position :  2


In [27]:
duplicate_data

array([120.,  nan,  95., 150.,  nan,  nan, 200., 110.,  nan, 130.])

#### Q40. Find index of value closest to 100 ignoring NaN.

In [30]:
response_times

array([120.,  nan,  95., 150.,  nan,  80., 200., 110.,  nan, 130.])

In [31]:
idx = np.nanargmin(response_times-100)
idx

np.int64(5)

In [33]:
idx = np.nanargmin(np.abs(response_times-100)) # correct
idx

np.int64(2)

### REAL-WORLD SCENARIO 1: Customer Purchase Data

In [40]:
np.random.seed(42)

# 100 customers × 12 months
purchases = np.random.randint(0, 1000, size=(100, 12)).astype(float)

# Randomly insert 15% missing values
mask = np.random.random(purchases.shape) < 0.15
purchases[mask] = np.nan

print("Purchases shape:", purchases.shape)
print("First 5 customers, first 6 months:\n", purchases[:5, :6])
print(f"Missing values: {np.isnan(purchases).sum()} out of {purchases.size}")

Purchases shape: (100, 12)
First 5 customers, first 6 months:
 [[102.  nan 860.  nan 106.  71.]
 [ nan  nan  nan 372.  99. 871.]
 [491. 413. 805.  nan 191. 955.]
 [747. 856. 560. 474.  58. 510.]
 [ nan 686. 957. 562. 875.  nan]]
Missing values: 178 out of 1200


### Q41. Calculate average monthly purchase per customer ignoring NaN.

In [41]:
np.nanmean(purchases,axis=1)[:5]

array([327.4       , 397.71428571, 394.18181818, 583.83333333,
       663.57142857])

### Q42. Replace missing values with each customer's mean (use broadcasting).

In [42]:
purchases2 = purchases.copy()
purchases2[:5,:6]

array([[102.,  nan, 860.,  nan, 106.,  71.],
       [ nan,  nan,  nan, 372.,  99., 871.],
       [491., 413., 805.,  nan, 191., 955.],
       [747., 856., 560., 474.,  58., 510.],
       [ nan, 686., 957., 562., 875.,  nan]])

In [46]:
cust_mean = np.nanmean(purchases2,axis=1)
purchases2[np.isnan(purchases2)] = cust_mean
purchases2[:5,:5]

ValueError: NumPy boolean array indexing assignment cannot assign 100 input values to the 178 output values where the mask is true

In [50]:
indexs = np.where(np.isnan(purchases2))
purchases2[indexs] = cust_mean[indexs[1]]
purchases2[:6,:5]

array([[102.        , 397.71428571, 860.        , 583.83333333,
        106.        ],
       [327.4       , 397.71428571, 394.18181818, 372.        ,
         99.        ],
       [491.        , 413.        , 805.        , 583.83333333,
        191.        ],
       [747.        , 856.        , 560.        , 474.        ,
         58.        ],
       [327.4       , 686.        , 957.        , 562.        ,
        875.        ],
       [646.        ,  20.        , 840.        , 166.        ,
        663.57142857]])

### Q43. Find customers with more than 3 missing months.

In [54]:
miss_count = np.sum(np.isnan(purchases),axis=1)
customers = np.where(miss_count > 3)[0]
print(customers)

[ 1  4  7 15 31 33 36 42 46 55 95 98]


### Q44. Calculate total yearly purchase for each customer (replace NaN with 0 first).

In [56]:
purchases3 = purchases.copy()
purchases3

array([[102.,  nan, 860., ..., 121., 466., 214.],
       [ nan,  nan,  nan, ..., 308.,  nan, 343.],
       [491., 413., 805., ..., 313.,  21., 252.],
       ...,
       [ 60., 633.,  50., ..., 828., 533.,  nan],
       [837., 512.,  nan, ...,  77., 729., 812.],
       [922.,  72., 793., ..., 349.,  nan, 830.]])

In [57]:
purchases3[np.isnan(purchases3)] = 0

In [58]:
purchases3

array([[102.,   0., 860., ..., 121., 466., 214.],
       [  0.,   0.,   0., ..., 308.,   0., 343.],
       [491., 413., 805., ..., 313.,  21., 252.],
       ...,
       [ 60., 633.,  50., ..., 828., 533.,   0.],
       [837., 512.,   0., ...,  77., 729., 812.],
       [922.,  72., 793., ..., 349.,   0., 830.]])

In [59]:
np.sum(purchases3,axis=1)

array([3274., 2784., 4336., 7006., 4645., 4349., 5577., 3425., 6394.,
       6110., 4823., 5093., 3636., 5846., 7152., 3663., 6059., 4668.,
       6541., 5450., 6404., 6389., 5802., 3460., 6367., 4450., 5841.,
       5361., 6096., 7691., 5691., 2390., 6242., 4089., 6531., 6064.,
       3417., 5533., 3566., 2915., 5575., 5485., 5456., 5442., 6765.,
       5644., 3409., 6051., 5606., 5950., 5848., 6100., 6320., 5559.,
       4600., 4329., 5059., 6681., 7362., 4141., 6818., 4722., 7111.,
       3867., 6410., 4300., 4856., 4149., 2598., 6231., 5381., 4227.,
       4796., 4675., 5963., 5257., 3751., 3760., 6206., 5092., 4621.,
       8006., 5560., 3615., 5371., 4681., 5452., 4752., 3903., 5440.,
       4921., 5913., 6113., 4914., 4606., 4364., 5029., 5047., 3880.,
       3831.])

In [60]:
#also
np.nansum(purchases,axis=1)

array([3274., 2784., 4336., 7006., 4645., 4349., 5577., 3425., 6394.,
       6110., 4823., 5093., 3636., 5846., 7152., 3663., 6059., 4668.,
       6541., 5450., 6404., 6389., 5802., 3460., 6367., 4450., 5841.,
       5361., 6096., 7691., 5691., 2390., 6242., 4089., 6531., 6064.,
       3417., 5533., 3566., 2915., 5575., 5485., 5456., 5442., 6765.,
       5644., 3409., 6051., 5606., 5950., 5848., 6100., 6320., 5559.,
       4600., 4329., 5059., 6681., 7362., 4141., 6818., 4722., 7111.,
       3867., 6410., 4300., 4856., 4149., 2598., 6231., 5381., 4227.,
       4796., 4675., 5963., 5257., 3751., 3760., 6206., 5092., 4621.,
       8006., 5560., 3615., 5371., 4681., 5452., 4752., 3903., 5440.,
       4921., 5913., 6113., 4914., 4606., 4364., 5029., 5047., 3880.,
       3831.])

### Q45. Find which month has highest total sales (after filling NaN with median).

In [63]:
purchases4 = purchases.copy()
med_data = np.nanmedian(purchases4,axis=1)
ind_data = np.where(np.isnan(purchases4))
purchases4[ind_data] = med_data[ind_data[0]]

In [64]:
purchases4

array([[102. , 167.5, 860. , ..., 121. , 466. , 214. ],
       [343. , 343. , 343. , ..., 308. , 343. , 343. ],
       [491. , 413. , 805. , ..., 313. ,  21. , 252. ],
       ...,
       [ 60. , 633. ,  50. , ..., 828. , 533. , 533. ],
       [837. , 512. , 517.5, ...,  77. , 729. , 812. ],
       [922. ,  72. , 793. , ..., 349. , 243. , 830. ]])

In [65]:
total_sale_per_month = np.sum(purchases4,axis=0)
print("Month has highest sales : ",np.argmax(total_sale_per_month)+1)
print("Sale : ",np.max(total_sale_per_month))

Month has highest sales :  3
Sale :  53283.5
