## NumPy Array Creation Practice Assignments

In [1]:
import numpy as np

#### 1 . Create an array of first 50 natural numbers without directly writing numbers.

In [2]:
a1 = np.arange(1,51)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### 2. Generate all even numbers between 1 and 200 using only NumPy methods.

In [8]:
a2 = np.arange(2,201,2)
a2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

#### 3. Create an array of odd numbers from 1 to 199 without using manual list

In [9]:
a3 = np.arange(1,200,2)
a3

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

#### 4. Generate reverse sequence from 100 to 1 using NumPy only

In [11]:
a4 =np.arange(100,0,-1)
a4

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

#### 5. Create an array where each value is multiplication of 3 (0 to 30 multiples)

In [13]:
a5 = np.arange(3,31,3)
a5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

#### 6. Create a sequence: 1, 4, 7, 10, 13 ... up to 30 elements.

In [15]:
a6 = np.arange(1,30,3)
a6

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

#### 7. Create sequence: 2, 6, 12, 20, 30 ... (pattern-based logic).

In [16]:
a7 = np.arange(1,11)
a7 = a7*(a7+1)
a7

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

#### 8. Generate square numbers from 1 to 100 using NumPy only.

In [17]:
a8 = np.arange(1,101)
a8 = a8**2
a8

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

#### 9. Generate cube numbers from 1 to 50

In [18]:
a9 = np.arange(1,51)**3
a9

array([     1,      8,     27,     64,    125,    216,    343,    512,
          729,   1000,   1331,   1728,   2197,   2744,   3375,   4096,
         4913,   5832,   6859,   8000,   9261,  10648,  12167,  13824,
        15625,  17576,  19683,  21952,  24389,  27000,  29791,  32768,
        35937,  39304,  42875,  46656,  50653,  54872,  59319,  64000,
        68921,  74088,  79507,  85184,  91125,  97336, 103823, 110592,
       117649, 125000])

#### 10. Create Fibonacci-like first 20 values (array form).

In [20]:
fib = np.empty(20, dtype=int)
fib[0] = 0
fib[1] = 1
for i in range(2, 20):
    fib[i] = fib[i-1] + fib[i-2]

print(fib)

[   0    1    1    2    3    5    8   13   21   34   55   89  144  233
  377  610  987 1597 2584 4181]


In [21]:
2. PATTERN + arange + OPERATIONS
Create sequence 1–100 and replace even numbers with 0.
Create sequence 1–50 and replace odd numbers with -1.
Create array 1–30 and generate cumulative sum.
Create multiples of 7 and normalize them (divide by max value).
Create sequence 1–100 and calculate square root of each element.

SyntaxError: invalid character '–' (U+2013) (729731793.py, line 2)

#### 11. Create sequence 1–100 and replace even numbers with 0.

In [23]:
a10 = np.arange(1,101)
for i in range(1,len(a10),2):
    a10[i]=0
a10
    

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0, 51,
        0, 53,  0, 55,  0, 57,  0, 59,  0, 61,  0, 63,  0, 65,  0, 67,  0,
       69,  0, 71,  0, 73,  0, 75,  0, 77,  0, 79,  0, 81,  0, 83,  0, 85,
        0, 87,  0, 89,  0, 91,  0, 93,  0, 95,  0, 97,  0, 99,  0])

#### 12 . Create sequence 1–50 and replace odd numbers with -1.

In [25]:
a12 = np.arange(1,50)
for i in range(0,len(a12),2):
    a12[i]=-1
a12

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1,
       18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34,
       -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1])