# 50 numpy exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
 print(np.__version__)



2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a3 = np.zeros(10)
print(a3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a4 = np.arange(10)
print(a4.nbytes)
print("%d bytes" % (a4.size * a4.itemsize))

80
80 bytes


In [5]:
print( (a4.size * a4.itemsize),"bytes" )

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
'''python
%run `python -c "import numpy; numpy.info(numpy.add)"`
'''

'python\n%run `python -c "import numpy; numpy.info(numpy.add)"`\n'

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [8]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

In [9]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\omkar yallurkar\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, th

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a6 = np.zeros(10)
a6[4]=1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
print(np.arange(10,49))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(np.arange(10,49)[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
print(np.arange(0,9).reshape(3,3))
print("-"*20)
print(np.random.randint(0,9,(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[3 5 7]
 [7 6 1]
 [8 6 1]]



#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
a10 = np.nonzero([1,2,0,0,4,0])
print(a10)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
print(np.random.random((3,3,3)))

[[[0.35651263 0.92247987 0.91297654]
  [0.98037824 0.12579363 0.98917592]
  [0.35439598 0.22478817 0.95308055]]

 [[0.37746269 0.95610921 0.57289774]
  [0.38087116 0.7125584  0.64014638]
  [0.36955693 0.77847743 0.40240002]]

 [[0.67387568 0.24676561 0.7515274 ]
  [0.33474987 0.67746587 0.23039644]
  [0.46120416 0.45428129 0.53820864]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
np.random.seed(42)
a13 = np.random.randint(0,1000,(10,10))
print(a13.min())
print(a13.max())

1
975


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
a14 = np.random.randint(1,10,30)
print(np.round(a14.mean()))

6.0


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
a15 = np.full((10,10),1)

a15[1:-1,1:-1]=0
print(a15)
print("-"*20)



[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
--------------------


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [22]:
a16 = np.linspace(10,150,100,dtype=int).reshape(10,10)
a16[[0,-1],:]=0
a16[:,[0,-1]]=0
print(a16)

[[  0   0   0   0   0   0   0   0   0   0]
 [  0  25  26  28  29  31  32  34  35   0]
 [  0  39  41  42  43  45  46  48  49   0]
 [  0  53  55  56  58  59  60  62  63   0]
 [  0  67  69  70  72  73  75  76  77   0]
 [  0  82  83  84  86  87  89  90  92   0]
 [  0  96  97  99 100 101 103 104 106   0]
 [  0 110 111 113 114 116 117 118 120   0]
 [  0 124 125 127 128 130 131 133 134   0]
 [  0   0   0   0   0   0   0   0   0   0]]


In [23]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=2, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf < np.nan)
print(np.inf == np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(3 * 0.1)

nan
False
False
False
False
nan
True
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
Z = np.diag(np.arange(1,5),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [28]:
a20 = np.random.randint(0,1000,(6,7,8)).astype(int)
# print(a20)
print(a20.flatten()[99])
print(np.unravel_index(99,(6,7,8)))
print(a20[1,5,3])

224
(np.int64(1), np.int64(5), np.int64(3))
224


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:

a22 = np.random.random((5,5))
a22 = (a22 - np.mean (a22)) / (np.std (a22))
print(a22)

[[-0.55801098  0.30499392 -0.14318905 -0.05559847  1.73374853]
 [ 2.07529509 -1.34639518 -0.79507763  1.04483489 -0.19907642]
 [-0.61497757 -0.45126941 -0.34275871  1.7514885  -1.08286156]
 [ 1.19517052  0.5738412  -0.4464149   0.04427129 -0.60684412]
 [ 0.807475   -1.30190031 -1.60605201  0.87267934 -0.85337196]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
a24 = np.arange(0,15).reshape(5,3)
b24 = np.arange(0,6).reshape(3,2)
print(a24@b24)
print("--"*20)
aa24 = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(aa24)
print("--"*20)
bb24 = np.ones((5,3)) @ np.ones((3,2))
print(bb24)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
----------------------------------------
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
----------------------------------------
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [35]:
Z =np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/2)
# print(Z<Z>)   Invalid syntax

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[0.5 1.  1.5]



#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14920\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14920\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14920\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
print(np.zeros(10,dtype=bool))

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[False False False False False False False False False False]
[ -9.  -3.  -9.   8. -10.   2.  -2.   4.  -4.  -7.]
[ -9.  -3.  -9.   8. -10.   2.  -2.   4.  -4.  -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
a30 = np.random.randint(1,100,10)
b30 = np.random.randint(1,200,10)
print(np.intersect1d(a30,b30))

[]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [39]:
Z = np.ones(1) / 0

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14920\1497651281.py:1: RuntimeWarning: divide by zero encountered in divide
  Z = np.ones(1) / 0


In [40]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14920\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [42]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2026-04-27
Today: 2026-04-28
Tomorrow: 2026-04-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [43]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [44]:
a35 = np.ones(3)
b35 = np.ones(3)*2
print(a35)
print(b35)
np.add(a35,b35,b35)
np.negative(a35,a35)
np.divide(a35,2,a35)
np.multiply(b35,a35)

[1. 1. 1.]
[2. 2. 2.]


array([-1.5, -1.5, -1.5])

In [45]:
a35

array([-0.5, -0.5, -0.5])

In [46]:
b35

array([3., 3., 3.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [47]:
Z = np.random.uniform(0,10,10)
print(Z)
print("----"*20)
print(Z%1)
print("----"*20)
print("----"*20)
print(Z - Z%1)
print("----"*20)
print(Z // 1)
print("----"*20)
print(np.floor(Z))
print("----"*20)
print(Z.astype(int))
print("----"*20)
print(np.trunc(Z))

[8.42023075 1.94380034 4.11353905 6.99512211 1.38353092 1.32745422
 9.69536867 7.14595104 0.41067517 3.98820901]
--------------------------------------------------------------------------------
[0.42023075 0.94380034 0.11353905 0.99512211 0.38353092 0.32745422
 0.69536867 0.14595104 0.41067517 0.98820901]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
[8. 1. 4. 6. 1. 1. 9. 7. 0. 3.]
--------------------------------------------------------------------------------
[8. 1. 4. 6. 1. 1. 9. 7. 0. 3.]
--------------------------------------------------------------------------------
[8. 1. 4. 6. 1. 1. 9. 7. 0. 3.]
--------------------------------------------------------------------------------
[8 1 4 6 1 1 9 7 0 3]
--------------------------------------------------------------------------------
[8. 1. 4. 6. 1. 1. 9. 7. 0. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [48]:
print(np.random.randint(0,4,(5,5)))
print("-"*20)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[2 3 1 2 1]
 [0 1 0 1 2]
 [2 0 3 0 0]
 [1 1 0 2 1]
 [3 1 1 3 0]]
--------------------
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [49]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [50]:
a = np.ones(10)
a[::2]=0
print(a)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [51]:
a= np.random.random(10)
a.sort()
print(a)

[0.24773099 0.2799339  0.35597268 0.41960006 0.55435405 0.61172075
 0.66019738 0.73789692 0.75784611 0.95486528]



#### 41. How to sum a small array faster than np.sum? (★★☆)

In [52]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [53]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [54]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Subtract the mean of each row of a matrix (★★☆)

In [55]:
matrix = np.random.random((5, 4))

row_mean = matrix.mean(axis=1, keepdims=True)

result  = matrix - row_mean
print(result)

[[ 0.26183743  0.0323534  -0.34398627  0.04979544]
 [ 0.10371426 -0.19655564  0.06409414  0.02874723]
 [ 0.198135    0.21737856 -0.37241108 -0.04310248]
 [-0.035185   -0.15790865  0.19544493 -0.00235128]
 [-0.06267401 -0.15503969  0.41681084 -0.19909713]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [56]:
a = random.randint(0,1000,10)
print(a)
a[np.argmax(a)]=0
print(a)

[895 159 474 851 663 907 689 674 379 544]
[895 159 474 851 663   0 689 674 379 544]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [57]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. How to tell if a given 2D array has null columns? (★★☆)

In [68]:
a47 = np.array([
    [1,  np.nan, 3],
    [4,  np.nan, 6],
    [7,  np.nan, 9]
])

null_columns = np.all(np.isnan(a47), axis=0)
print(null_columns)

[False  True False]


#### 48. How to get the diagonal of a dot product? (★★★)

In [70]:
a48 = np.random.randint(1,25,(5, 3))

dot_product = np.dot(a48, a48.T)

diag = np.diag(dot_product)


In [63]:
dot_product

array([[866, 379, 401, 753, 311],
       [379, 473, 181, 227, 364],
       [401, 181, 206, 408, 146],
       [753, 227, 408, 874, 188],
       [311, 364, 146, 188, 281]], dtype=int32)

In [64]:
diag

array([866, 473, 206, 874, 281], dtype=int32)

#### 49. How to swap two rows of an array? (★★★)

In [74]:
a49 = np.arange(9).reshape(3, 3)
print(a49)
a49[[0, 2]] = a49[[2, 0]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [75]:
a49

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 50. How to find the most frequent value in an array?

In [78]:
a50= np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(a50, return_counts=True)
most_frequent = values[np.argmax(counts)]

print(most_frequent)

3
