# SPLITTING METHODS 

In [155]:
import numpy as np

# 1. np.split()

### 1D ARRAY

In [156]:
A = np.array([10, 20, 30, 40, 50, 60])
print("Array  A : ",A)

Array  A :  [10 20 30 40 50 60]


#### BASIC

#### 1. Split A into 2 equal parts.

In [157]:
data1, data2 = np.split(A,2)
print("Dataset 1 : ",data1)
print("Dataset 2 : ",data2)

Dataset 1 :  [10 20 30]
Dataset 2 :  [40 50 60]


#### 2. Split A into 3 equal parts.

In [158]:
data1 , data2, data3 = np.split(A,3)
print("Dataset 1 : ",data1)
print("Dataset 2 : ",data2)
print("Dataset 3 : ",data3)

Dataset 1 :  [10 20]
Dataset 2 :  [30 40]
Dataset 3 :  [50 60]


#### 3.Split A at index [2].

In [159]:
data1, data2 = np.split(A,[2])
print("Dataset 1 : ",data1)
print("Dataset 2 : ",data2)

Dataset 1 :  [10 20]
Dataset 2 :  [30 40 50 60]


#### 4. Split A at indices [2, 4].

In [160]:
data1 , data2 , data3 = np.split(A,[2,4])
print("Dataset 1 : ",data1)
print("Dataset 2 : ",data2)
print("Dataset 3 : ",data3)

Dataset 1 :  [10 20]
Dataset 2 :  [30 40]
Dataset 3 :  [50 60]


#### 5. Split A into 6 parts.

In [161]:
np.split(A,6)

[array([10]), array([20]), array([30]), array([40]), array([50]), array([60])]

#### ADVANCED 

#### 1. Split A into 3 parts and compare sums.

In [162]:
data1 , data2, data3 = np.split(A,3)
print("Dataset 1  Sum : ",data1.sum())
print("Dataset 2  sum : ",data2.sum())
print("Dataset 3  sum  :",data3.sum())

Dataset 1  Sum :  30
Dataset 2  sum :  70
Dataset 3  sum  : 110


#### 2. Split A and identify segment containing 40.

In [163]:
data1, data2 = np.split(A,2)
if np.isin(data1,40).any():
    print("Contain in 1st part")
    print("Dataset 1 : ",data1)
elif np.isin(data2,40).any() :
    print("Contain in 2nd part")
    print("Dataset 2 : ",data2)
else :
    print("Not coianing in both parts")

Contain in 2nd part
Dataset 2 :  [40 50 60]


#### 3. Split A into halves and compare max values.

In [164]:
data1, data2 = np.split(A,2)
max_data1 = np.max(data1)
max_data2 = np.max(data2)
if max_data1 > max_data1:
    print("Max value[data1]:",max_data1)
elif max_data1 < max_data2:
    print("Max value[data2] : ",max_data2)
else :
    print("Both Are common :",data1)

Max value[data2] :  60


#### 4.Split A and calculate length of each segment.

In [165]:
data1,data2 = np.split(A,[4])
print("Length of data1 :",data1.size)
print("Length of data2 : ",data2.size)

Length of data1 : 4
Length of data2 :  2


#### 5.Split A and reverse each segment.

In [166]:
data1 , data2 = np.split(A,2)
print("Dataset Reverse :",data1[::-1])
print("Dataset Reverse : ",data2[::-1])

Dataset Reverse : [30 20 10]
Dataset Reverse :  [60 50 40]


#### 2D ARRAY

In [167]:
x =np.array(
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### BASIC 

#### 1.Split X into 2 parts row-wise.

In [168]:
data1 , data2 = np.split(x,2,axis=0)
print("Dataset 1 : ",data1,sep='\n')
print("Dataset 2 : ",data2,sep='\n')

Dataset 1 : 
[[1 2 3 4]
 [5 6 7 8]]
Dataset 2 : 
[[ 9 10 11 12]
 [13 14 15 16]]


#### 2. Split X into 2 parts column-wise.

In [169]:
data1 , data2 = np.split(x,2,axis = 1)
print("Dataset 1 : ",data1,sep = '\n')
print("Dataset 2 : ",data2,sep = '\n')

Dataset 1 : 
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Dataset 2 : 
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


#### 3. Split X at row index 2.

In [170]:
data1 , data2 = np.split(x,2,axis =0)
print("Row  wise spliting : ")
print("Dataset 1 : ",data1,sep = '\n')
print("Dataset 2 : ",data2,sep = '\n')

Row  wise spliting : 
Dataset 1 : 
[[1 2 3 4]
 [5 6 7 8]]
Dataset 2 : 
[[ 9 10 11 12]
 [13 14 15 16]]


#### 4. Split X at column index 2.

In [171]:
data1 , data2 = np.split(x,[2],axis=1)
print("Dataset 1 : ",data1,sep = '\n')
print("Dataset 2 : ",data2,sep = '\n')

Dataset 1 : 
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Dataset 2 : 
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


#### 5. Split X into 4 equal blocks.

In [172]:
d1,d2,d3,d4 = np.split(x,4)
print("Data 1 : ",d1)
print("Data 2 : ",d2)
print("Data 3 : ",d3)
print("Data 4 : ",d4)

Data 1 :  [[1 2 3 4]]
Data 2 :  [[5 6 7 8]]
Data 3 :  [[ 9 10 11 12]]
Data 4 :  [[13 14 15 16]]


#### ADVANCED

#### 1. Split X and compute sum of each block.

In [173]:
data1 , data2 = np.split(x,2)
print("Sum of database 1 : ",data1.sum())
print("Sum of database 2 : ",data2.sum())

Sum of database 1 :  36
Sum of database 2 :  100


#### 2. Split X and compare shapes.

In [174]:
data1 , data2 = np.split(x,2)
print("Shape of Database 1 :",data1.shape)
print("Shape of Database 2 :",data2.shape)


Shape of Database 1 : (2, 4)
Shape of Database 2 : (2, 4)


#### 3. Split X into uneven row groups.

In [175]:
np.split(x,[2,3,4],axis = 0)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([], shape=(0, 4), dtype=int64)]

#### 4. Identify block containing value 10.

In [176]:
block1 , block2 = np.split(x,2)
if np.isin(block1,10).any():
    print("10 value conatin in block 1")
    print(block1)
if np.isin(block2,10).any():
    print("10 value conatin in block 2")
    print(block2)
    

10 value conatin in block 2
[[ 9 10 11 12]
 [13 14 15 16]]


#### 5. Compute max per split.

In [177]:
data1 , data2 = np.split(x,2)
print("Max value form data1 : ",data1.max())
print("Max value form data2 : ",data2.max())

Max value form data1 :  8
Max value form data2 :  16


### 3D ARRAY

In [178]:
A = np.array(
[[[1,2],[3,4]],
[[5,6],[7,8]]])
print("Arrray A :")
print(A)
print("Shape :",A.shape)

Arrray A :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape : (2, 2, 2)


#### BASIC 

#### 1. Split A along axis=0.

In [179]:
data1, data2 = np.split(A,2,axis=0)
print("-----Data1----- ")
print(data1)
print("Shape :",data1.shape)
print(" -----Data2----  ")
print(data2)
print("Shape :",data2.shape)

-----Data1----- 
[[[1 2]
  [3 4]]]
Shape : (1, 2, 2)
 -----Data2----  
[[[5 6]
  [7 8]]]
Shape : (1, 2, 2)


#### 2. Split A along axis=1.

In [180]:
data1, data2 = np.split(A,2,axis=1)
print("-----Data1----- ")
print(data1)
print("Shape :",data1.shape)
print(" -----Data2----  ")
print(data2)
print("Shape :",data2.shape)

-----Data1----- 
[[[1 2]]

 [[5 6]]]
Shape : (2, 1, 2)
 -----Data2----  
[[[3 4]]

 [[7 8]]]
Shape : (2, 1, 2)


#### 3. Split A along axis=2.

In [181]:
data1, data2 = np.split(A,2,axis=2)
print("-----Data1----- ")
print(data1)
print("Shape :",data1.shape)
print(" -----Data2----  ")
print(data2)
print("Shape :",data2.shape)

-----Data1----- 
[[[1]
  [3]]

 [[5]
  [7]]]
Shape : (2, 2, 1)
 -----Data2----  
[[[2]
  [4]]

 [[6]
  [8]]]
Shape : (2, 2, 1)


#### 4. Identify number of resulting arrays.

In [182]:
np.split(A,2)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]])]

#### 5. Describe shape after each split

In [183]:
data1, data2 = np.split(A,2)
print("shape of 1st block :",data1.shape)
print("Shape of 2nd block :",data2.shape)

shape of 1st block : (1, 2, 2)
Shape of 2nd block : (1, 2, 2)


#### ADVANCED 

#### 1. Compute sum of each split.

In [184]:
data1,data2 = np.split(A,2)
print("Sum of dataset1 : ",data1.sum())
print("Sum Of Dataset 2 : ",data2.sum())

Sum of dataset1 :  10
Sum Of Dataset 2 :  26


#### 2. Identify which split contains value 6.

In [185]:
data1,data2 = np.split(A,2)
if np.isin(data1,6).any():
    print("Dataset 1")
    print(data1)
if np.isin(data2,6).any():
    print("Database 2")
    print(data2)

Database 2
[[[5 6]
  [7 8]]]


#### 3. Compare splitting across axes.

In [186]:
data1, data2 = np.split(A,2,axis = 0)
data3, data4 = np.split(A,2,axis = 1)

print("Spliting data row vise")
print("Data1 : ",data1,sep='\n')
print("Data2 : ",data2,sep='\n')
print("Spliting data column vise")
print("Data3 : ",data3,sep='\n')
print("Data4 : ",data4,sep='\n')


Spliting data row vise
Data1 : 
[[[1 2]
  [3 4]]]
Data2 : 
[[[5 6]
  [7 8]]]
Spliting data column vise
Data3 : 
[[[1 2]]

 [[5 6]]]
Data4 : 
[[[3 4]]

 [[7 8]]]


#### --------------------------------------------------------------------------------------------------------------

# 2. np.array_split
(Same structure — focus on unequal splits)

## 1D ARRAY

In [187]:
A = np.array([1, 2, 3, 4, 5])

In [188]:
print("Array A : ",A)

Array A :  [1 2 3 4 5]


#### BASIC 

#### 1.Split A into 2 parts.

In [189]:
data1 , data2  = np.array_split(A,2)
print("data1 :",data1)
print("data2 :",data2)

data1 : [1 2 3]
data2 : [4 5]


#### 2. Split A into 3 parts.

In [190]:
data1, data2, data3 = np.array_split(A,3)
print("data1 :",data1)
print("data 2 :",data2)
print("data 3 :",data3)

data1 : [1 2]
data 2 : [3 4]
data 3 : [5]


#### 3. Split A into 4 parts.

In [191]:
data1, data2, data3 , data4 = np.array_split(A,4)
print("data1 :",data1)
print("data 2 :",data2)
print("data 3 :",data3)
print("data 4 :",data4)

data1 : [1 2]
data 2 : [3]
data 3 : [4]
data 4 : [5]


#### Split A into 5 parts.

In [192]:
data1, data2, data3, data4, data5 = np.array_split(A,5)
print("data1 :",data1)
print("data 2 :",data2)
print("data 3 :",data3)
print("data 4 :",data4)
print("data 5 :",data5)

data1 : [1]
data 2 : [2]
data 3 : [3]
data 4 : [4]
data 5 : [5]


#### 5. Split A into 6 parts.

In [193]:
data1, data2, data3, data4, data5, data6 = np.array_split(A,6)
print("data1 :",data1)
print("data 2 :",data2)
print("data 3 :",data3)
print("data 4 :",data4)
print("data 5 :",data5)
print("data 6 :",data6)

data1 : [1]
data 2 : [2]
data 3 : [3]
data 4 : [4]
data 5 : [5]
data 6 : []


#### ADVANCED

#### 1. Compare sizes of each segment.

In [194]:
data1, data2, data3, = np.array_split(A,3)
print("data1 size  :",data1.size)
print("data 2 size  :",data2.size)
print("data 3 size :",data3.size)

data1 size  : 2
data 2 size  : 2
data 3 size : 1


#### 2.Identify smallest segment.

In [195]:
data1, data2, data3, = np.array_split(A,3)
d1Size = data1.size
d2Size = data2.size
d3Size = data3.size
print("data 1 size :",d1Size)
print("data 1 size :",d1Size)
print("data 1 size :",d1Size)

small = 0 
if d1Size< d2Size and d1Size<d3Size:
    print("Smallest size : ",d1Size)
    print(data1)
elif d2Size< d3Size:
    print("Smallest size : ",d2Size)
    print(data1)
else :
    print("Smallest size : ",d3Size)
    print(data1)



data 1 size : 2
data 1 size : 2
data 1 size : 2
Smallest size :  1
[1 2]


#### 3. Compute sum of each part.

In [196]:
data1, data2,data3 = np.array_split(A,3)
print("Sum of part 1 : ",data1.sum())
print("Sum of part 2 : ",data2.sum())
print("Sum of part 3 : ",data3.sum())

Sum of part 1 :  3
Sum of part 2 :  7
Sum of part 3 :  5


#### 4. Analyze uneven distribution.

In [197]:
data1, data2, data3 = np.array_split(A,3)
print("Dataset1 ")
print("Sahpe : ",data1.shape )
print("Dimension  : ",data1.ndim )
print(data1 )
print("_"*80)
print("Dataset2 ")
print("Sahpe : ",data2.shape )
print("Dimension  : ",data2.ndim )
print(data2 )
print("_"*80)
print("Dataset3 ")
print("Sahpe : ",data3.shape )
print("Dimension  : ",data3.ndim )
print(data3 )

Dataset1 
Sahpe :  (2,)
Dimension  :  1
[1 2]
________________________________________________________________________________
Dataset2 
Sahpe :  (2,)
Dimension  :  1
[3 4]
________________________________________________________________________________
Dataset3 
Sahpe :  (1,)
Dimension  :  1
[5]


#### 5. Compare with equal split.

In [198]:
data1, data2 = np.array_split(A,2)
print("Dataset1 ")
print("Sahpe : ",data1.shape )
print("Dimension  : ",data1.ndim )
print(data1 )
print("_"*30)
print("Dataset2 ")
print("Sahpe : ",data2.shape )
print("Dimension  : ",data2.ndim )

Dataset1 
Sahpe :  (3,)
Dimension  :  1
[1 2 3]
______________________________
Dataset2 
Sahpe :  (2,)
Dimension  :  1


## 2D ARRAY

In [199]:
ar = np.array([[1,2,3],[11,22,33],[7,8,9]])
print(ar)

[[ 1  2  3]
 [11 22 33]
 [ 7  8  9]]


#### 1. Split rows into 3 parts.

In [200]:
d1,d2, d3 = np.array_split(ar,3)
print("Part 1 :",d1)
print("Part 2 :",d2)
print("Part 3 :",d3)

Part 1 : [[1 2 3]]
Part 2 : [[11 22 33]]
Part 3 : [[7 8 9]]


#### 2. Split rows into 4 parts.

In [201]:
d1,d2, d3 ,d4= np.array_split(ar,4)
print("Part 1 :",d1)
print("Part 2 :",d2)
print("Part 3 :",d3)
print("Part 3 :",d4)

Part 1 : [[1 2 3]]
Part 2 : [[11 22 33]]
Part 3 : [[7 8 9]]
Part 3 : []


#### 3 . Split columns unevenly.

In [202]:
d1,d2, d3 = np.array_split(ar,3,axis =1)
print("Part 1 :",d1)
print("Part 2 :",d2)
print("Part 3 :",d3)

Part 1 : [[ 1]
 [11]
 [ 7]]
Part 2 : [[ 2]
 [22]
 [ 8]]
Part 3 : [[ 3]
 [33]
 [ 9]]


#### 4. Identify smallest block.

In [203]:
d1,d2= np.array_split(ar,2)
print("Smallest block 1 :",d1.size )if d1.size < d2.size else print("Smallest block2 ", d2.size)

Smallest block2  3


#### 5. Count rows per split.

In [204]:
d1,d2= np.array_split(ar,2)
print("Data 1 total rows :",d1.shape[0])
print("Data 2 total rows :",d2.shape[0])

Data 1 total rows : 2
Data 2 total rows : 1


#### 6. Compute sum per split.

In [205]:
d1,d2= np.array_split(ar,2)
print("Sum of dataset1",d1.sum())
print("Sum of dtaset2 :",d2.sum())

Sum of dataset1 72
Sum of dtaset2 : 24


#### 3D ARRAY

In [206]:
ar3 = np.array([[np.zeros(5),np.ones(5),np.full(5,7)],[np.ones(5),np.zeros(5),np.full(5,5)]])
ar3

array([[[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [7., 7., 7., 7., 7.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [5., 5., 5., 5., 5.]]])

In [207]:
ar3.shape

(2, 3, 5)

#### 1 . Split along axis=0 into uneven parts.

In [208]:
d1, d2, d3 = np.array_split(ar3,3,axis=0)

In [209]:
d1

array([[[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [7., 7., 7., 7., 7.]]])

In [210]:
d2

array([[[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [5., 5., 5., 5., 5.]]])

In [211]:
d3

array([], shape=(0, 3, 5), dtype=float64)

#### 2 . Split along axis=1 unevenly.

In [212]:
d1, d2, d3 , d4 = np.array_split(ar3,4,axis=1)

In [213]:
d1

array([[[0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.]]])

In [214]:
d2

array([[[1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.]]])

In [215]:
d3

array([[[7., 7., 7., 7., 7.]],

       [[5., 5., 5., 5., 5.]]])

In [216]:
d4

array([], shape=(2, 0, 5), dtype=float64)

#### 3. Split along axis=2 unevenly.

In [217]:
d1, d2, d3 = np.array_split(ar3,3,axis=2)

In [218]:
d1

array([[[0., 0.],
        [1., 1.],
        [7., 7.]],

       [[1., 1.],
        [0., 0.],
        [5., 5.]]])

In [219]:
d2

array([[[0., 0.],
        [1., 1.],
        [7., 7.]],

       [[1., 1.],
        [0., 0.],
        [5., 5.]]])

In [220]:
d3

array([[[0.],
        [1.],
        [7.]],

       [[1.],
        [0.],
        [5.]]])

#### 4. Count elements per split.

In [221]:
d1, d2, d3 = np.array_split(ar3,3)


In [222]:
d1.size

15

In [223]:
d2.size

15

In [224]:
d3.size

0

In [225]:
a1,a2,a3 = np.array_split(ar3,3,axis=1)

In [226]:
a1.size

10

In [227]:
a2.size

10

In [228]:
a3.size

10

In [229]:
b1,b2,b3 = np.array_split(ar3,3,axis=2)

In [230]:
b1.size

12

In [231]:
b2.size

12

In [232]:
b3.size

6

#### 5. Compute sum per split.

In [234]:
d1,d2,d3 = np.array_split(ar3,3)

In [235]:
print(d1.sum())
print(d2.sum())
print(d3.sum())

40.0
30.0
0.0


In [236]:
a1,a2,a3 = np.array_split(ar3,3,axis=1)

In [237]:
print(a1.sum())
print(a2.sum())
print(a3.sum())

5.0
5.0
60.0


In [238]:
b1,b2,b3 = np.array_split(ar3,3,axis=2)

In [239]:
print(b1.sum())
print(b2.sum())
print(b3.sum())

28.0
28.0
14.0


# 3. np.vsplit()

(ONLY ROW SPLITTING)

In [240]:
arr = np.full((4,3),5)

In [241]:
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [242]:
arr.shape

(4, 3)

#### 1. Split into 2 row groups.

In [243]:
p1,p2 = np.vsplit(arr,2)

In [244]:
p1

array([[5, 5, 5],
       [5, 5, 5]])

In [245]:
p2

array([[5, 5, 5],
       [5, 5, 5]])

#### 2 . Split into 4 parts.

In [246]:
d1,d2,d3,d4 = np.vsplit(arr,4)

In [247]:
d1

array([[5, 5, 5]])

In [248]:
d2

array([[5, 5, 5]])

In [249]:
d3

array([[5, 5, 5]])

In [250]:
d4

array([[5, 5, 5]])

#### 3. Split after row index 2.

In [251]:
d1,d2 = np.hsplit(arr,[2])

In [252]:
d1

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [253]:
d2

array([[5],
       [5],
       [5],
       [5]])

#### 4. Count rows per split.

In [254]:
d1,d2 = np.vsplit(arr,2)

In [255]:
d1.shape[0]

2

In [256]:
d2.shape[0]

2

#### 5. Compute sum per split.

In [257]:
d1,d2 = np.vsplit(arr,2)

In [258]:
print(d1.sum())

30


In [259]:
print(d2.sum())

30


# 4. np.hsplit()

(ONLY COLUMN SPLITTING)

In [266]:
a = np.array([[1,2,3,8],[4,5,6,2],[7,8,9,1]])
a

array([[1, 2, 3, 8],
       [4, 5, 6, 2],
       [7, 8, 9, 1]])

#### 1 .Split into 2 column groups.

In [267]:
d1,d2 = np.hsplit(a,2)

In [268]:
d1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [269]:
d2

array([[3, 8],
       [6, 2],
       [9, 1]])

#### 2. Split into 4 columns.

In [270]:
c1,c2,c3,c4 = np.hsplit(a,4)

In [271]:
c1

array([[1],
       [4],
       [7]])

In [272]:
c2

array([[2],
       [5],
       [8]])

In [274]:
c3

array([[3],
       [6],
       [9]])

In [275]:
c4

array([[8],
       [2],
       [1]])

#### 3. Split after column index 2.

In [276]:
d1,d2 = np.hsplit(a,[2])

In [277]:
d1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [278]:
d2

array([[3, 8],
       [6, 2],
       [9, 1]])

#### 4. Divide into left/right halves.

In [279]:
l1,h1 = np.hsplit(a,2)

In [280]:
l1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [282]:
h1

array([[3, 8],
       [6, 2],
       [9, 1]])

#### 5. Count columns per split.

In [283]:
d1,d2 = np.hsplit(a,2)

In [284]:
d1.shape[1]

2

In [285]:
d2.shape[1]

2

#### 6. Compute sum per column block.

In [286]:
d1,d2 = np.hsplit(a,2)

In [289]:
print(d1.sum())

27


In [288]:
print(d2.sum())

29


# 5. np.dsplit()

(DEPTH SPLITTING)

In [ ]:
array = np.ones((3,2,2))
array

#### 1. Split into depth layers.

In [290]:
dep1 , dep2 = np.dsplit(array,2)

In [291]:
dep1.shape

(3, 2, 1)

In [292]:
dep2.shape

(3, 2, 1)

#### 2. Count layers.

In [293]:
dep1.shape[0]

3

In [294]:
dep2.shape[0]

3

#### 3.Extract first layer.

In [295]:
dep1[0]

array([[1.],
       [1.]])

In [296]:
dep2[0]

array([[1.],
       [1.]])

#### 4. Extract second layer.

In [297]:
dep1[1]

array([[1.],
       [1.]])

In [298]:
dep2[1]

array([[1.],
       [1.]])

#### 5.Compute sum per layer.

In [299]:
print(dep1[0].sum())
print(dep1[1].sum())


2.0
2.0
