# NumPy Set Operations

In [1]:
import numpy as np

## 1. np.union1d()

#### 1. Find the union of two arrays [1,2,3] and [3,4,5].

In [3]:
a= np.array([1,2,3])
b = np.array([3,4,5])
print(np.union1d(a,b))

[1 2 3 4 5]


#### 2. Find unique combined elements from [5,6,7] and [7,8,9].

In [4]:
print(np.union1d([5,6,7],[7,8,9]))

[5 6 7 8 9]


#### 3. Find union of [10,20] and [20,30,40].

In [5]:
print(np.union1d([10,20],[20,30,40]))

[10 20 30 40]


#### 4. Combine [1,1,2] and [2,3,3] into unique elements.

In [6]:
print(np.union1d([1,1,2],[2,3,3]))

[1 2 3]


#### 5. Find union of [100,200] and [300,400].

In [7]:
print(np.union1d([100,200],[300,400]))

[100 200 300 400]


#### 6. Merge [2,4,6] and [1,3,5] into sorted unique array.

In [8]:
np.union1d([2,4,6],[1,3,5])

array([1, 2, 3, 4, 5, 6])

#### 7. Find union of negative arrays [-1,-2] and [-2,-3].

In [9]:
np.union1d([-1,-2],[-2,-3])

array([-3, -2, -1])

#### 8. Combine [0,1,2] and [2,3,4].

In [10]:
print(np.union1d([0,1,2],[2,3,4]))

[0 1 2 3 4]


#### 9. Find union of [9,8,7] and [7,6,5].

In [11]:
print(np.union1d([9,8,7],[7,6,5]))

[5 6 7 8 9]


#### 10. Combine [11,12] and [12,13,14].

In [12]:
print(np.union1d([11,12],[12,13,14]))

[11 12 13 14]


# 

## 2. np.intersect1d()

#### 1. Find common elements in [1,2,3] and [2,3,4].

In [13]:
print(np.intersect1d([1,2,3],[2,3,4]))

[2 3]


#### 2. Find intersection of [5,6,7] and [7,8,9].

In [14]:
print(np.intersect1d([5,6,7],[7,8,9]))

[7]


#### 3. Find common values in [10,20,30] and [20,40].

In [15]:
print(np.intersect1d([10,20,30],[20,30]))

[20 30]


#### 4. Find intersection of [1,1,2] and [2,2,3].

In [16]:
print(np.intersect1d([1,1,2],[2,2,3]))

[2]


#### 5. Find common elements in [100,200] and [300,200].

In [17]:
print(np.intersect1d([100,200],[300,200]))

[200]


#### 6. Find intersection of [2,4,6] and [1,3,5].

In [18]:
print(np.intersect1d([2,4,6],[1,3,5]))

[]


#### 7. Find common elements in [-1,-2] and [-2,-3].

In [20]:
print(np.intersect1d([-1,-2],[-2,-3]))

[-2]


#### 8. Find intersection of [0,1,2] and [2,3,4].

In [21]:
print(np.intersect1d([0,1,2],[2,3,4]))

[2]


#### 9. Find common values in [9,8,7] and [7,6,5].

In [22]:
print(np.intersect1d([9,8,7],[7,6,5]))

[7]


#### 10. Find intersection of [11,12] and [12,13,14].

In [23]:
print(np.intersect1d([11,12],[12,13,14]))

[12]


# 

## 3. np.setdiff1d()

#### 1.Find elements in [1,2,3] not in [2,3].

In [24]:
print(np.setdiff1d([1,2,3],[2,3]))

[1]


#### 2.Find values in [5,6,7] not in [7,8,9].

In [25]:
print(np.setdiff1d([5,6,7],[7,8,9]))

[5 6]


#### 3.Find difference [10,20,30] minus [20].

In [26]:
print(np.setdiff1d([10,20,30],[20]))

[10 30]


#### 4. Find unique elements in [1,2,3] not in [3].

In [27]:
print(np.setdiff1d([1,2,3],[3]))

[1 2]


#### 5. Find elements in [100,200] not in [200].

In [28]:
print(np.setdiff1d([100,200],[200]))

[100]


#### 6. Find difference [2,4,6] minus [4].

In [29]:
print(np.setdiff1d([2,4,6],[4]))

[2 6]


#### 7. Find values in [-1,-2] not in [-2].

In [30]:
print(np.setdiff1d([-1,-2],[-2]))

[-1]


#### 8. Find difference [0,1,2] minus [1].

In [31]:
print(np.setdiff1d([0,1,2],[1]))

[0 2]


#### 9.Find elements in [9,8,7] not in [7].

In [32]:
print(np.setdiff1d([9,8,7],[7]))

[8 9]


#### 10.Find values in [11,12,13] not in [12].

In [33]:
print(np.setdiff1d([11,12,13],[12]))

[11 13]


# 

## 4. np.setxor1d()

#### 1.Find symmetric difference of [1,2,3] and [2,3,4].

In [34]:
print(np.setxor1d([1,2,3],[2,3,4]))

[1 4]


#### 2.Find elements only in one of [5,6,7] and [7,8,9].

In [35]:
print(np.setxor1d([5,6,7],[7,8,9]))

[5 6 8 9]


#### 3.Find XOR of [10,20,30] and [20,40].

In [36]:
print(np.setxor1d([10,20,30],[20,40]))

[10 30 40]


#### 4.Find unique non-common elements in [1,2,3] and [3,4,5].

In [37]:
print(np.setxor1d([1,2,3],[3,4,5]))

[1 2 4 5]


#### 5.Find XOR of [100,200] and [200,300].

In [38]:
print(np.setxor1d([100,200],[200,300]))

[100 300]


#### 6.Find symmetric difference of [2,4,6] and [4,8].

In [39]:
print(np.setxor1d([2,4,6],[4,8]))

[2 6 8]


#### 7.Find XOR of [-1,-2] and [-2,-3].

In [40]:
print(np.setxor1d([-1,-2],[-2,-3]))

[-3 -1]


#### 8.Find symmetric difference of [0,1,2] and [2,3,4].

In [41]:
print(np.setxor1d([0,1,2],[2,3,4]))

[0 1 3 4]


#### 9.Find XOR of [9,8,7] and [7,6,5].

In [42]:
print(np.setxor1d([9,8,7],[7,6,5]))

[5 6 8 9]


#### 10. Find symmetric difference of [11,12] and [12,13,14].

In [43]:
print(np.setxor1d([11,12],[12,13,14]))

[11 13 14]


# 

## 5. np.unique()

#### 1. Find unique elements in [1,2,2,3,3].

In [44]:
print(np.unique([1,2,2,3,3]))

[1 2 3]


#### 2. Remove duplicates from [5,5,6,7].

In [45]:
b = np.array([5,5,6,7])
print(np.unique(b))

[5 6 7]


#### 3. Find unique values in [10,20,20,30].

In [46]:
c  = np.array([10,20,20,30])
print(np.unique(c))

[10 20 30]


#### 4. Remove duplicates from [1,1,1,2].

In [47]:
d = np.array([1,1,1,2])
print(np.unique(d))

[1 2]


#### 5. Find unique elements in [100,200,200].

In [48]:
e= np.array([100,200,200])
print(np.unique(e))

[100 200]


#### 6. Remove duplicates from [2,4,4,6].

In [49]:
f = np.array([2,4,4,6])
print(np.unique(f))

[2 4 6]


#### 7. Find unique values in [-1,-1,-2].

In [50]:
g = np.array( [-1,-1,-2])
print(np.unique(g ))

[-2 -1]


#### 8. Remove duplicates from [0,0,1,2].

In [51]:
h= np.array( [0,0,1,2])
print(np.unique(h))

[0 1 2]


#### 9.  Find unique elements in [9,9,8,7].

In [52]:
i= np.array([9,9,8,7])
print(np.unique(i))

[7 8 9]


#### 10. Remove duplicates from [11,12,12,13].

In [53]:
j = np.array([11,12,12,13])
print(np.unique(j))

[11 12 13]


# 

## 6. np.isin()

#### 1.Check if [1,2,3] elements exist in [2,3,4].

In [54]:
a1 = np.array([1,2,3])
b1 = np.array([2,3,4])
print(np.isin(a1,b1))

[False  True  True]


#### 2. Check membership of [5,6,7] in [7,8,9].

In [55]:
a2 = np.array([5,6,7])
b2 = np.array([7,8,9])
print(np.isin(a2,b2))

[False False  True]


#### 3. Check if [10,20] is in [20,30].

In [57]:
a3 = np.array([10,20])
b3 = np.array([20,30])
print(np.isin(a3,b3))

[False  True]


#### 4. Check membership of [1,2,3] in [3,4,5].

In [58]:
a4 = np.array([1,2,3])
b4 = np.array([3,4,5])
print(np.isin(a4,b4))

[False False  True]


#### 5. Check if [100,200] is in [200,300].

In [59]:
a5 = np.array([100,200] )
b5 = np.array([200,300])
print(np.isin(a5,b5))

[False  True]


#### 6. Check [2,4,6] in [1,3,5].

In [60]:
a6 = np.array([2,4,6])
b6 = np.array([1,3,5])
print(np.isin(a6,b6))

[False False False]


#### 7. Check membership of [-1,-2] in [-2,-3].

In [61]:
a7 = np.array( [-1,-2])
b7 = np.array([-2,-3])
print(np.isin(a7,b7))

[False  True]


#### 8. Check [0,1,2] in [2,3,4].

In [62]:
a8 = np.array([0,1,2] )
b8 = np.array([2,3,4])
print(np.isin(a8,b8))

[False False  True]


#### 9. Check [9,8,7] in [7,6,5].

In [63]:
a9 = np.array([9,8,7])
b9= np.array([7,6,5])
print(np.isin(a9,b9))

[False False  True]


#### 10. Check [11,12] in [12,13,14].

In [64]:
a10 = np.array([11,12])
b10 = np.array([12,13,14])
print(np.isin(a10,b10))

[False  True]
