# NumPy Vectorization Practice

In [1]:
import numpy as np 

#  1. Basic Math (Most Important)

#### Add 5 to every element in array a.

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a+5

array([5, 6, 7, 8, 9])

#### Multiply each element by 2

In [5]:
a*2

array([0, 2, 4, 6, 8])

#### Square all elements.

In [7]:
a**2

array([ 0,  1,  4,  9, 16])

#### Find cube of all elements.

In [8]:
a**3

array([ 0,  1,  8, 27, 64])

#### Subtract 10 from each element.

In [9]:
a-10

array([-10,  -9,  -8,  -7,  -6])

# 

# 2. Real Filtering

#### Get all numbers greater than 50.

In [10]:
np.random.seed(42)
arr = np.random.randint(10,100,10)
arr

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97], dtype=int32)

In [11]:
arr[arr>50]

array([61, 81, 70, 92, 96, 84, 84, 97], dtype=int32)

#### Get all even numbers.

In [12]:
arr[arr%2==0]

array([24, 70, 30, 92, 96, 84, 84], dtype=int32)

#### Get all even numbers.

In [13]:
arr[arr%2!=0]

array([61, 81, 97], dtype=int32)

#### Replace negative numbers with 0.

In [19]:
np.random.seed(42)
ar1 = np.random.randn(10)
ar1

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [20]:
ar1[ar1<0] = 0

In [21]:
ar1

array([0.49671415, 0.        , 0.64768854, 1.52302986, 0.        ,
       0.        , 1.57921282, 0.76743473, 0.        , 0.54256004])

#### Replace values below 30 with 30.

In [22]:
arr

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97], dtype=int32)

In [23]:
arr[arr<30] = 30

In [24]:
arr

array([61, 30, 81, 70, 30, 92, 96, 84, 84, 97], dtype=int32)

# 

# 3.Data Operations

#### Find mean of an array.`

In [25]:
np.mean(arr)

np.float64(72.5)

#### Find max and min of array.

In [26]:
print("Max :",np.max(arr))
print("Min : ",np.min(arr))

Max : 97
Min :  30


#### Find sum of all values.

In [27]:
print("Total :",np.sum(arr))

Total : 725


#### Find how many values are > 40.

In [28]:
arr[arr>40].size

8

#### Find percentage of values greater than 50.

In [30]:
counts = arr[arr>50].size
per = (counts /arr.size)*100
print(per,"%")

80.0 %


# 

# 4. Data Cleaning

#### Replace all NaN values with 0 in an array.

In [32]:
array_d = np.array([100,110,99,10,np.nan, 20,120,np.nan,111,np.nan])
array_d

array([100., 110.,  99.,  10.,  nan,  20., 120.,  nan, 111.,  nan])

In [34]:
np.where(np.isnan(array_d),0,array_d)

array([100., 110.,  99.,  10.,   0.,  20., 120.,   0., 111.,   0.])

In [35]:
array_d

array([100., 110.,  99.,  10.,  nan,  20., 120.,  nan, 111.,  nan])

In [36]:
array_d = np.where(np.isnan(array_d),0,array_d)

In [37]:
array_d

array([100., 110.,  99.,  10.,   0.,  20., 120.,   0., 111.,   0.])

#### Replace all values > 100 with 100 (cap values).

In [39]:
array_d[array_d>100] = 100

In [40]:
array_d

array([100., 100.,  99.,  10.,   0.,  20., 100.,   0., 100.,   0.])

#### Replace all values < 0 with mean of array.

In [47]:
np.random.seed(42)
new_arr = np.random.randint(-10,10,10)

In [48]:
new_arr

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7], dtype=int32)

In [49]:
new_arr[new_arr<0] = np.mean(new_arr[new_arr>0])

In [50]:
new_arr

array([7, 9, 4, 0, 7, 7, 8, 0, 0, 7], dtype=int32)

#### Remove negative values using filtering.

In [52]:
np.random.seed(42)
new_arr2 = np.random.randint(-10,10,10)
new_arr2

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7], dtype=int32)

In [53]:
result = new_arr2[new_arr2>=0]
result

array([9, 4, 0, 8, 0, 0], dtype=int32)

#### Replace all values divisible by 3 with -1.

In [55]:
np.random.seed(42)
arr2 = np.random.randint(1,100,10)
arr2

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75], dtype=int32)

In [56]:
arr2[arr2%3==0] = -1

In [57]:
arr2

array([52, -1, -1, -1, 61, -1, 83, -1, -1, -1], dtype=int32)