# NumPy Vectorization – Real-World Problems


In [2]:
import numpy as np

### PROBLEM SET 1: E-Commerce Pricing


In [6]:

# 50,000 products with [original_price, discount_percent, tax_rate]
products = np.random.rand(50000, 3)
products[:, 0] = products[:, 0] * 1000 + 10  # Price: $10-$1010
products[:, 1] = np.random.randint(0, 50, 50000)  # Discount: 0-50%
products[:, 2] = np.random.uniform(0.05, 0.15, 50000)  # Tax: 5-15%

print("Products shape:", products.shape)
print("First 5 products [price, discount%, tax%]:\n", products[:5])

Products shape: (50000, 3)
First 5 products [price, discount%, tax%]:
 [[9.35445874e+02 1.10000000e+01 8.67371435e-02]
 [4.38683401e+02 2.00000000e+00 1.10082115e-01]
 [3.49885374e+02 3.00000000e+01 8.44369824e-02]
 [1.96159116e+02 5.00000000e+00 9.12132546e-02]
 [5.65680536e+02 4.50000000e+01 7.91838058e-02]]


In [11]:
print(products[1,0])

438.68340133716555


#### Q1. Calculate discounted price: price * (1 - discount/100) for all 50,000 products at once.

In [19]:
discount_price = products[:,0] * (1-products[:,1]/100)
print("Fist 5 product discount price : ")
for dp in np.nditer(discount_price[:5]):
    print(np.round(dp,2))

Fist 5 product discount price : 
832.55
429.91
244.92
186.35
311.12


#### Q2. Calculate final price after tax: discounted price * (1 + tax rate).

In [21]:
tax = products[:, 2]
final_price = discount_price * (1 + tax)
final_price

array([904.75956193, 477.23510616, 265.60004713, ..., 549.72624234,
       672.92467429, 106.86326336])

#### Q3. Apply flash sale: products under $50 get additional 20% off. Update discounted price.

In [23]:
flash_mask = products[:,0] < 50
discount_price[flash_mask] *= 0.8
print(discount_price[:5])

[832.54682823 429.90973331 244.91976154 186.35116024 311.12429489]


#### Q4. Mark products as "High Value" if final price > $500, "Medium" if $100-500, "Low" if < $100.

In [28]:
ch = np.array(["High Value","mediaum value","Low value"])

condi = [ final_price > 500,
    (final_price >= 100) & (final_price <= 500),
    final_price < 100 ]
category = np.select(condi,ch,default="Unk")
category

array(['High Value', 'mediaum value', 'mediaum value', ..., 'High Value',
       'High Value', 'mediaum value'], dtype='<U13')

#### Q5. Calculate total revenue if all products sell 1 unit each.

In [29]:
total_revenue = np.sum(final_price)
print(total_revenue)

21262927.294067893


# 

# 

### PROBLEM SET 2: Weather Station Analysis

In [31]:
# 1000 weather stations × 365 days × 4 measurements
# Measurements: [temp_min, temp_max, humidity, rainfall_mm]
weather = np.random.rand(1000, 365, 4)
weather[:, :, 0] = weather[:, :, 0] * 30 + (-5)  # Min temp: -5 to 25°C
weather[:, :, 1] = weather[:, :, 1] * 25 + 10   # Max temp: 10-35°C
weather[:, :, 2] = weather[:, :, 2] * 70 + 20   # Humidity: 20-90%
weather[:, :, 3] = weather[:, :, 3] * 50        # Rainfall: 0-50mm

print("Weather shape:", weather.shape)
print("Station 0, Day 0 [min_temp, max_temp, humidity, rain]:", weather[0, 0])

Weather shape: (1000, 365, 4)
Station 0, Day 0 [min_temp, max_temp, humidity, rain]: [-4.72387702 28.7829653  71.44054609  1.35118493]


#### Q6. Calculate daily average temperature: (min_temp + max_temp) / 2 for all stations, all days.

In [33]:
avg_temp = (weather[...,0] + weather[...,1]) /2
np.round(avg_temp,2)

array([[12.03, 21.93, 21.08, ..., 24.4 , 14.84, 18.07],
       [18.28, 13.61, 19.64, ..., 11.68, 12.93, 15.47],
       [13.16, 10.48, 12.77, ..., 12.09, 10.27, 15.03],
       ...,
       [21.92, 20.73, 22.51, ..., 18.33, 16.18, 13.23],
       [24.23, 12.24, 14.99, ..., 13.17, 18.  , 18.28],
       [17.44, 14.  , 21.31, ..., 19.99,  4.68, 17.35]])

#### Q7. Flag heatwave days: max_temp > 30 AND min_temp > 20 for any station.

###### When both day and night are hot for multiple days, it is called a heatwave.

In [34]:
max_temp = weather[...,0]
min_temp = weather[...,1]
heatwave = (max_temp > 30) & (min_temp > 20)

print(heatwave.shape)
print(heatwave[0][:10])

(1000, 365)
[False False False False False False False False False False]


#### Q8. Calculate total annual rainfall per station (sum across days).

###### Rainfall means how much rain falls in a place, measured in millimeters

In [37]:
rainfall = weather[...,3]
annual_rainfall = np.sum(rainfall,axis=1)

In [38]:
print(annual_rainfall[:5])    # first 5 stations

[9036.55234011 9087.47418101 8543.93303592 8909.99194134 9233.87995926]


In [39]:
rainfall[:5]

array([[ 1.35118493,  7.64679171, 41.89597739, ..., 12.59255273,
        27.40159494, 19.40455976],
       [26.57544991,  7.99259897, 17.43813176, ..., 13.5566462 ,
        24.7121842 , 39.24219141],
       [39.28780375, 14.52987991, 46.85268658, ...,  0.80457132,
        12.69315702, 25.9744078 ],
       [ 4.49835337, 27.254388  , 37.18708056, ...,  9.34818016,
         0.60414553, 16.55269714],
       [36.93565978,  3.17564166,  1.40080646, ..., 29.5222769 ,
         5.94753969, 47.4296518 ]])

#### Q9. Find stations with average humidity > 75%.

In [40]:
humidity = weather[:, :, 2]
avg_humidity = np.mean(humidity, axis=1)
high_humidity_stations = np.where(avg_humidity > 75)[0]

print("Stations with high humidity:", high_humidity_stations)
print("Count:", len(high_humidity_stations))

Stations with high humidity: []
Count: 0


# 

# 

### PROBLEM SET 3: Student Grades Processing

In [42]:
# 10,000 students × 6 subjects × 3 exams
# Exams: [quiz1, quiz2, final]
grades = np.random.randint(40, 100, size=(10000, 6, 3))
weights = np.array([0.2, 0.2, 0.6])  # Quiz1 20%, Quiz2 20%, Final 60%

print("Grades shape:", grades.shape)
print("First student's grades (6 subjects × 3 exams):\n", grades[0])

Grades shape: (10000, 6, 3)
First student's grades (6 subjects × 3 exams):
 [[90 84 74]
 [74 49 74]
 [79 60 40]
 [61 64 82]
 [66 74 78]
 [92 96 99]]


#### Q11. Calculate weighted final grade for each student, each subject using vectorization.

In [44]:
weighted = grades * weights
final_scores = np.sum(weighted, axis=2)
print(final_scores[0]) # student 1st

[79.2 69.  51.8 74.2 74.8 97. ]


#### Q12. Calculate overall grade (average across all subjects) for each student.

In [45]:
overall_grade = np.mean(final_scores,axis=1)
overall_grade

array([74.33333333, 72.06666667, 67.8       , ..., 63.86666667,
       78.03333333, 68.23333333])

#### Q13. Identify students who failed any subject (grade < 60).

In [46]:
failed_st = np.where(final_scores<60)[0]
print("First 10 Failed studensts : ",failed_st[:10])

First 10 Failed studensts :  [0 1 2 2 4 4 5 5 5 6]


In [47]:
failed_st = np.unique(np.where(final_scores < 60)[0])
print("First 10 Failed studensts : ",failed_st[:10])

First 10 Failed studensts :  [ 0  1  2  4  5  6  7  8  9 10]


#### Q14. Calculate class average for each subject (mean across all students).

In [48]:
subject_average = np.mean(final_scores, axis=0)

print(subject_average.shape)  
print(subject_average)

(6,)
[69.50838 69.6543  69.42714 69.35442 69.34768 69.68988]


# 