# NumPy Searching Functions – Simple Assignments


### 1: np.where()
Returns indices where condition is True.

In [1]:
import numpy as np

In [2]:
scores = np.array([85, 42, 97, 63, 78, 51, 89, 34, 76, 91, 42, 88, 42, 95, 67])
indeces = np.arange(15)
print("Scores:", scores)
print("Indices:", indeces)

Scores: [85 42 97 63 78 51 89 34 76 91 42 88 42 95 67]
Indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Q1. Find all indices where score is exactly 42 using np.where().

In [3]:
result_index = np.where(scores==42,indeces,np.nan)
result_index

array([nan,  1., nan, nan, nan, nan, nan, nan, nan, nan, 10., nan, 12.,
       nan, nan])

In [4]:
result_index[~np.isnan(result_index)]


array([ 1., 10., 12.])

In [5]:
np.where(scores==42)

(array([ 1, 10, 12]),)

#### Q2. Find all indices where score is greater than 80.

In [6]:
result_index2 = np.where(scores>80,indeces,np.nan)
result_index2[~np.isnan(result_index2)]


array([ 0.,  2.,  6.,  9., 11., 13.])

In [7]:
np.where(scores>80)

(array([ 0,  2,  6,  9, 11, 13]),)

#### Q3. Find all indices where score is between 70 and 90 (inclusive)

In [8]:
condition = np.logical_and(scores>70 ,scores<90)
re_index3 = np.where(condition,indeces,np.nan)

In [9]:
re_index3[~np.isnan(re_index3)]

array([ 0.,  4.,  6.,  8., 11.])

In [10]:
np.where((scores>70) &(scores<90))

(array([ 0,  4,  6,  8, 11]),)

#### Q4. Find all indices where score is less than 50 or greater than 90.

In [11]:
condition1 = np.logical_or(scores<50 ,scores>90)
re_index4 = np.where(condition1,indeces,np.nan)

In [12]:
re_index4[~np.isnan(re_index4)]

array([ 1.,  2.,  7.,  9., 10., 12., 13.])

In [13]:
np.where((scores<50)|(scores>90))

(array([ 1,  2,  7,  9, 10, 12, 13]),)

#### Q5. Replace all scores below 60 with 60 using np.where().

In [14]:
scores2 = scores.copy()

In [15]:
np.where(scores2<60,60,scores2)

array([85, 60, 97, 63, 78, 60, 89, 60, 76, 91, 60, 88, 60, 95, 67])

In [16]:
scores2

array([85, 42, 97, 63, 78, 51, 89, 34, 76, 91, 42, 88, 42, 95, 67])

### 2: np.nonzero()
Returns indices of non-zero elements.



In [17]:
data = np.array([0, 5, 0, 0, 8, 0, 12, 0, 0, 3, 0, 7, 0, 0, 9])
print("Data:", data)
print("Indices:", np.arange(15))

Data: [ 0  5  0  0  8  0 12  0  0  3  0  7  0  0  9]
Indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Q6. Find all indices where value is non-zero using np.nonzero().

In [18]:
non_zero_in = np.nonzero(data)
non_zero_in

(array([ 1,  4,  6,  9, 11, 14]),)

#### Q7. Count how many zeros are in the array using np.nonzero().

In [19]:
 re_data = np.nonzero(data

_IncompleteInputError: incomplete input (2327028313.py, line 1)

#### Q8. Extract all non-zero values into a new array.

In [20]:
data[np.nonzero(data)]

array([ 5,  8, 12,  3,  7,  9])

#### Q9. Find indices where value is zero (use complement of nonzero).

#### Q10. Replace all non-zero values with 1 (keep zeros as 0) using np.nonzero().

In [21]:
data1 = data.copy()
data1

array([ 0,  5,  0,  0,  8,  0, 12,  0,  0,  3,  0,  7,  0,  0,  9])

In [22]:
data1[np.nonzero(data1)] = 1

In [23]:
data1

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

### 3: np.argmax() / np.argmin()
Returns index of maximum/minimum value.

In [24]:
temperatures = np.array([23, 19, 31, 28, 22, 35, 29, 26, 33, 27, 30, 24, 32, 21, 34])
print("Temperatures:", temperatures)
print("Days (indices):", np.arange(15))

Temperatures: [23 19 31 28 22 35 29 26 33 27 30 24 32 21 34]
Days (indices): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Q11. Find the index of the highest temperature using np.argmax().

In [25]:
print(np.argmax(temperatures))

5


#### Q12. Find the index of the lowest temperature using np.argmin().

In [26]:
print(np.argmin(temperatures))

1


#### Q13. Find the value of the highest temperature (use argmax result).


In [27]:
print(temperatures[np.argmax(temperatures)])

35


#### Q14. Find the index of the 2nd highest temperature (hint: set max to -inf and find again).

In [28]:
temp2 = temperatures.copy()
temp2

array([23, 19, 31, 28, 22, 35, 29, 26, 33, 27, 30, 24, 32, 21, 34])

In [29]:
temp2[np.argmax(temp2)] = 0

In [30]:
print("Index of the 2nd highest temperature : ",np.argmax(temp2))

Index of the 2nd highest temperature :  14


#### Q15. Find the day (index) where temperature is closest to 25°C.

In [31]:
s

NameError: name 's' is not defined

### 4: np.searchsorted()

In [ ]:
sorted_ages = np.array([18, 21, 25, 27, 30, 32, 35, 38, 40, 45, 50, 55, 60])
print("Sorted ages:", sorted_ages)

#### Q16. Find the index where 26 should be inserted to maintain sorted order.

In [ ]:
data = np.searchsorted(sorted_ages,26)

In [ ]:
print(data)

#### Q17. Find the index where 33 should be inserted using np.searchsorted().

In [ ]:
print(np.searchsorted(sorted_ages,33))

#### Q18. Insert multiple values [22, 28, 42] at once and find their positions.

In [ ]:
print(np.searchsorted(sorted_ages,[22,28,42]))

#### Q19. Use side='right' to insert 30 and see the difference from default side='left'.

In [ ]:
print("Left side : ",np.searchsorted(sorted_ages,30,side='left'))
print("Right side : ",np.searchsorted(sorted_ages,30,side='right'))

#### Q20. Find how many ages are less than 35 using np.searchsorted().

In [ ]:
print(np.searchsorted(sorted_ages,35,side='left'))

In [ ]:
sorted_ages

### 5: np.extract()
Extracts elements that satisfy a condition.



In [ ]:
expenses = np.array([120, 45, 200, 80, 350, 65, 180, 95, 420, 150, 75, 290, 110, 55, 400])
print("Expenses:", expenses)

#### Q21. Extract all expenses greater than 200 using np.extract().

In [32]:
np.extract(expenses>200,expenses)

NameError: name 'expenses' is not defined

#### Q22. Extract all expenses between 100 and 250 (inclusive).

In [33]:
np.extract(((expenses>100 ) & (expenses<250)),expenses)

NameError: name 'expenses' is not defined

#### 23. Extract all expenses that are even numbers.

In [34]:
np.extract(expenses%2== 0,expenses)

NameError: name 'expenses' is not defined

#### Q24. Extract expenses that are less than 50 or greater than 300.

In [35]:
np.extract(((expenses<50 )  |(expenses>300)),expenses)

NameError: name 'expenses' is not defined

#### Q25. Extract expenses and their indices using np.where() (not extract).

In [36]:
indices = np.where(expenses>200)
print("Indices  : ",indices)
print("Expenses : ",expenses[indices])


NameError: name 'expenses' is not defined

### BONUS: 2D Array Searching


In [37]:
matrix = np.array([
    [5, 8, 3, 9],
    [2, 7, 6, 4],
    [8, 1, 9, 5],
    [3, 6, 2, 8]
])
print("Matrix:\n", matrix)

Matrix:
 [[5 8 3 9]
 [2 7 6 4]
 [8 1 9 5]
 [3 6 2 8]]


#### Q26. Find all indices where value equals 8 using np.where() (returns row and col).

In [38]:
rows,cols = np.where(matrix ==8)
print("Rows : ",rows)
print("Columns : ",cols)

Rows :  [0 2 3]
Columns :  [1 0 3]


#### Q27. Find all rows that contain the number 9.

In [39]:
np.where(matrix==9)[0]

array([0, 2])

#### Q28. Find the column index of maximum value in each row using np.argmax().

In [40]:
np.argmax(matrix,axis=1)

array([3, 1, 2, 3])

#### Q29. Find the row index of minimum value in each column using np.argmin().

In [41]:
np.argmax(matrix,axis=0)

array([2, 0, 2, 0])

#### Q30. Find all elements greater than 5 and replace them with 0 using np.where().


In [42]:
m2 = matrix.copy()
m2

array([[5, 8, 3, 9],
       [2, 7, 6, 4],
       [8, 1, 9, 5],
       [3, 6, 2, 8]])

In [43]:
m2 = np.where(m2>5,0,m2)
m2

array([[5, 0, 3, 0],
       [2, 0, 0, 4],
       [0, 1, 0, 5],
       [3, 0, 2, 0]])

###  REAL-WORLD SCENARIO: Customer Data Search

In [44]:
# 1000 customers with [CustomerID, Age, PurchaseAmount, Satisfaction_1-5]
np.random.seed(42)
customers = np.random.randint(1000, 5000, size=(1000, 4))
customers[:, 1] = np.random.randint(18, 80, 1000)  # Age
customers[:, 2] = np.random.randint(10, 1000, 1000)  # Purchase amount
customers[:, 3] = np.random.randint(1, 6, 1000)  # Satisfaction

print("Customers shape:", customers.shape)
print("First 5 customers [ID, Age, Purchase, Satisfaction]:\n", customers[:5])

Customers shape: (1000, 4)
First 5 customers [ID, Age, Purchase, Satisfaction]:
 [[4174   23  903    4]
 [2130   63  576    2]
 [2638   23   36    1]
 [1330   51  639    5]
 [4171   18  742    4]]


#### Q31. Find all customers with satisfaction score of 5 using np.where().

In [45]:
satisfy_cust = np.where(customers[:,3]==5) # return row indices
satisfy_cust

(array([  3,   7,  17,  27,  31,  45,  47,  51,  55,  67,  76,  83,  87,
         89,  99, 106, 108, 117, 118, 119, 123, 126, 131, 139, 140, 144,
        145, 153, 154, 157, 160, 167, 168, 169, 171, 173, 175, 196, 205,
        209, 212, 213, 215, 216, 217, 220, 221, 227, 234, 236, 237, 245,
        252, 257, 260, 272, 275, 276, 278, 281, 301, 307, 308, 313, 316,
        321, 325, 329, 330, 334, 335, 339, 358, 360, 362, 364, 368, 372,
        378, 379, 380, 382, 387, 388, 393, 398, 400, 403, 406, 407, 413,
        417, 426, 427, 428, 433, 434, 439, 447, 449, 451, 461, 466, 468,
        481, 493, 494, 496, 505, 511, 514, 519, 523, 526, 531, 544, 547,
        551, 557, 558, 560, 567, 577, 580, 587, 593, 595, 607, 608, 611,
        613, 620, 623, 627, 629, 638, 639, 643, 647, 648, 654, 659, 664,
        668, 669, 673, 677, 679, 681, 683, 684, 692, 706, 720, 721, 722,
        724, 725, 733, 743, 752, 776, 788, 796, 809, 814, 815, 818, 823,
        826, 833, 843, 844, 846, 847, 848, 850, 851

In [46]:
customers[17,3]

np.int32(5)

In [47]:
customers[satisfy_cust,3]

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]], dtype=int32)

#### Q32. Find customers aged 25-35 with purchase amount > 500.

In [48]:
cond1 = ((customers[:,1]>25 )& (customers[:,1]<35))
cond2 = customers[:,2]>500
result = np.where(np.logical_and(cond1,cond2)) #return row indices
result

(array([ 13,  45,  82,  83,  94, 105, 108, 136, 137, 140, 187, 218, 221,
        223, 229, 260, 263, 265, 269, 317, 333, 368, 370, 384, 386, 399,
        401, 426, 445, 469, 497, 507, 510, 511, 524, 565, 571, 574, 576,
        577, 581, 601, 628, 641, 671, 705, 737, 745, 755, 785, 808, 820,
        824, 864, 880, 891, 906, 937, 939, 951, 954, 963, 982, 998]),)

In [49]:
customers[result,0]# customers id 

array([[1562, 3690, 4397, 1659, 4062, 1815, 1954, 3518, 1833, 3361, 3808,
        4486, 4522, 3523, 3719, 4636, 1684, 3081, 1235, 3275, 1946, 2692,
        3597, 1814, 4005, 2332, 4874, 4451, 3308, 2394, 4853, 4598, 2449,
        1310, 3632, 3808, 2136, 2349, 4902, 2245, 4977, 4234, 2949, 1894,
        2646, 1085, 3474, 2179, 3606, 2585, 1834, 1265, 4507, 3601, 2674,
        1189, 2927, 1870, 1940, 3160, 4896, 3757, 4921, 4001]],
      dtype=int32)

#### Q33. Find the customer with maximum purchase amount (return full row).

In [50]:
max_cust  =  np.argmax(customers[:,2])

In [51]:
print(customers[max_cust,:])

[1954   58  999    3]


#### Q34. Find the youngest customer (minimum age) using np.argmin().

In [52]:
min_age = np.argmin(customers[:,1])

In [53]:
print(customers[min_age,:])

[4171   18  742    4]


#### Q35. Find how many customers have age > 60 and purchase < 200.

In [54]:
resu_cust = np.where(np.logical_and(customers[:,1]>60,customers[:,2]<200))
print("Customers : ",resu_cust[0].size)

Customers :  64
