# Data Cleaning Practice 2

In [2]:
import pandas as pd

In [36]:
import numpy as np

In [3]:
data = pd.read_csv('messy_data1.csv')

In [4]:
df = data.copy(deep=True)

# 

# 

In [6]:
df.head()

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
0,1,Renee Wilson,twenty five,NaN,HR,Mumbai,male,NaN,0292140937,2025-10-17,NaN,9.0
1,2,Thomas Morgan,150,not disclosed,Marketing,Bangalore,Female,NaN,NaN,32-13-2024,NaN,2.0
2,3,Whitney Harmon,twenty five,78391.23,it,Mumbai,F,brent13@hotmail.com,+91-1007997806,32-13-2024,NaN,NaN
3,4,Edward Cowan,NaN,96172.18,Sales,Mumbai,F,NaN,NaN,32-13-2024,NaN,15.0
4,5,Brian Moore,59,NaN,finance,Pune,Female,NaN,NaN,32-13-2024,NaN,6.0


In [7]:
df.tail()

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
1045,278,Monica Garcia,NaN,-5000,Sales,Bangalore,NaN,NaN,NaN,2021-12-09,NaN,15.0
1046,925,Terry Obrien,42,not disclosed,HR,NaN,male,NaN,+91-6044344922,NaN,NaN,1.0
1047,602,Linda Hogan,twenty five,21747.56,Sales,MUMBAI,F,sharonfrye@hotmail.com,0705855628,2022-05-03,5.3,10.0
1048,440,Laurie Cooper,twenty five,NaN,Support,MUMBAI,male,invalid_email,+91-5153200843,32-13-2024,2.4,NaN
1049,838,Robert Knight,60,NaN,Marketing,Hyderabad,Male,NaN,12345,2024-01-12,NaN,15.0


# 

In [8]:
df.sample(10)

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
444,445,Joseph Peters,150,not disclosed,NaN,MUMBAI,M,invalid_email,NaN,NaN,2.8,NaN
297,298,Chris Jackson,150,NaN,Finance,NaN,F,mccartyjennifer@gmail.com,+91-1322620438,2022-09-04,-2.0,3.0
6,7,James Roberts,150,NaN,Finance,MUMBAI,Male,kguzman@wood-mccarty.org,0530826576,NaN,-2.0,10.0
847,848,Allison Mitchell,NaN,NaN,Support,Delhi,M,ashley76@yahoo.com,3621641197,NaN,-2.0,NaN
806,807,Nancy Friedman,twenty five,46768.62,Sales,bangalore,F,NaN,NaN,32-13-2024,NaN,9.0
675,676,Lauren Williams,150,NaN,it,Mumbai,Male,invalid_email,NaN,2025-08-03,-2.0,NaN
225,226,Douglas Wallace,NaN,31894.97,finance,Mumbai,M,hansenfrancis@gmail.com,+91-7690111839,NaN,-2.0,NaN
726,727,Frank Burke,150,NaN,Marketing,Mumbai,Male,NaN,12345,NaN,NaN,NaN
521,522,Lisa Davidson,150,NaN,Finance,Bangalore,Male,parkerkevin@gmail.com,+91-3019805633,32-13-2024,NaN,7.0
995,996,James Carlson,150,not disclosed,Support,Pune,M,NaN,+91-8279295720,NaN,12.7,8.0


# 

In [9]:
df.dtypes

Employee_ID            int64
Name                  object
Age                   object
Salary                object
Department            object
City                  object
Gender                object
Email                 object
Phone                 object
Join_Date             object
Experience_Years     float64
Performance_Score    float64
dtype: object

# 

In [10]:
df.describe(include='all')

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
count,1050.000000,995,609,634,930,919,867,610,621,549,509.000000,552.000000
unique,NaN,946,45,194,8,7,5,391,401,252,NaN,NaN
top,NaN,Jennifer Adams,150,-5000,Sales,Pune,M,invalid_email,12345,32-13-2024,NaN,NaN
freq,NaN,3,222,233,131,147,189,201,196,262,NaN,NaN
mean,502.380952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.029666,10.449275
std,288.838378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.383420,5.036451
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.000000,1.000000
25%,253.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.000000,6.000000
50%,503.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.000000,15.000000
75%,751.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.800000,15.000000


In [11]:
df.describe()

,Employee_ID,Experience_Years,Performance_Score
count,1050.000000,509.000000,552.000000
mean,502.380952,4.029666,10.449275
std,288.838378,7.383420,5.036451
min,1.000000,-2.000000,1.000000
25%,253.250000,-2.000000,6.000000
50%,503.500000,-2.000000,15.000000
75%,751.750000,9.800000,15.000000
max,1000.000000,19.900000,15.000000


In [12]:
df.isnull().sum()

Employee_ID            0
Name                  55
Age                  441
Salary               416
Department           120
City                 131
Gender               183
Email                440
Phone                429
Join_Date            501
Experience_Years     541
Performance_Score    498
dtype: int64

In [14]:
df.isnull().mean()*100

Employee_ID           0.000000
Name                  5.238095
Age                  42.000000
Salary               39.619048
Department           11.428571
City                 12.476190
Gender               17.428571
Email                41.904762
Phone                40.857143
Join_Date            47.714286
Experience_Years     51.523810
Performance_Score    47.428571
dtype: float64

# 

In [15]:
df.duplicated().sum()

np.int64(50)

# 

## #Cleaninig

In [18]:
df['Employee_ID'].duplicated().sum()

np.int64(50)

In [19]:
df[df['Employee_ID'].duplicated()]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
1000,522,Lisa Davidson,150,NaN,Finance,Bangalore,Male,parkerkevin@gmail.com,+91-3019805633,32-13-2024,NaN,7.0
1001,738,David Rodriguez,58,NaN,Finance,Pune,F,NaN,NaN,32-13-2024,-2.0,15.0
1002,741,Debra Martin,twenty five,-5000,Support,MUMBAI,NaN,invalid_email,NaN,32-13-2024,18.5,NaN
1003,661,Amber Bradshaw,twenty five,NaN,Support,Mumbai,M,NaN,NaN,32-13-2024,16.2,NaN
1004,412,Miranda Lewis,NaN,60786.06,finance,Pune,Male,NaN,NaN,2025-05-04,NaN,15.0
1005,679,Christopher Walls,NaN,42596.88,IT,Pune,NaN,jasonfarrell@gmail.com,0335031521,NaN,NaN,NaN
1006,627,Jake Combs,NaN,NaN,it,Mumbai,male,NaN,+91-0308589694,32-13-2024,11.0,NaN
1007,514,Catherine Smith,NaN,NaN,HR,Pune,F,NaN,NaN,32-13-2024,NaN,3.0
1008,860,Molly Garcia,twenty five,97951.69,Sales,MUMBAI,Male,NaN,6501859347,NaN,NaN,NaN
1009,137,NaN,NaN,not disclosed,it,Pune,M,NaN,NaN,2025-07-13,18.2,NaN


In [20]:
df[df['Employee_ID']== 522]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
521,522,Lisa Davidson,150,NaN,Finance,Bangalore,Male,parkerkevin@gmail.com,+91-3019805633,32-13-2024,NaN,7.0
1000,522,Lisa Davidson,150,NaN,Finance,Bangalore,Male,parkerkevin@gmail.com,+91-3019805633,32-13-2024,NaN,7.0


In [21]:
df[df['Employee_ID']== 412]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
411,412,Miranda Lewis,NaN,60786.06,finance,Pune,Male,NaN,NaN,2025-05-04,NaN,15.0
1004,412,Miranda Lewis,NaN,60786.06,finance,Pune,Male,NaN,NaN,2025-05-04,NaN,15.0


# 

In [23]:
df = df.drop_duplicates(subset='Employee_ID')

In [24]:
df['Employee_ID'].duplicated().sum()

np.int64(0)

# 

In [25]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [26]:
df['Age'].unique()

array(['twenty five', '150', nan, '59', '49', '32', '39', '50', '22',
       '20', '27', '47', '37', '36', '56', '34', '51', '46', '41', '26',
       '21', '54', '25', '23', '33', '40', '35', '19', '38', '42', '53',
       '58', '24', '44', '48', '43', '30', '18', '57', '31', '55', '29',
       '45', '60', '28', '52'], dtype=object)

In [27]:
df['Age'] = df['Age'].str.replace('twenty five','25')

In [29]:
df['Age'].unique()

array(['25', '150', nan, '59', '49', '32', '39', '50', '22', '20', '27',
       '47', '37', '36', '56', '34', '51', '46', '41', '26', '21', '54',
       '23', '33', '40', '35', '19', '38', '42', '53', '58', '24', '44',
       '48', '43', '30', '18', '57', '31', '55', '29', '45', '60', '28',
       '52'], dtype=object)

In [30]:
df['Age'] = df['Age'].astype('Int64')

In [31]:
df['Age'].unique()

<IntegerArray>
[  25,  150, <NA>,   59,   49,   32,   39,   50,   22,   20,   27,   47,   37,
   36,   56,   34,   51,   46,   41,   26,   21,   54,   23,   33,   40,   35,
   19,   38,   42,   53,   58,   24,   44,   48,   43,   30,   18,   57,   31,
   55,   29,   45,   60,   28,   52]
Length: 45, dtype: Int64

In [35]:
df['Age'].isnull().sum()

np.int64(418)

# 

# 

In [38]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [39]:
df['Salary'].unique()

array([nan, 'not disclosed', '78391.23', '96172.18', '57122.3', '-5000',
       '104390.97', '80431.32', '25771.7', '22778.63', '33250.42',
       '78389.93', '63507.52', '106600.22', '19829.05', '46671.18',
       '49612.83', '30840.41', '91958.81', '27876.93', '41031.48',
       '49780.16', '19416.98', '40124.62', '71822.17', '36638.57',
       '19152.49', '86824.37', '74414.95', '71914.55', '105855.5',
       '37409.22', '24379.76', '91958.26', '85699.2', '26442.15',
       '87059.95', '82162.91', '41201.79', '72332.52', '31894.97',
       '34019.27', '46327.35', '81622.39', '83624.6', '46617.23',
       '85521.48', '100383.73', '100795.85', '73498.76', '56486.89',
       '115526.12', '82690.82', '53205.88', '53033.41', '104774.89',
       '36032.59', '31379.53', '63005.58', '31350.34', '77685.39',
       '112739.12', '112482.39', '115781.57', '23240.13', '28879.85',
       '94562.05', '71476.26', '83594.07', '103547.51', '66188.21',
       '49216.32', '115367.76', '65560.96', '4202

In [40]:
df['Salary'] = pd.to_numeric(df['Salary'],errors='coerce')

In [41]:
df['Salary'].unique()

array([      nan,  78391.23,  96172.18,  57122.3 ,  -5000.  , 104390.97,
        80431.32,  25771.7 ,  22778.63,  33250.42,  78389.93,  63507.52,
       106600.22,  19829.05,  46671.18,  49612.83,  30840.41,  91958.81,
        27876.93,  41031.48,  49780.16,  19416.98,  40124.62,  71822.17,
        36638.57,  19152.49,  86824.37,  74414.95,  71914.55, 105855.5 ,
        37409.22,  24379.76,  91958.26,  85699.2 ,  26442.15,  87059.95,
        82162.91,  41201.79,  72332.52,  31894.97,  34019.27,  46327.35,
        81622.39,  83624.6 ,  46617.23,  85521.48, 100383.73, 100795.85,
        73498.76,  56486.89, 115526.12,  82690.82,  53205.88,  53033.41,
       104774.89,  36032.59,  31379.53,  63005.58,  31350.34,  77685.39,
       112739.12, 112482.39, 115781.57,  23240.13,  28879.85,  94562.05,
        71476.26,  83594.07, 103547.51,  66188.21,  49216.32, 115367.76,
        65560.96,  42020.34,  96609.9 ,  60786.06,  18889.48,  66333.94,
       100869.02, 112195.93,  83002.22, 114971.  , 

In [43]:
 df[df['Salary']< 0]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
7,8,Victoria Williams,<NA>,-5000.0,IT,Mumbai,NaN,zwarren@gmail.com,NaN,32-13-2024,-2.0,NaN
8,9,NaN,150,-5000.0,HR,Hyderabad,NaN,kimberlykelly@gmail.com,+91-6295011236,NaN,NaN,9.0
10,11,Kara House,150,-5000.0,NaN,Pune,male,invalid_email,NaN,NaN,NaN,NaN
11,12,Ana Werner,32,-5000.0,finance,Pune,male,invalid_email,9812677862,2022-07-14,14.2,4.0
19,20,Tony Sanchez,22,-5000.0,HR,Mumbai,male,invalid_email,+91-9084592467,32-13-2024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
976,977,Bryan Fisher,<NA>,-5000.0,IT,Bangalore,NaN,invalid_email,NaN,2026-01-09,NaN,NaN
978,979,Kelly Kelley,25,-5000.0,Support,Delhi,F,invalid_email,12345,2023-09-14,NaN,15.0
993,994,Jennifer Terry,30,-5000.0,HR,MUMBAI,Female,huynhhayley@gmail.com,NaN,NaN,NaN,4.0
997,998,NaN,49,-5000.0,HR,Mumbai,Female,richardcox@shaw.com,NaN,NaN,NaN,NaN


In [44]:
df.loc[df['Salary'] < 0, 'Salary'] = np.nan

In [45]:
 df[df['Salary']< 0]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score


# 

# 

In [47]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [48]:
df['Department'].unique()

array(['HR', 'Marketing', 'it', 'Sales', 'finance ', 'Finance', 'IT', nan,
       'Support'], dtype=object)

In [49]:
df['Department'].str.lower().unique()

array(['hr', 'marketing', 'it', 'sales', 'finance ', 'finance', nan,
       'support'], dtype=object)

In [51]:
df['Department'].str.strip().str.lower().unique()

array(['hr', 'marketing', 'it', 'sales', 'finance', nan, 'support'],
      dtype=object)

In [52]:
df['Department'] = df['Department'].str.strip().str.title()

In [53]:
df['Department'].unique()

array(['Hr', 'Marketing', 'It', 'Sales', 'Finance', nan, 'Support'],
      dtype=object)

In [54]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [55]:
df['Department'].unique()

array(['Hr', 'Marketing', 'It', 'Sales', 'Finance', 'Support'],
      dtype=object)

# 

# 

In [57]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [58]:
df['City'].unique()

array(['Mumbai', 'Bangalore', 'Pune', nan, 'MUMBAI', 'Hyderabad', 'Delhi',
       'bangalore'], dtype=object)

In [59]:
df['City'].str.strip().str.title().unique()

array(['Mumbai', 'Bangalore', 'Pune', nan, 'Hyderabad', 'Delhi'],
      dtype=object)

In [60]:
df['City'] = df['City'].str.strip().str.title()

In [61]:
df['City'].isnull().sum()

np.int64(127)

In [62]:
df['City'] = df.groupby('Department')['City'].transform(lambda x: x.fillna(x.mode()[0]))

In [63]:
df['City'].isnull().sum()

np.int64(0)

# 

# 

In [64]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [66]:
df['Gender'].unique()

array(['male ', 'Female', 'F', 'Male', nan, 'M'], dtype=object)

In [67]:
df['Gender'] = df['Gender'].str.strip().str.title()

In [68]:
df['Gender'].unique()

array(['Male', 'Female', 'F', nan, 'M'], dtype=object)

In [71]:
df['Gender'].map({'F':'Female', 'M':'Male'}).unique()

array([nan, 'Female', 'Male'], dtype=object)

In [72]:
df['Gender'] = df['Gender'].map({'F':'Female', 'M':'Male'})

In [73]:
df['Gender'].unique()

array([nan, 'Female', 'Male'], dtype=object)

In [74]:
df['Gender'] = df.groupby(['Department', 'City'])['Gender'].transform(
               lambda x: x.fillna( x.mode()[0] if not x.mode().empty else np.nan))

In [75]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

# 

# 

In [76]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [78]:
df['Email'] = df['Email'].str.strip().str.lower()

In [80]:
df[df['Email'] == 'invalid_email']

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
9,10,Heather Cardenas,49,NaN,Marketing,Pune,Female,invalid_email,+91-4934430535,2024-09-07,-2.0,NaN
10,11,Kara House,150,NaN,Finance,Pune,Male,invalid_email,NaN,NaN,NaN,NaN
11,12,Ana Werner,32,NaN,Finance,Pune,Male,invalid_email,9812677862,2022-07-14,14.2,4.0
12,13,Deborah Hall,39,NaN,It,Pune,Male,invalid_email,+91-8351905724,NaN,-2.0,NaN
19,20,Tony Sanchez,22,NaN,Hr,Mumbai,Female,invalid_email,+91-9084592467,32-13-2024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
961,962,Jasmine Rhodes,25,NaN,It,Mumbai,Female,invalid_email,12345,NaN,8.4,15.0
963,964,Charles Myers,30,NaN,Marketing,Hyderabad,Female,invalid_email,NaN,NaN,NaN,8.0
976,977,Bryan Fisher,<NA>,NaN,It,Bangalore,Female,invalid_email,NaN,2026-01-09,NaN,NaN
978,979,Kelly Kelley,25,NaN,Support,Delhi,Female,invalid_email,12345,2023-09-14,NaN,15.0


In [84]:
df['Email'].replace('invalid_email',np.nan)

0                            NaN
1                            NaN
2            brent13@hotmail.com
3                            NaN
4                            NaN
                 ...            
995                          NaN
996     meyerstephanie@gmail.com
997          richardcox@shaw.com
998        rosariomark@yahoo.com
999    porteranthony@miller.info
Name: Email, Length: 1000, dtype: object

In [85]:
df['Email'] = df['Email'].replace('invalid_email',np.nan)

In [86]:
df['Email'].isnull().mean()

np.float64(0.609)

# 

# 

In [89]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [93]:
df['Phone'].head(10)

0        0292140937
1               NaN
2    +91-1007997806
3               NaN
4               NaN
5               NaN
6        0530826576
7               NaN
8    +91-6295011236
9    +91-4934430535
Name: Phone, dtype: object

In [94]:
df['Phone'] = df['Phone'].str.strip()

In [95]:
df['Phone'] = df['Phone'].str.replace(r'\D','',regex=True)

In [96]:
df['Phone'] = df['Phone'].str[-10:]

In [98]:
df[df['Phone'].duplicated()].tail()

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
989,990,Nicholas Maldonado,<NA>,NaN,Finance,Mumbai,Female,mary03@gmail.com,NaN,32-13-2024,19.2,15.0
992,993,Daniel Morrison,25,NaN,Finance,Bangalore,Female,greenandrew@gmail.com,NaN,NaN,13.8,NaN
993,994,Jennifer Terry,30,NaN,Hr,Mumbai,Female,huynhhayley@gmail.com,NaN,NaN,NaN,4.0
997,998,NaN,49,NaN,Hr,Mumbai,Female,richardcox@shaw.com,NaN,NaN,NaN,NaN
998,999,NaN,150,NaN,Sales,Bangalore,Female,rosariomark@yahoo.com,12345,2025-03-22,-2.0,NaN


In [100]:
df['Phone'] = pd.to_numeric(df['Phone'],errors='coerce')

In [101]:
df[df['Phone'].duplicated()]

,Employee_ID,Name,Age,Salary,Department,City,Gender,Email,Phone,Join_Date,Experience_Years,Performance_Score
3,4,Edward Cowan,<NA>,96172.18,Sales,Mumbai,Female,NaN,NaN,32-13-2024,NaN,15.0
4,5,Brian Moore,59,NaN,Finance,Pune,Male,NaN,NaN,32-13-2024,NaN,6.0
5,6,Dennis Ho,25,57122.30,Sales,Bangalore,Female,NaN,NaN,NaN,NaN,15.0
7,8,Victoria Williams,<NA>,NaN,It,Mumbai,Male,zwarren@gmail.com,NaN,32-13-2024,-2.0,NaN
10,11,Kara House,150,NaN,Finance,Pune,Male,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
989,990,Nicholas Maldonado,<NA>,NaN,Finance,Mumbai,Female,mary03@gmail.com,NaN,32-13-2024,19.2,15.0
992,993,Daniel Morrison,25,NaN,Finance,Bangalore,Female,greenandrew@gmail.com,NaN,NaN,13.8,NaN
993,994,Jennifer Terry,30,NaN,Hr,Mumbai,Female,huynhhayley@gmail.com,NaN,NaN,NaN,4.0
997,998,NaN,49,NaN,Hr,Mumbai,Female,richardcox@shaw.com,NaN,NaN,NaN,NaN


In [104]:
df['Phone'].isnull().mean()

np.float64(0.409)

# 

# 

In [105]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [106]:
df['Join_Date'].isnull().mean()

np.float64(0.481)

In [107]:
df['Join_Date'].unique()

array(['2025-10-17', '32-13-2024', nan, '2024-09-07', '2022-07-14',
       '2026-03-01', '2022-02-27', '2024-08-28', '2023-07-15',
       '2024-02-26', '2021-06-06', '2022-01-21', '2025-09-14',
       '2026-05-09', '2022-01-06', '2022-09-09', '2025-06-08',
       '2024-03-22', '2025-08-21', '2021-06-11', '2024-12-29',
       '2026-02-04', '2026-03-06', '2021-09-15', '2025-04-19',
       '2025-04-04', '2024-05-21', '2025-08-04', '2026-03-24',
       '2024-02-20', '2023-12-11', '2023-09-18', '2024-05-07',
       '2024-07-11', '2025-07-13', '2021-05-28', '2022-03-19',
       '2026-01-12', '2024-08-07', '2023-11-30', '2024-01-08',
       '2023-10-16', '2022-06-06', '2022-12-15', '2025-11-28',
       '2025-10-02', '2022-11-22', '2024-12-13', '2026-05-07',
       '2023-07-24', '2023-01-15', '2026-05-22', '2025-07-22',
       '2022-01-25', '2025-02-11', '2025-11-13', '2025-07-07',
       '2024-08-12', '2024-07-25', '2022-05-13', '2024-09-20',
       '2023-12-27', '2025-09-07', '2022-04-15', '

In [108]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],errors='coerce')

In [109]:
df['Join_Date'].isnull().mean()

np.float64(0.731)

In [110]:
df['Join_Date'].isnull().mean()*100

np.float64(73.1)

In [111]:
df['Join_Date'] = df.groupby(['Department', 'City'])['Join_Date'].transform( lambda x: x.fillna(x.median()))

In [112]:
df['Join_Date'].isnull().mean()*100

np.float64(0.0)

# 

# 

In [113]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [115]:
df['Experience_Years'].isnull().mean()

np.float64(0.513)

In [116]:
df['Experience_Years'].unique()

array([ nan, -2. , 14.2, 14.6,  1. , 11.6,  5. , 11.2, 18.1,  9.4,  9.5,
        0.9,  1.9,  8.7, 15.6,  8. , 16.1,  2.8,  9.2,  1.8, 15.9,  9.3,
       16.3,  5.9,  0.7, 13.4, 19.4,  9.1, 15.2, 16.5, 18.2,  0.2,  5.1,
        3.8, 19.1, 18.3,  1.1,  5.4,  9.8, 11. , 17.5, 19. , 17.4, 13.9,
       17.2,  4.8,  0.3,  5.3,  4.6,  2.4, 16.2, 19.5,  0.8, 17. , 12.8,
        3.7,  3.3, 16.6,  8.9, 10.7, 17.6,  5.2,  7.4,  6.8, 15.3,  7.6,
       15. , 15.1,  6.5,  6.6, 11.1,  6.7,  2.1,  4.9,  6.9, 13.5,  3.2,
       17.8, 10. ,  0.5,  5.8,  8.5,  1.3, 17.9, 17.3, 16.4, 11.4, 15.7,
        9.9, 12.5,  4.1, 16.8,  4.7,  8.2,  4.5,  1.6, 12.7, 18.5,  3.4,
       18.9, 14. , 18.7,  3.6,  3.9, 10.5, 12.9, 10.4,  8.6, 14.1,  6.4,
        6. , 13.8, 19.9,  3. ,  2.6, 16. , 15.8, 10.2,  4. , 11.9,  7.5,
       11.8,  0.6, 13.7, 13.1, 17.1,  1.2, 12.1,  2. , 10.9, 12. ,  0. ,
        0.4,  8.4,  8.3,  6.3, 19.2])

In [118]:
df['Experience_Years'].dtypes

dtype('float64')

In [119]:
df.loc[df['Experience_Years'] < 0,'Experience_Years'] = np.nan

In [120]:
df['Experience_Years'].isnull().mean()

np.float64(0.763)

In [121]:
df['Experience_Years'] = df.groupby(['Department', 'City'])['Experience_Years'].transform( lambda x: x.fillna(x.median()))

In [122]:
df['Experience_Years'].isnull().mean()

np.float64(0.0)

# 

# 

In [123]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City', 'Gender',
       'Email', 'Phone', 'Join_Date', 'Experience_Years', 'Performance_Score'],
      dtype='object')

In [125]:
df['Performance_Score'].isnull().mean()

np.float64(0.475)

In [129]:
df = df.drop('Performance_Score', axis=1)

# 

In [130]:
df.isnull().mean()*100

Employee_ID          0.0
Name                 5.1
Age                 41.8
Salary              80.8
Department           0.0
City                 0.0
Gender               0.0
Email               60.9
Phone               40.9
Join_Date            0.0
Experience_Years     0.0
dtype: float64

In [134]:
df['Age'] = df.groupby(['Department', 'City'])['Age'].transform(lambda x: x.fillna(round(x.median()))).astype('Int64')

In [132]:
df.dtypes

Employee_ID                  int64
Name                        object
Age                          Int64
Salary                     float64
Department                  object
City                        object
Gender                      object
Email                       object
Phone                      float64
Join_Date           datetime64[ns]
Experience_Years           float64
dtype: object

In [135]:
df['Salary'] = df.groupby(['Department', 'City'])['Salary'].transform(lambda x: x.fillna(x.median()))

In [136]:
df.isnull().mean()*100

Employee_ID          0.0
Name                 5.1
Age                  0.0
Salary               1.3
Department           0.0
City                 0.0
Gender               0.0
Email               60.9
Phone               40.9
Join_Date            0.0
Experience_Years     0.0
dtype: float64

In [137]:
df = df.dropna(subset='Name')

In [138]:
df.isnull().mean()*100

Employee_ID          0.000000
Name                 0.000000
Age                  0.000000
Salary               1.264489
Department           0.000000
City                 0.000000
Gender               0.000000
Email               60.906217
Phone               40.674394
Join_Date            0.000000
Experience_Years     0.000000
dtype: float64

In [139]:
df = df.dropna(subset='Salary')

In [140]:
df.isnull().mean()*100

Employee_ID          0.000000
Name                 0.000000
Age                  0.000000
Salary               0.000000
Department           0.000000
City                 0.000000
Gender               0.000000
Email               60.618997
Phone               40.448239
Join_Date            0.000000
Experience_Years     0.000000
dtype: float64