# NUMPY JOINING ASSIGNMENT

### DAY : 08

## A. ARRAY JOINING

## CONCATENATION()

### BASIC questions

In [5]:
import numpy as np 

In [6]:
A = np.array([1, 2, 3])
B = np.array([44, 55, 66])


In [7]:
print("Array A :",A)
print("Array B : ",B)

Array A : [1 2 3]
Array B :  [44 55 66]


#### 1.Using concatenation, form a single array by joining A and B.

In [8]:
# data = np.concatenate(A,B)

In [9]:
np.concatenate((A,B))

array([ 1,  2,  3, 44, 55, 66])

#### 2. Create a new array by joining B followed by A.

In [10]:
new_array = np.concatenate((B,A))
new_array

array([44, 55, 66,  1,  2,  3])

#### 3. Construct an array by repeating A twice and then adding B.

In [11]:
reapeted_A = np.tile(A,2)
print("Repeated Array A : ",reapeted_A)
new_array = np.concatenate((reapeted_A,B))
print("Combined Array : ",new_array)

Repeated Array A :  [1 2 3 1 2 3]
Combined Array :  [ 1  2  3  1  2  3 44 55 66]


In [12]:
#best way
np.concatenate((A,A,B))

array([ 1,  2,  3,  1,  2,  3, 44, 55, 66])

#### 4. Combine A and B in alternating order (A, B, A).

In [13]:
np.concatenate((A,B,A))

array([ 1,  2,  3, 44, 55, 66,  1,  2,  3])

#### 5. Merge A and B and find the total number of elements.

In [14]:
np.concatenate((A,B)).size

6

#### 6. Create a final array by joining B three times.

In [15]:
np.concatenate((B,B,B))

array([44, 55, 66, 44, 55, 66, 44, 55, 66])

#### 7. Join A and B and check whether the result is sorted or not.

In [16]:
data = np.concatenate((A,B))
print(data)
is_soarted = np.all(data[:-1]<=data[1:])
print("Is sorted :",is_soarted)

[ 1  2  3 44 55 66]
Is sorted : True


#### 8. Form a dataset by combining A and B and compare lengths before/after join.

In [17]:
print("Length of A:",A.size)
print("Length of B : ",B.size)
combined_data = np.concatenate((A,B))
print("Length of Combined Data :",combined_data.size)

Length of A: 3
Length of B :  3
Length of Combined Data : 6


#### 9. Create a reversed combined array using A and B.

In [18]:
data = np.concatenate((A,B))[::-1]
data

array([66, 55, 44,  3,  2,  1])

#### 10. Join A and B and compute sum of all elements in final array.

In [19]:
final_data = np.concatenate((A,B)).sum()
print(final_data)

171


### ADVANCED (5 QUESTIONS)

In [20]:
X = [[1, 2], [3, 4]]
Y = [[55, 66], [77, 88]]
x = np.array(X)
y = np.array(Y)
print("Array X :",x,sep="\n")
print("Array Y :",y,sep="\n")

Array X :
[[1 2]
 [3 4]]
Array Y :
[[55 66]
 [77 88]]


#### 1. Combine X and Y vertically and explain resulting shape.

In [21]:
data = np.concatenate((x,y),axis=0)
data

array([[ 1,  2],
       [ 3,  4],
       [55, 66],
       [77, 88]])

In [22]:
print("Shape - (rows,cols)")
print("Shape of x :",x.shape)
print("Shape of y :",y.shape)
print("Shape of combined :",data.shape)
print("Here combined veritically means row vise, so new shape is rows of x + rows of y and column are same ")

print("Note :vertically join valid when column of both array same ")

Shape - (rows,cols)
Shape of x : (2, 2)
Shape of y : (2, 2)
Shape of combined : (4, 2)
Here combined veritically means row vise, so new shape is rows of x + rows of y and column are same 
Note :vertically join valid when column of both array same 


#### 2. Combine X and Y horizontally and explain difference from vertical join.

In [23]:
hdata = np.concatenate((x,y),axis =1)
hdata

array([[ 1,  2, 55, 66],
       [ 3,  4, 77, 88]])

In [24]:
print("Verical join means row vise adding but column of all array must same otherwise fail join ")
print("Vertical join result shape: (rows+all adding rows ) same column size")
print("-"*50)
print("Horizontal Join means column vise adding but rows of all adiing must be same othervise fail join")
print("Horizontal join result shape (rows, coulumn+all other arrys adding new columns)")

Verical join means row vise adding but column of all array must same otherwise fail join 
Vertical join result shape: (rows+all adding rows ) same column size
--------------------------------------------------
Horizontal Join means column vise adding but rows of all adiing must be same othervise fail join
Horizontal join result shape (rows, coulumn+all other arrys adding new columns)


#### 3. Create a dataset by joining X, Y, and X again vertically.

In [25]:
np.concatenate((x,y,x),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [55, 66],
       [77, 88],
       [ 1,  2],
       [ 3,  4]])

#### 4. Join Y and X horizontally and compute row-wise sum of final matrix.

In [26]:
hdata = np.concatenate((y,x),axis=1)
hdata.sum(axis=1)

array([124, 172])

#### 5. Merge X and Y into a single matrix and verify total elements count.

In [27]:
mdata = np.concatenate((x,y),axis=0)
print("Total Elements : ",mdata.size)

Total Elements :  8


### REAL WORLD (5 QUESTIONS)

In [28]:
Math_Marks = np.array([50, 60])
Science_Marks = np.array([70, 80])

Sales_Jan = np.array([100, 200])
Sales_Feb = np.array([150, 250])

Sensor_A = np.array([0.1, 0.2])
Sensor_B = np.array([0.3, 0.4])

Login_Day1 = np.array([5, 6])
Login_Day2 = np.array([7, 8])


#### 1 . Combine Math and Science marks into a single student report.

In [29]:
sub_marks = np.concatenate((Math_Marks,Science_Marks))
sub_marks

array([50, 60, 70, 80])

In [30]:
submarks1 = np.concatenate((Math_Marks.reshape(-1,1),Science_Marks.reshape(-1,1)),axis=1)
submarks1

array([[50, 70],
       [60, 80]])

#### 2. Merge January and February sales data and compute total sales.

In [31]:
complete_sales = np.concatenate((Sales_Jan,Sales_Feb))
complete_sales

array([100, 200, 150, 250])

#### 3. Combine Sensor A and Sensor B readings into one dataset.

In [32]:
np.concatenate((Sensor_A,Sensor_B))

array([0.1, 0.2, 0.3, 0.4])

#### 4. Merge login activity of Day1 and Day2 into a full activity log.

In [33]:
login_acti = np.concatenate((Login_Day1,Login_Day2))
login_acti

array([5, 6, 7, 8])

## B. ARRAY STACKING

### 1. np.stack()

In [34]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])


#### 1. Stack A and B along a new axis and describe the shape.

In [35]:
stack_data = np.stack((a1,b1))
print("Stacked Data :",stack_data,sep='\n')
print("Shape :",stack_data.shape)

Stacked Data :
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)


#### 2. Stack A and B such that they form rows in a matrix.

In [36]:
np.stack((a1,b1))

array([[1, 2, 3],
       [4, 5, 6]])

#### 3. Stack A and B such that they form columns.

In [37]:
np.stack((a1,b1),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 4. `Stack A, B, and A again and describe structure.

In [38]:
data = np.stack((a1,b1,a1))
print(data)
print(data.shape)
print(data.ndim)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
2


#### 5. Stack B, A, B and count total elements.

In [39]:
print("Total Elements :",np.stack((b1,a1,b1)).size)

Total Elements : 9


##### 6. Stack A with itself and compare with original.

In [40]:
print(a1)
print("-"*10)
print(np.stack((a1,a1)))

[1 2 3]
----------
[[1 2 3]
 [1 2 3]]


#### 7. Stack A and B and identify number of dimensions.

In [41]:
print("No of Dim :",np.stack((a1,b1)).ndim)

No of Dim : 2


#### 8. Stack A, B and find sum of resulting array.

In [42]:
result = np.stack((a1,b1))
print("Sum Of result :",result.sum())

Sum Of result : 21


#### 9. Stack A and B and extract first stacked block.

In [43]:
stdata = np.stack((a1,b1))
print("First Block :",stdata[0])

First Block : [1 2 3]


#### 10 . Compare stacking A & B vs simple joining.

In [44]:
print("Stacked Data : ",np.stack((a1,b1)),sep="\n")
print("-"*50)
print("Simple Joinning :",np.concatenate((a1,b1)))

Stacked Data : 
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
Simple Joinning : [1 2 3 4 5 6]


### ADVANCED (2D ARRAYS – 5)

In [45]:
 x1= np.array([[1,2],[3,4]])
 x2= np.array([[5,6],[7,8]])

#### 1. Stack X and Y along a new axis and describe 3D shape.

In [46]:
sdata = np.stack((x1,x2))
print(sdata)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
print(sdata.shape)

(2, 2, 2)


#### 2. Stack X and Y and identify number of layers formed.

In [48]:
stdata = np.stack((x1,x2))
print(stdata)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
print("Total Layer:",stdata.shape[0])

Total Layer: 2


#### 3. Stack X, Y, X and compute total number of elements.

In [50]:
np.stack((x1,x2,x1)).size

12

#### 4. Stack Y, X and extract first layer.

In [51]:
stdata = np.stack((x2,x1))
print(stdata[0,...])

[[5 6]
 [7 8]]


In [52]:
stdata

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

#### 5. Stack matrices and analyze how dimension increases.

In [53]:
print("x1 dime..:",x1.ndim)
print("x2 dime..: ",x2.ndim)
print("Stacked dim..:",np.stack((x2,x1)).ndim)

x1 dime..: 2
x2 dime..:  2
Stacked dim..: 3


### REAL WORLD

In [54]:
Temperature = np.array([30, 32, 35])
Humidity = np.array([60, 65, 70])

#### 1. Stack temperature and humidity to create weather dataset.

In [55]:
weather_data = np.stack((Temperature,Humidity),axis =1)
weather_data

array([[30, 60],
       [32, 65],
       [35, 70]])

#### 2. Represent each day as a stacked data point.

In [56]:
data = np.stack((Temperature,Humidity),axis =1)
i=1
for r in data:
    print("Day",i," :",r )
    i+=1

Day 1  : [30 60]
Day 2  : [32 65]
Day 3  : [35 70]


#### 3. Stack multiple features into ML input structure.

In [57]:
np.stack((Temperature,Humidity),axis=1)

array([[30, 60],
       [32, 65],
       [35, 70]])

#### 4. Combine two feature vectors into model-ready data.

In [58]:
data = np.stack((Temperature,Humidity))
data


array([[30, 32, 35],
       [60, 65, 70]])

# 2. np.vstack()

#### BASIC (1D ARRAYS – 10)

In [59]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#### 1. Stack A and B vertically to form rows.

In [60]:
np.vstack((A,B))

array([[1, 2, 3],
       [4, 5, 6]])

#### 2. Stack B above A and compare result.

In [61]:
np.vstack((B,A))

array([[4, 5, 6],
       [1, 2, 3]])


#### 3. Stack A twice vertically.

In [62]:
np.vstack((A,A))

array([[1, 2, 3],
       [1, 2, 3]])

#### 4. Stack A, B, A and count rows.

In [63]:
np.vstack((A,B,A)).shape[0]

3

#### 5. Stack B three times and count rows.

In [64]:
np.vstack((B,B,B)).shape[0]

3


#### 6. Stack A and B and compute row-wise sum.

In [65]:
np.vstack((A,B)).sum(axis=1)

array([ 6, 15])

#### 7. Stack A and B and extract second row.

In [66]:
np.vstack((A,B))[1]

array([4, 5, 6])

#### 8.Stack A and B and find number of rows.

In [67]:
np.vstack((A,B)).shape[0]

2

#### 9. Stack A and B and compare with stack(axis=0).

In [68]:
data1 = np.vstack((A,B))
data2 = np.stack((A,B),axis=0)
print(data1)
print("-"*18)
print(data2)

[[1 2 3]
 [4 5 6]]
------------------
[[1 2 3]
 [4 5 6]]


#### 10. Stack A and B and identify row structure.

In [69]:
data = np.vstack((A,B))
data

array([[1, 2, 3],
       [4, 5, 6]])

### ADVANCED (2D ARRAYS )

In [70]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [71]:
x

array([[1, 2],
       [3, 4]])

In [72]:
y

array([[5, 6],
       [7, 8]])

#### 1.Stack X and Y vertically and describe new shape.

In [73]:
data = np.vstack((x,y))
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
data.shape

(4, 2)

#### 2. Stack Y and X and compute column-wise sum.

In [75]:
data = np.vstack((y,x))
data.sum(axis=0)

array([16, 20])

#### 3.Stack X, Y, X and find row-wise max.

In [76]:
data = np.vstack((x,y,x))
data.sum(axis=1)

array([ 3,  7, 11, 15,  3,  7])

#### 4. Stack matrices and count total rows.

In [77]:
np.vstack((x,y)).shape[0]

4

### REAL WORLD

In [78]:
Day1_Sales =np.array( [100, 200, 300])
Day2_Sales =np.array( [150, 250, 350])

In [79]:
Day1_Sales

array([100, 200, 300])

In [80]:
Day2_Sales

array([150, 250, 350])

#### 1. Stack daily sales to create time-series dataset.

In [81]:
dataset = np.vstack((Day1_Sales,Day2_Sales))
dataset

array([[100, 200, 300],
       [150, 250, 350]])

#### 2. Represent each day as a row.

In [82]:
day =1
for r in np.vstack((Day1_Sales,Day2_Sales)):
    print(f"Day {day} : {r}")
    day+=1

Day 1 : [100 200 300]
Day 2 : [150 250 350]


#### 3.Stack multiple days and compute daily totals.

In [83]:
data = np.vstack((Day1_Sales,Day2_Sales))
day= 1
for r in data:
    print(f"Day {day} : Total Sales : {r.sum()}")

Day 1 : Total Sales : 600
Day 1 : Total Sales : 750


#### 4. Combine weekly sales data vertically.

In [84]:
data = np.vstack((Day1_Sales,Day2_Sales))
data

array([[100, 200, 300],
       [150, 250, 350]])

# 3. np.hstack()2

In [85]:
BASIC (1D ARRAYS – 10)

SyntaxError: invalid decimal literal (2755256076.py, line 1)

In [86]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Array A:",A)
print("Array B : ",B)

Array A: [1 2 3]
Array B :  [4 5 6]


#### 1 .Stack A and B horizontally.

In [87]:
data = np.hstack((A,B))
data

array([1, 2, 3, 4, 5, 6])

#### 2. Stack B and A and compare results.

In [88]:
data = np.hstack((A,B))
print("A :",A)
print("B :",B)
print("Stacked Data :",data)

A : [1 2 3]
B : [4 5 6]
Stacked Data : [1 2 3 4 5 6]


#### 3. Stack A twice horizontally.

In [89]:
np.hstack((A,A))

array([1, 2, 3, 1, 2, 3])

#### 4. Stack A, B, A and count elements.

In [90]:
data = np.hstack((A,B,A))
print("Data :",data)
print("Total Elements :",data.size)

Data : [1 2 3 4 5 6 1 2 3]
Total Elements : 9


#### 5. Stack B three times.

In [91]:
data = np.hstack((B,B,B))
print(data)

[4 5 6 4 5 6 4 5 6]


#### 6. Stack A and B and compute total length.

In [92]:
data = np.hstack((A,B))
print("Data :",data)
print("Total Length : ",data.size)

Data : [1 2 3 4 5 6]
Total Length :  6


#### 7. Stack A and B and extract first half.

In [93]:
data = np.hstack((A,B))
size = data.size
data[:size//2]

array([1, 2, 3])

#### 8. Stack A and B and extract last value.

In [94]:
data = np.hstack((A,B))
print("Last value :",data[-1])

Last value : 6


#### 9. Compare result with simple joining.

In [95]:
simpl_join = np.concatenate((A,B))
stackData = np.hstack((A,B))
print("Data 1: ",simpl_join)
print("Data 2: ",stackData)
print("Compare : ",simpl_join==stackData)

Data 1:  [1 2 3 4 5 6]
Data 2:  [1 2 3 4 5 6]
Compare :  [ True  True  True  True  True  True]


#### 10 . Identify shape after stacking.

In [96]:
data = np.vstack((A,B))
data.shape

(2, 3)

### ADVANCED (2D ARRAYS – 5)

In [97]:
x = np.array([[1,2],[3,4]])
y = np.array( [[5,6],[7,8]])
print("X array :",x,sep='\n')
print("Y array : ",y,sep ='\n')

X array :
[[1 2]
 [3 4]]
Y array : 
[[5 6]
 [7 8]]


#### 1. Stack X and Y horizontally and describe shape.

In [98]:
data = np.hstack((x,y))
data.shape

(2, 4)

#### 2.Stack Y and X and compute row sums.

In [99]:
data = np.hstack((x,y))
data.sum(axis=1)

array([14, 22])

In [100]:
data

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### 3. Stack X, Y, X and count columns.

In [101]:
data = np.hstack((x,y,x))
total_elements = data.size
print("Total elements :",total_elements)


Total elements : 12


#### 4. Stack matrices and find max per row.

In [102]:
data = np.hstack((x,y))
data.max(axis=1)

array([6, 8])

#### 5. Interpret columns as features.

In [103]:
data = np.hstack((x,y))
data.shape

(2, 4)

In [104]:
data

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [105]:
fea=0
for a in range(data.shape[1]):
    print(f"Feature col {a} : {data[:,a]}")
    

Feature col 0 : [1 3]
Feature col 1 : [2 4]
Feature col 2 : [5 7]
Feature col 3 : [6 8]


# 4. np.dstack()

### BASIC (1D → 2D/3D )

In [106]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Array A :",A,sep="\n")
print("Array B : ",B,sep='\n')

Array A :
[[1 2]
 [3 4]]
Array B : 
[[5 6]
 [7 8]]


#### 1. Stack A and B along depth dimension.

In [107]:
data = np.dstack((A,B))
data

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

#### 2. Identify number of layers formed.

In [108]:
data = np.dstack((A,B))
data.shape[0]

2

#### 3. Stack A, B, A and count depth layers.

In [109]:
data = np.dstack((A,B,A))
data.shape[0]

2

#### 4. Stack B twice and analyze structure.

In [110]:
data = np.dstack((B,B))
data.shape

(2, 2, 2)

#### 5.Extract first depth layer.

In [111]:
data = np.dstack((A,B))
data[0]

array([[1, 5],
       [2, 6]])

#### 6. Extract second depth layer.

In [112]:
data[1]

array([[3, 7],
       [4, 8]])

#### 7. Compute total elements after stacking.

In [113]:
data = np.dstack((A,B))
data.size

8

#### 8. Compare with vertical stacking.

In [114]:
data = np.dstack((A,B))
data2 = np.vstack((A,B))
print("Depth vise stacking : ")
print(data)
print("Vertical stacking : ")
print(data2)

Depth vise stacking : 
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Vertical stacking : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 9. Compare with horizontal stacking.

In [115]:
data = np.dstack((A,B))
data2 = np.hstack((A,B))
print("Depth vise stacking : ")
print(data)
print("Horizonatal stacking : ")
print(data2)

Depth vise stacking : 
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Horizonatal stacking : 
[[1 2 5 6]
 [3 4 7 8]]


#### 10. Identify final dimension.

In [116]:
data = np.dstack((A,B))
data.ndim

3

# 5. np.column_stack()

### BASIC (1D ARRAYS – 10)

In [117]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Array  A : ",A)
print("Array B :",B)

Array  A :  [1 2 3]
Array B : [4 5 6]


#### 1.Stack A and B as columns.

In [118]:
 data = np.column_stack((A,B))
data

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 2. Identify number of columns.

In [119]:
data = np.column_stack((A,B))
data.shape[1]

2

#### 3. Extract first column.

In [120]:
data = np.column_stack((A,B))
data[...,0]

array([1, 2, 3])

#### 4. Extract second column.

In [121]:
data = np.column_stack((A,B))
data[...,1]

array([4, 5, 6])

#### 5 .Compute column-wise sum.

In [122]:
data = np.column_stack((A,B))
data.sum(axis=0)

array([ 6, 15])

#### 6.Stack A twice as columns.

In [123]:
data = np.column_stack((A,A))
data

array([[1, 1],
       [2, 2],
       [3, 3]])

#### 7.Stack B twice.

In [124]:
data = np.column_stack((B,B))
data

array([[4, 4],
       [5, 5],
       [6, 6]])

#### 8. Stack A, B, A.

In [125]:
data = np.column_stack((A,B,A))
data

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])


####  9. Identify shape after stacking.

In [126]:
data = np.column_stack((A,B))
data.shape

(3, 2)

#### 10 . Compare with hstack.

In [127]:
cdata = np.column_stack((A,B))
hdata = np.hstack((A,B))
print("Column Stacking :")
print(cdata)
print("-"*10)
print("H stacking : ")
print(hdata)

Column Stacking :
[[1 4]
 [2 5]
 [3 6]]
----------
H stacking : 
[1 2 3 4 5 6]


### ADVANCED (2D ARRAYS )

In [128]:
x= np.array([[10], [20], [30]])
y = np.array([[40], [50], [60]])
print("Array x :",x,sep='\n')
print("Dimentiona of X :",x.ndim)
print("Array y : ",y,sep='\n')
print("Dimention of Y : ",y.ndim)


Array x :
[[10]
 [20]
 [30]]
Dimentiona of X : 2
Array y : 
[[40]
 [50]
 [60]]
Dimention of Y :  2


#### 1. Create feature matrix using column stacking.

In [129]:
data = np.column_stack((x,y))
total_col = data.shape[1]
for a in range(total_col):
    print("Feature 1 : ",data[:,a])
    

Feature 1 :  [10 20 30]
Feature 1 :  [40 50 60]


#### 2. Compute column-wise mean.

In [130]:
data = np.column_stack((x,y))
data.sum(axis=0)

array([ 60, 150])

#### 3. Stack multiple arrays into dataset.

In [131]:
dataset = np.column_stack((x,y))
dataset

array([[10, 40],
       [20, 50],
       [30, 60]])

#### 4.Extract column vectors.

In [132]:
data = np.column_stack((x,y))
total_col = data.shape[1]
for a in range(total_col):
    print(f"Vector {a+1} : {data[...,a]}")

Vector 1 : [10 20 30]
Vector 2 : [40 50 60]


# 6. np.row_stack()

### BASIC (1D ARRAYS – 10)

In [133]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Array A :",A)
print("Array B ",B)

Array A : [1 2 3]
Array B  [4 5 6]


#### 1.Stack A and B as rows.

In [134]:
data = np.row_stack((A,B))
data

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\618378719.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data = np.row_stack((A,B))


array([[1, 2, 3],
       [4, 5, 6]])

#### 2.Identify number of rows.

In [135]:
data.shape[0]

2

#### 3. Extract first row.

In [136]:
data[0]

array([1, 2, 3])

#### 4. Extract second row.

In [137]:
data[1]

array([4, 5, 6])

#### 5.Compute row-wise sum.

In [138]:
data.sum(1) # sum(1) means  - sum(axis=1)

array([ 6, 15])

#### 6. Stack A twice.

In [139]:
data = np.row_stack((A,A))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\4148979092.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data = np.row_stack((A,A))


In [140]:
data

array([[1, 2, 3],
       [1, 2, 3]])

#### 7.Stack B twice.

In [141]:
data = np.row_stack((B,B))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\4126919841.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data = np.row_stack((B,B))


In [142]:
data

array([[4, 5, 6],
       [4, 5, 6]])

#### 8. Stack A, B, A.

In [143]:
data = np.row_stack((A,B,A))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\1551171226.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data = np.row_stack((A,B,A))


In [144]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

#### 9 .Identify shape.

In [145]:
data = np.row_stack((A,B))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\423678399.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data = np.row_stack((A,B))


In [146]:
data.shape

(2, 3)

#### 10 . Compare with vstack.

In [147]:
rstdata = np.row_stack((A,B))


C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9008\274890968.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  rstdata = np.row_stack((A,B))


In [148]:
rstdata

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
vsdata = np.vstack((A,B))

In [150]:

vsdata

array([[1, 2, 3],
       [4, 5, 6]])