# NumPy Sorting Functions –  Simple Assignments

## 1: np.sort()

In [35]:
import numpy as np

marks = np.array([85, 42, 97, 63, 78, 51, 89, 34, 76, 91])
print("Original marks:", marks)

Original marks: [85 42 97 63 78 51 89 34 76 91]


#### Q1. Sort the marks in ascending order using np.sort().

In [36]:
np.sort(marks)

array([34, 42, 51, 63, 76, 78, 85, 89, 91, 97])

#### Q2. Sort the marks in descending order (use np.sort() then reverse).



In [37]:
np.sort(marks)[::-1]

array([97, 91, 89, 85, 78, 76, 63, 51, 42, 34])

#### Q3. Sort the marks but keep the original array unchanged. Prove it by printing both.



In [38]:
sorted_mark = np.sort(marks)
print("marks        : ",marks)
print("Sorted marks : ",sorted_mark)

marks        :  [85 42 97 63 78 51 89 34 76 91]
Sorted marks :  [34 42 51 63 76 78 85 89 91 97]


#### Q4. Sort only the first 5 marks (indices 0-4) using slicing + np.sort().



In [39]:
# help(np.sort)
np.sort(marks[:5])

array([42, 63, 78, 85, 97])

#### Q5. Find the 3 highest marks using np.sort() and slicing.



In [40]:
h1,h2,h3 = np.sort(marks)[::-1][:3]
print("Highest mark :",h1)
print("Second Highest m :",h2)
print("Third Highest m :",h3)

Highest mark : 97
Second Highest m : 91
Third Highest m : 89


## 2: ndarray.sort()
Sorts the array in-place (modifies original).



In [41]:
prices = np.array([299, 150, 450, 125, 350, 200, 500, 75, 425, 180])
print("Original prices:", prices)

Original prices: [299 150 450 125 350 200 500  75 425 180]


#### Q6. Sort the prices in ascending order using in-place sort.

In [42]:
price2 = prices.copy()
price2.sort()
print(price2)

[ 75 125 150 180 200 299 350 425 450 500]


#### Q7. After sorting, print the original array to confirm it changed

In [43]:
prices3 = prices.copy()
prices3.sort()

In [44]:
prices3

array([ 75, 125, 150, 180, 200, 299, 350, 425, 450, 500])

#### Q8. Sort the prices in descending order using in-place sort.

In [47]:
prices4 = prices.copy()
prices4.sort()
prices4[::-1]


array([90.25, 64.5 , 45.15, 33.6 , 25.99, 22.75, 12.49, 11.  ])

#### Q9. Sort only the last 6 elements in-place (leave first 4 unchanged).

In [50]:
prices9 = prices.copy()
prices9[4:] = np.sort(prices9[4:])

print(f"After sorting : {prices9}")
print(f"First 4 elements unchanged: {prices9[:4]}")
print(f"After sorting last 6 elements: {prices9[4:]}")

After sorting : [90.25 64.5  45.15 33.6  11.   12.49 22.75 25.99]
First 4 elements unchanged: [90.25 64.5  45.15 33.6 ]
After sorting last 6 elements: [11.   12.49 22.75 25.99]


#### Q10. Sort the array in-place then find the median (middle value).

In [51]:
prices6 = prices.copy()
prices6.sort()
median_value = np.median(prices6)
print(prices6)
print('median value : ',median_value)

[11.   12.49 22.75 25.99 33.6  45.15 64.5  90.25]
median value :  29.795


## 3: np.argsort()
Returns indices that would sort the array.

In [52]:
heights = np.array([165, 180, 155, 172, 168, 190, 158, 175, 182, 160])
print("Heights:", heights)
print("Student IDs (index):", np.arange(10))

Heights: [165 180 155 172 168 190 158 175 182 160]
Student IDs (index): [0 1 2 3 4 5 6 7 8 9]


#### Q11. Find the indices that would sort heights from shortest to tallest.

In [53]:
sorted_index = np.argsort(heights)
print('sorted array index :',sorted_index)

sorted array index : [2 6 9 0 4 3 7 1 8 5]


#### Q12. Use those indices to get the sorted heights array.

In [54]:
heights[sorted_index]

array([155, 158, 160, 165, 168, 172, 175, 180, 182, 190])

#### Q13. Find which student (index) is the tallest using np.argsort().

In [55]:
st_id = np.argsort(heights)[-1]
print("Tallest Student id : ",st_id)
print("Height : ",heights[st_id])


Tallest Student id :  5
Height :  190


#### Q14. Find which student (index) is the shortest using np.argsort().

In [56]:
st_id = np.argsort(heights)[0]
print("Smallest Student id : ",st_id)
print("Height : ",heights[st_id])


Smallest Student id :  2
Height :  155


#### Q15. Get the top 3 tallest students' indices using np.argsort().

In [57]:
st1,st2,st3 = np.argsort(heights)[::-1][:3]
print("Top 3 highest height student ids :")
print("St id :",st1)
print("St id :",st2)
print("St id :",st3)

Top 3 highest height student ids :
St id : 5
St id : 8
St id : 1


### 4: np.partition()
Partial sort - places kth smallest element in correct position.

In [58]:
salaries = np.array([45000, 32000, 68000, 28000, 52000, 41000, 75000, 38000, 61000, 49000])
print("Salaries:", salaries)

Salaries: [45000 32000 68000 28000 52000 41000 75000 38000 61000 49000]


#### Q16. Partition the array so that the 3rd smallest (index 2) is in correct position.

In [59]:
partition_array = np.partition(salaries,2)
partition_array

array([28000, 32000, 38000, 41000, 45000, 49000, 52000, 61000, 68000,
       75000])

In [60]:
print(partition_array[2])

38000


#### Q17. Get the 4 smallest salaries using np.partition().

In [61]:
sorted_salaries = np.partition(salaries,4)
print(sorted_salaries[:4])

[28000 32000 38000 41000]


#### Q18. Get the 3 largest salaries using np.partition() with negative index.

In [62]:
sorted_array = np.partition(salaries,4)

In [63]:
print(sorted_array[-3])

61000


#### Q19. Compare speed: find top 5 salaries using np.sort() vs np.partition() on large array.

In [64]:
import time
start = time.time()
sorted_all = np.sort(salaries)
top_5_sort = sorted_all[-5:]
time_sort = time.time() - start

start = time.time()
partitioned = np.partition(salaries, -5)
top_5_partition = partitioned[-5:]
time_partition = time.time() - start


In [65]:
print(f"Array size: {len(salaries):,}")
print(f"\nnp.sort() time: {time_sort:.4f}s")
print(f"Top 5 via sort: {np.sort(top_5_sort)}")
print(f"\nnp.partition() time: {time_partition:.4f}s")
print(f"Top 5 via partition: {np.sort(top_5_partition)}")
print("-" * 60)

Array size: 10

np.sort() time: 0.0005s
Top 5 via sort: [49000 52000 61000 68000 75000]

np.partition() time: 0.0004s
Top 5 via partition: [49000 52000 61000 68000 75000]
------------------------------------------------------------


#### Q20. Partition the array so first 4 positions contain the smallest 4 values (any order).b

In [66]:
arr_partitioned = marks.copy()
arr_partitioned.partition(4)  # In-place method
print(f"After partition(k=4): {arr_partitioned}")
print(f"First 4 smallest, any order :  {arr_partitioned[:4]}")
print(f"Remaining elements: {arr_partitioned[4:]}")

After partition(k=4): [34 42 51 63 76 78 85 89 91 97]
First 4 smallest, any order :  [34 42 51 63]
Remaining elements: [76 78 85 89 91 97]


### 5: np.argpartition()
Returns indices of partial sort.

In [70]:
scores = np.array([88, 45, 92, 67, 79, 56, 94, 38, 81, 73, 96, 62, 85, 49, 91])
print("Scores:", scores)
print("Student indices:", np.arange(15))

Scores: [88 45 92 67 79 56 94 38 81 73 96 62 85 49 91]
Student indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Q21. Find indices of the 3 smallest scores using np.argpartition().

In [71]:
score_index = np.argpartition(scores,3)
print(score_index[:3])

[ 7  1 13]


#### Q22. Find indices of the 5 largest scores using np.argpartition().

In [72]:
score_max = np.argpartition(scores,3)[-5:]
print(score_max)

[ 0 14  2  6 10]


#### Q23. Use the indices to extract the actual 5 largest scores.

In [73]:
print("Top 5 scores : ",scores[score_max])

Top 5 scores :  [88 91 92 94 96]


#### Q24. Find which student has the 2nd highest score using np.argpartition().

In [74]:
print("Second Higest scoes : ",scores[score_max][-2])

Second Higest scoes :  94


#### Q25. Find which student has the lowest score using np.argpartition().

In [75]:
print(scores[score_index[0]])

38
