# Array Inexing and Slicing

##  #Indexing

In [1]:
import numpy as np

In [3]:
a = np.array(range(20))

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
print(a[1])
print(a[-1])

1
19


In [7]:
a2 = np.array(range(25),ndmin=2)

In [9]:
print(a2)
print(a2[0,1])
print(a2[...,-1])
print(a2[0,-1])
print(a2[-1,-4])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
1
[24]
24
21


In [17]:
a3 = np.array([1,2,3,4,5,6],ndmin=3)

In [18]:
print(a3[...,-1])
print(a3[-1,-1,-1])

[[6]]
6


In [19]:
a4 = np.array(range(36)).reshape(3,-1,6)

In [20]:
a4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [21]:
print(a4[1,1,-1])

23


In [22]:
print(a4[-1,-1,-2])

34


## #Slicing...

In [23]:
print(a[:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
print(a2[:])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [25]:
print(a3[:])

[[[1 2 3 4 5 6]]]


In [26]:
print(a4[:])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [27]:
print(a4[...])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [28]:
print(a4[...,...,-2])

IndexError: an index can only have a single ellipsis ('...')

In [30]:
print(a4[...,-2]) # correct way

[[ 4 10]
 [16 22]
 [28 34]]


#### 1D array slicing

In [31]:
a1 = np.linspace(10,100,30,dtype=int)

In [32]:
a1[10:]

array([ 41,  44,  47,  50,  53,  56,  59,  62,  65,  68,  72,  75,  78,
        81,  84,  87,  90,  93,  96, 100])

In [33]:
print(a1[:10])

[10 13 16 19 22 25 28 31 34 37]


In [34]:
print(a1[-1:0:-2])

[100  93  87  81  75  68  62  56  50  44  37  31  25  19  13]


In [35]:
print(a1[::-1])

[100  96  93  90  87  84  81  78  75  72  68  65  62  59  56  53  50  47
  44  41  37  34  31  28  25  22  19  16  13  10]


In [36]:
print(a1[::-2])

[100  93  87  81  75  68  62  56  50  44  37  31  25  19  13]


#### 2D array slicing

In [37]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
print(a2[:])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
print(a2[::])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [41]:
print(a2[::-1]) # row reverse

[[5 6 7 8 9]
 [0 1 2 3 4]]


In [42]:
print(a2[::-2])

[[5 6 7 8 9]]


In [43]:
print(a2[::-3])

[[5 6 7 8 9]]


In [44]:
print(a2[::,-3])

[2 7]


In [45]:
print(a2[:,-3:])

[[2 3 4]
 [7 8 9]]


In [46]:
aa2 = np.arange(12).reshape(4,3)

In [47]:
aa2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
print(aa2[::-3])

[[ 9 10 11]
 [ 0  1  2]]


In [49]:
print(aa2[...,-1])

[ 2  5  8 11]


In [50]:
print(aa2[-1,-1])

11


In [51]:
print(aa2[::-1,-1])

[11  8  5  2]


In [52]:
print(aa2[::-1,:-1])

[[ 9 10]
 [ 6  7]
 [ 3  4]
 [ 0  1]]


#### 3D Slicing

In [53]:
aa3 = np.arange(12).reshape(-1,3,4)
aa3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [54]:
print(aa3[-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
print(aa3[-1,-1])

[ 8  9 10 11]


In [56]:
print(aa3[-1,:-1])

[[0 1 2 3]
 [4 5 6 7]]


In [57]:
print(aa3[-1,:,-1])

[ 3  7 11]


In [58]:
print(aa3[-1,:,:-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [63]:
a5 = np.eye(5).astype(int)
a5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [66]:
aaaa= a5[:-1,:True]
aaaa

array([[1],
       [0],
       [0],
       [0]])

In [69]:
bbb = a5[:-1, :1] # same like above but readable 
bbb

array([[1],
       [0],
       [0],
       [0]])

In [70]:
a6 = np.arange(25).reshape(5,-1)
a6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
a11= a6[:-1,:True]  # True means 1 so =[ :1]
a11 

array([[ 0],
       [ 5],
       [10],
       [15]])

In [73]:
a11= a6[:-1,:0]
a11

array([], shape=(4, 0), dtype=int64)

In [74]:
print(a6[a6>2])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Fancy Indexing..

In [75]:
a6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
print(a6[[1,2,0]])

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


###### fancy Indexing for 3d array

In [78]:
aa3 = np.arange(18).reshape(3,3,2)
aa3


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [79]:
print(aa3[[0,1]])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [80]:
print(aa3[[[0,1]]])

[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]]


In [81]:
aa3[2,[0,2]]

array([[12, 13],
       [16, 17]])

In [82]:
print(aa3[-1,[-1,-2]])

[[16 17]
 [14 15]]


##### Boolean Indexing

In [83]:
a7 = np.array([10,11,15,18,17])
a7[a7>15]

array([18, 17])

In [85]:
marks = np.array([60,98,69,84,49,51])
marks[marks>55]

array([60, 98, 69, 84])

In [86]:
##### multiple condition

In [96]:
np.random.seed(12)
age = np.random.randint(1,100,20)
adults = age[(age>30)&(age<50)]
adults

array([49, 35], dtype=int32)

In [98]:
a8 = np.array([1,2,3,4,2,4,5,6])
ar= a8[(a8==2) |(a8==4)]
ar.size

4

##### np.where()

In [100]:
a9 = np.array([10,20,30,40])
b9 = np.where(a9>20,1,0)
b9

array([0, 0, 1, 1])

In [103]:
c9 = np.argwhere(a9>10) #return index
c9

array([[1],
       [2],
       [3]])

In [107]:
np.where(a9 > 10)

(array([1, 2, 3]),)

##### np.ix_() imp

In [108]:
a10 = np.arange(20).reshape(5,4)
a10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [116]:
a10[np.ix_(1)]

ValueError: Cross index must be 1 dimensional

In [117]:
a10[np.ix_([1])]

array([[4, 5, 6, 7]])

In [119]:
a10[np.ix_([1:])]

SyntaxError: invalid syntax (2491535386.py, line 1)

In [120]:
a10[np.ix_([1,2])]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
# without np.ix_()
a10[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a10[np.ix_([1,2],[2,3])]

array([[ 6,  7],
       [10, 11]])

In [126]:
# without np.ix_()
a10[[1,2],[2,3]]

array([ 6, 11])

#####  now np.take() - same like fancy indexing but fatser + flexible

In [131]:
a11 = np.array([10,20,30,40])
newarr = np.take(a11,[0,3])
newarr

array([10, 40])

In [132]:
a10


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [133]:
newarr2 = np.take(a10,[0,3])
newarr2 

array([0, 3])

In [136]:
newarr3 = np.take(a10,[0,3],axis =0) # row wise
newarr3

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [138]:
newarr4 = np.take(a10,[0,3],axis =1) # column wise
newarr4


array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])