# ASSIGNMENT: NumPy Indexing & Slicing

In [3]:
import numpy as np

In [4]:
arr = np.arange(1,21).reshape(5,-1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

### Section A – Basic Indexing

#### Q1. Extract the first element 

In [5]:
arr[0,0]

np.int64(1)

In [6]:
print(arr[0,0])

1


In [7]:
print(arr[0][0])

1


#### Q2. Extract the last element.


In [8]:
print(arr[-1][-1])

20


In [9]:
print(arr[-1,-1])

20


#### Q3. Extract the element at position (2,2).


In [10]:
print(arr[2,2])

11


In [11]:
print(arr[2][2])

11


#### Q4. Extract the element at position (3,1).

In [12]:
arr[3,1]

np.int64(14)

In [13]:
print(arr[3,1])

14


#### Q6. Extract the element at position (-1,-1).

In [14]:
print(arr[-1,-1])

20


#### Q7. Extract the element at position (-2,-3).

In [15]:
print(arr[-2,-1]) # Second last row and last column

16


#### Q8. Extract the center element.


In [16]:
print(arr[arr.size//2,arr.size//2])

IndexError: index 10 is out of bounds for axis 0 with size 5

In [17]:
print(arr[arr.shape[0]//2,arr.shape[1]//2])

11


#### Q9. Extract the top-right element.

In [18]:
print(arr[0,-1])

4


#### Q10. Extract the bottom-left element.

In [19]:
print(arr[-1,0])

17


### Section B – Row Operations

#### Q11. Extract the first row.

In [20]:
print(arr[0])

[1 2 3 4]


#### Q12. Extract the last row.

In [21]:
arr[-1]

array([17, 18, 19, 20])

#### Q13. Extract the third row.


In [22]:
arr[2]

array([ 9, 10, 11, 12])

#### Q14. Extract the first two rows.

In [23]:
arr[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Q15. Extract the last three rows.


In [24]:
arr[-3:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

#### Q16. Extract rows from index 1 to 3.


In [25]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Q17. Extract alternate rows.


In [26]:
arr[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

#### Q18. Extract rows in reverse order.


In [27]:
arr[::-1]

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

#### Q19. Extract only even-indexed rows.


In [28]:
arr[2::2]

array([[ 9, 10, 11, 12],
       [17, 18, 19, 20]])

#### Q20. Extract only odd-indexed rows.

In [29]:
arr[1::2]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

### Section C – Column Operations

#### Q21. Extract the first column.


In [30]:
arr[,0]

SyntaxError: invalid syntax (2723924206.py, line 1)

In [31]:
arr[...,0]

array([ 1,  5,  9, 13, 17])

In [32]:
arr[:,0]

array([ 1,  5,  9, 13, 17])

In [33]:
arr[:][0]

array([1, 2, 3, 4])

In [34]:
arr[0][:]

array([1, 2, 3, 4])

#### Q22. Extract the last column.


In [35]:
arr[...,-1]

array([ 4,  8, 12, 16, 20])

In [36]:
arr[:,-1]

array([ 4,  8, 12, 16, 20])

#### Q23. Extract the third column.


In [37]:
arr[:,2]

array([ 3,  7, 11, 15, 19])

#### Q24. Extract first two columns.


In [38]:
arr[...,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [39]:
arr[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

#### Q25. Extract last three columns.


In [40]:
arr[:,-3:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

#### Q26. Extract columns from index 1 to 3.


In [41]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

#### Q27. Extract alternate columns.


In [42]:
arr[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

#### Q28. Extract columns in reverse order.


In [43]:
arr[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13],
       [20, 19, 18, 17]])

#### Q29. Extract even-indexed columns.


In [44]:
arr[:,2::2]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

#### Q30. Extract odd-indexed columns.

In [45]:
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

### Section D – Slicing

#### Q31. Extract a 2×2 subarray from top-left.


In [46]:
arr[:2,:2]

array([[1, 2],
       [5, 6]])

#### Q32. Extract a 2×2 subarray from bottom-right.


In [47]:
arr[-2:,-2:]

array([[15, 16],
       [19, 20]])

#### Q33. Extract middle 3×3 matrix.


In [48]:
r ,c= arr.shape
arr[r//2-1:r//2+1,c//2-1:c//2+1]

array([[ 6,  7],
       [10, 11]])

In [49]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
r ,c= arr.shape
arr[r//2-1:r//2+2,c//2-1:c//2+2]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

#### Q34. Extract first 3 rows and first 3 columns.


In [51]:
arr[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

#### Q35. Extract last 3 rows and last 3 columns.


In [52]:
arr[-3:,-3:]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

#### Q36. Extract rows 1–3 and columns 2–4.


In [53]:
arr[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

#### Q37. Extract rows 0–2 and columns 1–3.


In [54]:
arr[:2,1:3]

array([[2, 3],
       [6, 7]])

#### Q38. Extract elements at even rows and even columns.


In [55]:
arr[::2,::2]

array([[ 1,  3],
       [ 9, 11],
       [17, 19]])

#### Q39. Extract elements at odd rows and odd columns.


In [56]:
arr[1::2,1::2]

array([[ 6,  8],
       [14, 16]])

#### Q40. Extract border elements (outer layer).

In [57]:
arr[[0,-1]]

array([[ 1,  2,  3,  4],
       [17, 18, 19, 20]])

In [58]:
arr[:,[0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

In [64]:
arr[np.ix_([0,-1],[0,-1])]

array([[ 1,  4],
       [17, 20]])

### Section E – Boolean Indexing

#### Q41. Extract elements greater than 10.


In [65]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Q42. Extract elements less than 15.

In [66]:
arr[arr<15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Q43. Extract elements between 5 and 20.


In [67]:
arr[(arr>5) &(arr<20)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### Q44. Extract all even numbers.


In [68]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Q45. Extract all odd numbers.


In [69]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### Q46. Replace values < 10 with 0.


In [70]:
arr2 = arr.copy()
np.where(arr2>10,arr2,0)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

#### Q47. Replace values > 15with 100.


In [71]:
np.where(arr<15,arr,100)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14, 100, 100],
       [100, 100, 100, 100]])

#### Q48. Extract elements divisible by 3.


In [72]:
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18])

#### Q49. Extract elements divisible by 5.


In [73]:
arr[arr%5==0]

array([ 5, 10, 15, 20])

#### Q50. Count how many elements are > 12.

In [74]:
arr[arr>12].size

8

### Section F – Mixed Operations

#### Q51. Extract diagonal elements.


In [75]:
np.diag(arr)

array([ 1,  6, 11, 16])

In [76]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
arr.diag()

AttributeError: 'numpy.ndarray' object has no attribute 'diag'

In [78]:
arr.diagonal()

array([ 1,  6, 11, 16])

#### Q52. Extract anti-diagonal elements.


In [79]:
arr[...,::-1].diagonal()

array([ 4,  7, 10, 13])

In [80]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [81]:
np.fliplr(arr).diagonal()

array([ 4,  7, 10, 13])

#### Q53. Extract first column of all rows except first.


In [83]:
arr[1:,0]

array([ 5,  9, 13, 17])

#### Q54. Extract last row except last column.


In [84]:
arr[-1,:-1]

array([17, 18, 19])

#### Q55. Extract middle row.


In [85]:
arr[arr.shape[0]//2]

array([ 9, 10, 11, 12])

In [86]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

#### Q56. Extract middle column.


In [87]:
arr[...,arr.shape[1]//2]

array([ 3,  7, 11, 15, 19])

#### Q57. Extract all corner elements.


In [90]:
arr[np.ix_([0,-1],[0,-1])]

array([[ 1,  4],
       [17, 20]])

#### Q58. Extract elements of first and last row.


In [91]:
arr[[0,-1]]

array([[ 1,  2,  3,  4],
       [17, 18, 19, 20]])

#### Q59. Extract elements of first and last column.


In [92]:
arr[...,[0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

#### Q60. Extract a cross pattern (middle row + middle column).

In [95]:
arr[np.ix_([1,2,3],[1,2])]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

### Section G – Advanced Basics

#### Q61. Reverse the array row-wise.


In [96]:
arr[::-1]

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

#### Q62. Reverse the array column-wise.


In [97]:
arr[...,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13],
       [20, 19, 18, 17]])

#### Q63. Reverse the entire array.


In [98]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [99]:
arr[::-1,::-1]

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

#### Q64. Flatten the array.


In [102]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [103]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [105]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [106]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [113]:
print(arr.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [114]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

#### Q65. Extract top 5 elements (flattened).


In [115]:
arr.reshape(-1)[:5]

array([1, 2, 3, 4, 5])

#### Q66. Extract bottom 5 elements (flattened).


In [116]:
arr.reshape(-1)[-5:]

array([16, 17, 18, 19, 20])

#### Q67. Reshape into (20,1).


In [117]:
arr.reshape(20,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

#### Q68. Reshape into (1,20).


In [119]:
arr.reshape(1,20)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

#### Q69. Swap first and last rows.


In [126]:
arr2 = arr.copy()
arr2[[0,-1]] = arr[[-1,0]]
arr2

array([[17, 18, 19, 20],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4]])

#### Q70. Swap first and last columns.

In [127]:
arr2[...,[0,-1]] = arr2[...,[-1,0]]
arr2

array([[20, 18, 19, 17],
       [ 8,  6,  7,  5],
       [12, 10, 11,  9],
       [16, 14, 15, 13],
       [ 4,  2,  3,  1]])