In [1]:
import numpy as np

### SECTION 1: BASIC ATTRIBUTE UNDERSTANDING

#### 1.Create a 1D array and find its: shape,dimension,size

In [4]:
a1 = np.array([1,2,3])
print("Shape :",a1.shape)
print("Dimension :",a1.ndim)
print("Total elements:",a1.size)

Shape : (3,)
Dimension : 1
Total elements: 3


#### 2.Create a 2D array and find its: shape,dimension,size

In [6]:
a2 = np.array([[1,2,3],[3,4,5]])
print("Shape :",a2.shape)
print("Dimension :",a2.ndim)
print("Total elements:",a2.size)

Shape : (2, 3)
Dimension : 2
Total elements: 6


#### 3. Create a 3D array and check number of dimensions.

In [7]:
a3 = np.array([1,2,3],ndmin=3)
a3

array([[[1, 2, 3]]])

In [8]:
a3.ndim

3

#### 4. Create an array and print its datatype.

In [10]:
a4 = np.array([1,2,3])
b4 = np.ones(3)
print(a4.dtype)
print(b4.dtype)

int64
float64


#### 5. Create array of floats and check dtype and itemsize.

In [15]:
a5 = np.full(10,3.8)
print(a5.dtype)
print(a5.itemsize)

float64
8


### SECTION 2: SHAPE & SIZE LOGIC

#### 6. Create array using arange(1,101) and reshape into (10×10).
#### Print shape and total size.

In [16]:
a6 = np.arange(1,101).reshape(10,10)
print("Shape: ",a6.shape)
print("Total elements : ",a6.size)

Shape:  (10, 10)
Total elements :  100


#### 7. Create array of 50 elements and reshape into possible 2D shapes.
#### Print shape for each.

In [17]:
a7 = np.arange(50).reshape(2,-1)
print(a7.shape)


(2, 25)


In [18]:
for i in range(1, 51):
    if 50 % i == 0:   
        rows = i
        cols = 50 // i
        
        reshaped = a7.reshape(rows, cols)
        print(f"Shape: ({rows}, {cols})")

Shape: (1, 50)
Shape: (2, 25)
Shape: (5, 10)
Shape: (10, 5)
Shape: (25, 2)
Shape: (50, 1)


#### 8. Create 2D array and convert it into 1D. Check shape before and after.

In [19]:
a8 = np.array([[1,2,3,4],[9,8,6,7]])
print("Before : ",a8.shape)
a8 = a8.reshape(-1)
print("After : ",a8.shape)


Before :  (2, 4)
After :  (8,)


#### 9. Create array and verify:  size = rows × columns

In [20]:
a9 = np.arange(30).reshape(5,6)
a9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [23]:
rows,cols = a9.shape
print("Rows:",rows)
print("columns : ",cols)
print("size :",a9.size)
print("Verification :",a9.size==(rows*cols))

Rows: 5
columns :  6
size : 30
Verification : True


#### 10. Create 3D array and print shape and ndim.

In [24]:
a10 = np.ones((2,1,3))
print("Shape :",a10.shape)
print("Dimension :",a10.ndim)

Shape : (2, 1, 3)
Dimension : 3


### SECTION 3: DATATYPE (dtype) PRACTICE

#### 11. Create integer array and check dtype

In [25]:
a11 = np.random.randint(1,20,10)
a11.dtype

dtype('int32')

#### 12. Convert integer array into float using .astype() and check dtype.

In [26]:
a12 = np.random.randint(1,20,10).astype(np.float32)
a12.dtype

dtype('float32')

#### 13. Create boolean array and check dtype.

In [37]:
np.random.seed(42)
a13 = np.array([np.ones(5),np.zeros(5)]).reshape(-1)
b13 = np.random.choice(a13,7).astype(np.bool)
b13

array([False,  True, False,  True, False, False,  True])

In [39]:
b13.dtype

dtype('bool')

#### 14. Create string array and check dtype.

In [40]:
a14 = np.full(10,"numpy")
a14

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [41]:
a14.dtype

dtype('<U5')

In [43]:
a14.dtype.name

'str160'

#### 15. Create array and convert it into int32.

In [45]:
a15 = np.ones(10)
a15.dtype

dtype('float64')

In [47]:
a15 =a15.astype(np.int32)
a15.dtype

dtype('int32')

#### SECTION 4: ITEMSIZE & MEMORY

#### 16 . Create integer array and find itemsize.

In [48]:
a16 = np.array([1,2,3,4,5,6])
a16.itemsize


8

#### 17. Create float array and compare itemsize with integer

In [50]:
a17= np.array([1,2,3,4],dtype=np.float64)
b17 = np.array([1,2,3,4])
print(a17)
print(b17)

[1. 2. 3. 4.]
[1 2 3 4]


In [53]:
print(a17.dtype , a17.itemsize,sep=' : ')
print(b17.dtype, b17.itemsize,sep=' : ')

float64 : 8
int64 : 8


In [55]:
c17 = np.array([1,2,3], dtype=np.int8)
d17 = np.array([1,2,3], dtype=np.float32)

print(a.itemsize) 
print(b.itemsize)

1
4


#### 18. Create array and calculate total memory used: total memory = size × itemsize

In [56]:
a18 = np.arange(100,120)
total_memory = a18.nbytes
arr_size = a18.size
item_size = a18.itemsize
print("Total Memory :",total_memory)
print("Total Items : ",arr_size)
print("Item Size : ",item_size)
print("Verification : ",total_memory == (arr_size*item_size))

Total Memory : 160
Total Items :  20
Item Size :  8
Verification :  True


### SECTION 5: LOGIC BASED ATTRIBUTE QUESTIONS

#### 19 . Create array and check if it is 1D, 2D or 3D using ndim.

In [64]:
a19 = np.array([[],[]])
print(a19.ndim,"D array ",sep='')

2D array 


In [65]:
b19 = np.array([[1],[2]])
print(b19.ndim,"D array ",sep='')

2D array 


In [66]:
c19 = np.array([[1,2,3],[3,4,5]])
print(c19.ndim,"D array ",sep='')

2D array 


In [67]:
d19 = np.array([[[1,2,3],[3,4,5]]])
print(d19.ndim,"D array ",sep='')

3D array 


In [68]:
e19 = np.array(10)
print(e19.ndim,"D array ",sep='')

0D array 


#### 20 . Write logic to verify if array is square matrix using shape.

In [73]:
a20 = np.arange(25).reshape(-1,5)
rows,cols = a20.shape
print("Rows :",rows)
print("Columns :",cols)
print("Square matrix" if rows == cols else "Not Squre Matrix")

Rows : 5
Columns : 5
Square matrix


#### 21. Check if two arrays have same shape.

## 

In [74]:
a21 = np.arange(20).reshape(-1,10)
b21 = np.arange(20).reshape(2,-1)
c21 = np.arange(20).reshape(2,-1).T
print("a21 and b21 same shape :",a21.shape == b21.shape)
print("b21 and c21 same shape :",b21.shape == c21.shape)


a21 and b21 same shape : True
b21 and c21 same shape : False


In [75]:
print("Shape of a21 array :",a21.shape)
print("Shape of b21 array :",b21.shape)
print("Shape of c21 array :",c21.shape)

Shape of a21 array : (2, 10)
Shape of b21 array : (2, 10)
Shape of c21 array : (10, 2)


#### 22. Create array and calculate memory manually and verify using attributes.

In [78]:
a22 = np.arange(10)
byte_per_ele = a22.itemsize
total_ele = a22.size
total_memory = byte_per_ele* total_ele
print("Total Memory :",total_memory)
print("Verification : ",total_memory==a22.nbytes)

Total Memory : 80
Verification :  True
