# Array Attributes

In [4]:
import numpy as np

In [5]:
a1 = np.array([1,2,3,4,5,6])
print(a1.ndim)
print(a1.size)
print(a1.dtype)
print(a1.nbytes)
print(a1.itemsize)
print(a1.shape)
print(a1.T)

1
6
int64
48
8
(6,)
[1 2 3 4 5 6]


In [6]:
a2 = np.arange(12).reshape(3,4)
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.dtype)
print(a2.nbytes)
print(a2.itemsize)
print(a2.shape)
print(a2.T)
print(a2.T.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12
int64
96
8
(3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [7]:
a3 = np.linspace(10,100,30,dtype='int32').reshape(2,15)
print(a3)
print(a3.size)
print(a3.nbytes)
print(a3.itemsize)
print(a3.shape)
print(a3.ndim)
print(a3.T)
print(a3.dtype)

[[ 10  13  16  19  22  25  28  31  34  37  41  44  47  50  53]
 [ 56  59  62  65  68  72  75  78  81  84  87  90  93  96 100]]
30
120
4
(2, 15)
2
[[ 10  56]
 [ 13  59]
 [ 16  62]
 [ 19  65]
 [ 22  68]
 [ 25  72]
 [ 28  75]
 [ 31  78]
 [ 34  81]
 [ 37  84]
 [ 41  87]
 [ 44  90]
 [ 47  93]
 [ 50  96]
 [ 53 100]]
int32


In [8]:
a = np.arange(50)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
b = np.reshape(a,(-1,25)).astype('int32')
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [ ]:
#-1 means: “NumPy decide automatically”

In [10]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]], dtype=int32)

In [11]:
print("Shape of A : ",a.shape)
print("Shape of B : ", b.shape)

Shape of A :  (50,)
Shape of B :  (2, 25)


In [12]:
print("Dimension  of A : ",a.ndim)
print("Dimension  of B : ",b.ndim)

Dimension  of A :  1
Dimension  of B :  2


In [13]:
print("Size of A : ",a.size)
print("Size of B : ",b.size)

Size of A :  50
Size of B :  50


In [14]:
print("Itemsize of A : ",a.itemsize)
print("Itemsize of B : ",b.itemsize)

Itemsize of A :  8
Itemsize of B :  4


In [15]:
print("Total bytes of A : ",a.nbytes)
print("Total bytes of B : ",b.nbytes)

Total bytes of A :  400
Total bytes of B :  200


In [16]:
print("Data types of A : ",a.dtype)
print("Data types of B : ",b.dtype)

Data types of A :  int64
Data types of B :  int32


In [17]:
print("trnaspose of A : ")
print(a.T)
print("\ntrnaspose of B : ")
print(b.T)

trnaspose of A : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

trnaspose of B : 
[[ 0 25]
 [ 1 26]
 [ 2 27]
 [ 3 28]
 [ 4 29]
 [ 5 30]
 [ 6 31]
 [ 7 32]
 [ 8 33]
 [ 9 34]
 [10 35]
 [11 36]
 [12 37]
 [13 38]
 [14 39]
 [15 40]
 [16 41]
 [17 42]
 [18 43]
 [19 44]
 [20 45]
 [21 46]
 [22 47]
 [23 48]
 [24 49]]


In [18]:
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [19]:
print(b.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [20]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]], dtype=int32)

In [22]:
print( b.sum().size)
print(b.sum(axis=0).size)
print(b.sum(axis=1).size)

1
25
2


In [23]:
print( b.sum().itemsize)
print(b.sum(axis=0).itemsize)


8
8


In [24]:
print( b.sum().shape)
print(b.sum(axis=0).shape)


()
(25,)


In [25]:
print( b.sum().nbytes)
print(b.sum(axis=0).nbytes)


8
200


In [26]:
print( b.sum().T)
print(b.sum(axis=0).T)


1225
[25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
 73]


In [27]:
print( b.sum().dtype)
print(b.sum(axis=0).dtype)


int64
int64


In [28]:
print( b.sum().ndim)
print(b.sum(axis=0).ndim)


0
1


In [29]:
a.astype('int32')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int32)

In [30]:
c = np.arange(10,dtype='int32')
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [31]:
c1 = np.array([1,2,3,4],dtype=np.int32)
c1

array([1, 2, 3, 4], dtype=int32)

In [37]:
c2 = np.array([1,2,3,4],dtype=float)
c2

array([1., 2., 3., 4.])

In [38]:
c3 = np.array(range(10),dtype=np.float32)
c3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [39]:
print(c3.astype(int))

[0 1 2 3 4 5 6 7 8 9]


In [40]:
c3 = c3.astype(int)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
c3.dtype

dtype('int64')

In [47]:
c4 = np.arange(5,dtype=np.int64)
c4

array([0, 1, 2, 3, 4])

In [48]:
c5 = np.arange(5,dtype=np.int16)
c5

array([0, 1, 2, 3, 4], dtype=int16)

In [50]:
c4 = np.arange(5,dtype=np.int8)
c4

array([0, 1, 2, 3, 4], dtype=int8)

In [51]:
c6 = np.arange(5,dtype=np.int128)
c6

AttributeError: module 'numpy' has no attribute 'int128'

In [52]:
c7 = np.array([64,64])
print(c7.sum())

128


In [53]:

c7.strides

(8,)

In [55]:
c8 = np.arange(20).reshape(2,10)
print(c8)
print(c8.strides)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(80, 8)


means:
Row jump = 80 bytes (10 elements × 8 bytes)
Column jump = 8 bytes

In [57]:
c8.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

###### Flag	        Meaning
###### OWNDATA	 - ---Own memory or borrowed
###### WRITEABL  - --Can modify or not
###### C_CONTIGUOUS- --	Row-wise storage
###### F_CONTIGUOUS ----	Column-wise storage
###### ALIGNED ----Memory is properly aligned (faster access)
###### WRITEBACKIFCOPY ---Temporary array for copy-back (internal use)

In [59]:
arrr = np.arange(10)
c9 = arrr[::2]        # view → OWNDATA False
c9.flags.writeable = False

c9.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [60]:
c9[0]=999

ValueError: assignment destination is read-only

In [62]:
c9.flags.writeable = True
c9[0]=999

In [63]:
c9

array([999,   2,   4,   6,   8])

In [64]:
a10 =np.arange(10)
a10.data

In [67]:
print(a10.base)

None


In [72]:
# a10 and b10 are same object
# Just another name (reference)
b10 =a10
print(b10.base)

None


In [73]:
c10 = a10[:]
print(c10.base)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
d10 = a10.copy()
print(d10.base)

None


In [75]:
a10.__array_interface__

{'data': (1680119967584, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (10,),
 'version': 3}

In [76]:
c10.__array_interface__

{'data': (1680119967584, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (10,),
 'version': 3}

#### Data Type Attributes

In [77]:
a11 = np.arange(25).reshape(5,5)
a11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
a11.dtype

dtype('int64')

In [80]:
a11.dtype.type

numpy.int64

In [81]:
a11.dtype.name

'int64'

In [84]:
print(a11.dtype.names)

None


In [86]:
a11.dtype.itemsize

8

In [88]:
a11.dtype.nbytes 

AttributeError: 'numpy.dtypes.Int64DType' object has no attribute 'nbytes'

In [89]:
a11.dtype.char

'q'

In [90]:
b11 = np.array([10,10,10],dtype=np.float64)
b11.dtype.char

'd'

In [92]:
c11 = np.arange(10,dtype=np.int8)
c11.dtype.char

'b'

In [ ]:
# Code	Meaning
# b	signed char (int8)
# B	unsigned char (uint8)
# h	short (int16)
# H	unsigned short (uint16)
# i	integer (int32)
# I	unsigned int (uint32)
# l	long (int64)
# L	unsigned long (uint64)
# q	long long (int64)
# Q	unsigned long long (uint64)

In [94]:
a11.dtype.kind

'i'

In [97]:
b11.dtype.kind

'f'

In [98]:
c11.dtype.kind

'i'

In [ ]:
# Kind	Meaning
# 'b'	boolean
# 'i'	signed integer
# 'u'	unsigned integer
# 'f'	floating point
# 'c'	complex
# 'O'	object
# 'S'	byte string
# 'U'	unicode string
# 'V'	void / raw
# 'M'	datetime
# 'm'	timedelta