# NumPy Broadcasting Assignment

In [1]:
import numpy as np

In [2]:
A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

C = np.array([[5],
              [10]])

D = np.array([100, 200])

E = np.array([[2, 4, 6]])

In [3]:
print(A)

[[10 20 30]
 [40 50 60]]


In [4]:
print(B)

[1 2 3]


In [5]:
print(C)

[[ 5]
 [10]]


In [6]:
print(D)

[100 200]


In [7]:
print(E)

[[2 4 6]]


# 

#### 1. Write a NumPy program to add array A and array B using broadcasting and store the result in a new variable.

In [11]:
result = A+B
result

array([[11, 22, 33],
       [41, 52, 63]])

In [12]:
result = np.add(A,B)
result

array([[11, 22, 33],
       [41, 52, 63]])

#### 2. Write a NumPy program to add array A and array C using broadcasting and display the resulting matrix.

In [15]:
result2 = A+C
print("Shape of A : ",A.shape)
print("Shape of C : ",C.shape)
print("Shape of Result Array : ",result2.shape)


Shape of A :  (2, 3)
Shape of C :  (2, 1)
Shape of Result Array :  (2, 3)


In [14]:
result2

array([[15, 25, 35],
       [50, 60, 70]])

#### 3. Write a NumPy program to perform element-wise multiplication of array A with array B using broadcasting.

In [16]:
res3 = np.multiply(A,B)
print("Shape Of Result ",res3.shape)

Shape Of Result  (2, 3)


In [17]:
res3

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [18]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
B

array([1, 2, 3])

#### 4. Write a NumPy program to multiply array A with array C using broadcasting and store the output.

In [20]:
res4 = A*C
print(res4)

[[ 50 100 150]
 [400 500 600]]


In [23]:
print("-----------Array A : ------------")
print(A)
print("-----------Array C :-------------- ")
print(C)
print("-----------RESULT : ------------")
print(res4)

-----------Array A : ------------
[[10 20 30]
 [40 50 60]]
-----------Array C :-------------- 
[[ 5]
 [10]]
-----------RESULT : ------------
[[ 50 100 150]
 [400 500 600]]


#### 5. Write a NumPy program to add arrays B and D and handle the exception if broadcasting is not possible.

In [26]:
try :
    res5 = np.add(B,D)
except ValueError as e :
    print("Broadcasting Not Possible : ",e) 
else:
    print(res5)



Broadcasting Not Possible :  operands could not be broadcast together with shapes (3,) (2,) 


#### 6. Write a NumPy program to add array E and array B using broadcasting and print the result along with its shape.

In [27]:
res6 = E+B
print("Shape of Result :",res6.shape)
print(res6)

Shape of Result : (1, 3)
[[3 6 9]]


#### 7. `Write a NumPy program to multiply array E with array C using broadcasting and display the final matrix.

In [28]:
res7 = E*C

In [29]:
print("---Array E -----")
print(E)
print("---Array C -----")
print(C)
print("---Result Array  -----")
print(res7)

---Array E -----
[[2 4 6]]
---Array C -----
[[ 5]
 [10]]
---Result Array  -----
[[10 20 30]
 [20 40 60]]


#### 8. Write a NumPy program to add a scalar value 10 to all elements of array A using broadcasting.


In [30]:
res8 = A+10
print(res8)

[[20 30 40]
 [50 60 70]]


In [31]:
A

array([[10, 20, 30],
       [40, 50, 60]])

#### 9. Write a NumPy program to subtract array C from array A using broadcasting and print the output.

In [32]:
res9 = A -C
print(res9)

[[ 5 15 25]
 [30 40 50]]


In [33]:
print("---Array  A-----")
print(A)
print("---Array C-----")
print(C)
print("---Result Array  -----")
print(res9)

---Array  A-----
[[10 20 30]
 [40 50 60]]
---Array C-----
[[ 5]
 [10]]
---Result Array  -----
[[ 5 15 25]
 [30 40 50]]


#### 10. Write a NumPy program to divide array A by array B using broadcasting and display the result in float format.

In [36]:
res10 = A/B

In [37]:
print("---Array  A-----")
print(A)
print("---Array B-----")
print(B)
print("---Result Array  -----")
print(res10)

---Array  A-----
[[10 20 30]
 [40 50 60]]
---Array B-----
[1 2 3]
---Result Array  -----
[[10. 10. 10.]
 [40. 25. 20.]]


# 

# 

## -----------------Set 2-----------------------

In [39]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([10, 20, 30])

Z = np.array([[2],
              [3],
              [4]])

P = np.array([100, 200])

Q = np.array([[1, 2, 3]])

In [40]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
Y

array([10, 20, 30])

In [42]:
Z

array([[2],
       [3],
       [4]])

In [43]:
P

array([100, 200])

In [44]:
Q

array([[1, 2, 3]])

#### 1. Write a NumPy program to add array X and array Y using broadcasting and store the result.

In [45]:
RES1 = X+Y

In [46]:
print("-----------ARRAY X -------------")
print(X)
print("-----------ARRAY Y -------------")
print(Y)
print("-----------Result  Array -------")
print(RES1)

-----------ARRAY X -------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------ARRAY Y -------------
[10 20 30]
-----------Result  Array -------
[[11 22 33]
 [14 25 36]
 [17 28 39]]


#### 2. Write a NumPy program to multiply array X with array Z using broadcasting and print the result.

In [47]:
RES2 = X*Y

In [48]:
print("-----------shape of ARRAY X -------------")
print(X.shape)
print("-----------shape of ARRAY Y -------------")
print(Y.shape)
print("-----------shape of Result  Array -------")
print(RES1.shape)
print(RES2)

-----------shape of ARRAY X -------------
(3, 3)
-----------shape of ARRAY Y -------------
(3,)
-----------shape of Result  Array -------
(3, 3)
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


#### 3. Write a NumPy program to subtract array Y from each row of array X using broadcasting.

In [49]:
RES3 = X-Y
print(RES3)

[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


In [50]:
print("-----------ARRAY X -------------")
print(X)
print("-----------ARRAY Y -------------")
print(Y)

-----------ARRAY X -------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------ARRAY Y -------------
[10 20 30]


#### 4. Write a NumPy program to divide array X by array Z using broadcasting and display the result.

In [51]:
RES4 = X/Y

In [52]:
print("-----------Result  Array -------")
print(RES4)

-----------Result  Array -------
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]
 [0.7  0.4  0.3 ]]


#### 5. Write a NumPy program to add array Q and array Z using broadcasting and print the resulting matrix.

In [53]:
RES5 = Q+Z

In [55]:
print("-----------ARRAY Q -------------")
print(Q)
print("-----------ARRAY Z -------------")
print(Z)
print("-----------Result  Array -------")
print(RES5)

-----------ARRAY Q -------------
[[1 2 3]]
-----------ARRAY Z -------------
[[2]
 [3]
 [4]]
-----------Result  Array -------
[[3 4 5]
 [4 5 6]
 [5 6 7]]


#### 6. Write a NumPy program to multiply array Q with array Y using broadcasting and display the output.

In [56]:
RES6 = Q*Y

In [57]:
print("-----------ARRAY Q -------------")
print(Q)
print("-----------ARRAY Y -------------")
print(Y)
print("-----------Result  Array -------")
print(RES6)

-----------ARRAY Q -------------
[[1 2 3]]
-----------ARRAY Y -------------
[10 20 30]
-----------Result  Array -------
[[10 40 90]]


#### 7. Write a NumPy program to check whether broadcasting is possible between arrays Y and P, and handle the error if it occurs.

In [60]:
try :
    RES7 = Y+P
    print("Broadcasting is possible ")
    print(RES7)
except ValueError as e :
    print("Broadcasting Not Possible :",e)

Broadcasting Not Possible : operands could not be broadcast together with shapes (3,) (2,) 


#### 8. Write a NumPy program to add a scalar value 5 to array X and then multiply the result with array Y using broadcasting.

In [63]:
RES8 = X+5
final_res = RES8 * Y
RES8

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [64]:
print(final_res)

[[ 60 140 240]
 [ 90 200 330]
 [120 260 420]]


#### 9. Write a NumPy program to subtract array Z from array Q using broadcasting and display the result.

In [65]:
RES10 = Q - Z

In [66]:
print("-----------ARRAY Q -------------")
print(Q)
print("-----------ARRAY Z -------------")
print(Z)
print("-----------Result  Array -------")
print(RES10)

-----------ARRAY Q -------------
[[1 2 3]]
-----------ARRAY Z -------------
[[2]
 [3]
 [4]]
-----------Result  Array -------
[[-1  0  1]
 [-2 -1  0]
 [-3 -2 -1]]


#### 10. Write a NumPy program to perform the operation (X + Y) * Z using broadcasting and store the final output.

In [67]:
RES10 = (X+Y)*Z
print(RES10)

[[ 22  44  66]
 [ 42  75 108]
 [ 68 112 156]]


## ------------------------Set 3 ---------------------------

In [2]:
M = np.array([[2, 4, 6],
              [8, 10, 12],
              [14, 16, 18]])

N = np.array([1, 3, 5])

O = np.array([[2],
              [4],
              [6]])

P_new = np.array([100, 200, 300, 400])

Q_new = np.array([[5, 10, 15]])

R = np.array([[1],
              [2],
              [3]])

In [3]:
M

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
N

array([1, 3, 5])

In [5]:
O

array([[2],
       [4],
       [6]])

In [6]:
P_new

array([100, 200, 300, 400])

In [7]:
Q_new

array([[ 5, 10, 15]])

In [8]:
R

array([[1],
       [2],
       [3]])

#### 1. Write a NumPy program to compute M + N using broadcasting and store the result.

In [9]:
rs1 = M+N

In [10]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY N -------------")
print(N)
print("-----------Result  Array -------")
print(rs1)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY N -------------
[1 3 5]
-----------Result  Array -------
[[ 3  7 11]
 [ 9 13 17]
 [15 19 23]]


#### 2. Write a NumPy program to compute M * O using broadcasting and display the output.

In [11]:
rs2 = M*O

In [12]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY O -------------")
print(O)
print("-----------Result  Array -------")
print(rs2)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY O -------------
[[2]
 [4]
 [6]]
-----------Result  Array -------
[[  4   8  12]
 [ 32  40  48]
 [ 84  96 108]]


#### 3. Write a NumPy program to compute (M + N) * O using broadcasting.

In [13]:
rs3 = (M+N)*O

In [14]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY N -------------")
print(N)
print("-----------ARRAY O -------------")
print(O)
print("-----------M+N -------------")
print(M+N)
print("-----------Result  Array -------")
print(rs3)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY N -------------
[1 3 5]
-----------ARRAY O -------------
[[2]
 [4]
 [6]]
-----------M+N -------------
[[ 3  7 11]
 [ 9 13 17]
 [15 19 23]]
-----------Result  Array -------
[[  6  14  22]
 [ 36  52  68]
 [ 90 114 138]]


#### 4. Write a NumPy program to subtract array N from each row of array M using broadcasting.

In [15]:
rs4 =np.subtract(M,N)

In [16]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY N -------------")
print(N)
print("-----------Result  Array -------")
print(rs4)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY N -------------
[1 3 5]
-----------Result  Array -------
[[ 1  1  1]
 [ 7  7  7]
 [13 13 13]]


#### 5. Write a NumPy program to check whether broadcasting is possible between arrays N and P_new, and handle the error properly.

In [17]:
try :
    res5 = N+P_new
    print(res5)
except ValueError as e :
    print("Broadcasting Not Possible : ",e)
finally:
    print("Shape of N :",N.shape)
    print("Shape of P_new : ",P_new.shape)

Broadcasting Not Possible :  operands could not be broadcast together with shapes (3,) (4,) 
Shape of N : (3,)
Shape of P_new :  (4,)


#### 6. Write a NumPy program to compute Q_new + N and display the result with its shape.

In [18]:
rs6 = Q_new +N

In [19]:
print("-----------ARRAY Q_new  -------------")
print(Q_new)
print("-----------ARRAY N -------------")
print(N)
print("-----------Result  Array -------")
print(rs6)
print("Shape of Result :",rs6.shape)

-----------ARRAY Q_new  -------------
[[ 5 10 15]]
-----------ARRAY N -------------
[1 3 5]
-----------Result  Array -------
[[ 6 13 20]]
Shape of Result : (1, 3)


#### 7. Write a NumPy program to compute Q_new * R using broadcasting and print the final matrix.

In [20]:
rs7 = Q_new * R

In [21]:
print("-----------ARRAY Q_new  -------------")
print(Q_new)
print("-----------ARRAY R -------------")
print(R)
print("-----------Result  Array -------")
print(rs7)

-----------ARRAY Q_new  -------------
[[ 5 10 15]]
-----------ARRAY R -------------
[[1]
 [2]
 [3]]
-----------Result  Array -------
[[ 5 10 15]
 [10 20 30]
 [15 30 45]]


#### 8. Write a NumPy program to reshape array N into a column vector and add it to array M using broadcasting.

In [25]:
rs8 = M + N.reshape(-1, 1)

In [26]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY N -------------")
print(N)
print("----------- array N into a column vector -------------")
print(N.reshape(-1, 1))
print("-----------Result  Array -------")
print(rs8)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY N -------------
[1 3 5]
----------- array N into a column vector -------------
[[1]
 [3]
 [5]]
-----------Result  Array -------
[[ 3  5  7]
 [11 13 15]
 [19 21 23]]


#### 9. Write a NumPy program to compute M - O and then divide the result by N using broadcasting.

In [27]:
rs9 = (M-O)/N

In [30]:
print("-----------ARRAY M  -------------")
print(M)
print("-----------ARRAY O -------------")
print(O)
print("-----------ARRAY N -------------")
print(N)
print("----------- (M-O)----------")
print(M-O)
print("-----------Result  Array -------")
print(rs9)

-----------ARRAY M  -------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-----------ARRAY O -------------
[[2]
 [4]
 [6]]
-----------ARRAY N -------------
[1 3 5]
----------- (M-O)----------
[[ 0  2  4]
 [ 4  6  8]
 [ 8 10 12]]
-----------Result  Array -------
[[0.         0.66666667 0.8       ]
 [4.         2.         1.6       ]
 [8.         3.33333333 2.4       ]]


#### 10 . Write a NumPy program to normalize array M by subtracting the row-wise mean using broadcasting.

In [31]:
row_mean = M.mean(axis=1).reshape(-1, 1)
norm_M = M - row_mean
print(norm_M)


[[-2.  0.  2.]
 [-2.  0.  2.]
 [-2.  0.  2.]]
